namespace GEN.ORT.YYY
{
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //
  //                    Source Code Generated by
  //                           CA Gen 8.6
  //
  //    Copyright (c) 2024 CA Technologies. All rights reserved.
  //
  //    Name: MYY10421_XML_PARSE               Date: 2024/01/09
  //    Target OS:   CLR                       Time: 13:41:31
  //    Target DBMS: ODBC/ADO.NET              User: AliAl
  //    Access Method: <NONE>         
  //
  //    Generation options:
  //    Debug trace option not selected
  //    Data modeling constraint enforcement not selected
  //    Optimized import view initialization not selected
  //    Enforce default values with DBMS not selected
  //    Init unspecified optional fields to NULL not selected
  //
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // using Statements
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  using System;
  using com.ca.gen.vwrt;
  using com.ca.gen.vwrt.types;
  using com.ca.gen.vwrt.vdf;
  using com.ca.gen.csu.exception;
  
  using com.ca.gen.abrt;
  using com.ca.gen.abrt.functions;
  using com.ca.gen.abrt.cascade;
  using com.ca.gen.abrt.manager;
  using com.ca.gen.abrt.trace;
  using com.ca.gen.exits.common;
  using com.ca.gen.odc;
  using System.Data;
  using System.Collections;
  
  public class MYY10421 : ABBase
  {
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // IMPORT VIEW CLASS VARIABLE
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    MYY10421_IA WIa;
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // EXPORT VIEW CLASS VARIABLE
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    MYY10421_OA WOa;
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // LOCAL VIEW CLASS VARIABLE
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    MYY10421_LA WLa;
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // ACTION BLOCK IMPORT/EXPORT VIEWS CLASS VARIABLES
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    GEN.ORT.YYY.CYYY0421_IA Cyyy0421Ia;
    GEN.ORT.YYY.CYYY0421_OA Cyyy0421Oa;
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // MISC DECLARATIONS AND PROTOTYPES 
    //    FOLLOW AS NEEDED:             
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    bool func_0022020166_esc_flag;
    //       +->   MYY10421_XML_PARSE                01/09/2024  13:41
    //       !       IMPORTS:
    //       !         Work View imp canam_xml (Transient, Optional, Import
    //       !                     only)
    //       !           xml_buffer
    //       !       EXPORTS:
    //       !         Entity View exp iyy1_type (Transient, Export only)
    //       !           tinstance_id
    //       !           treference_id
    //       !           tcreate_user_id
    //       !           tupdate_user_id
    //       !           tkey_attr_text
    //       !           tsearch_attr_text
    //       !           tother_attr_text
    //       !           tother_attr_date
    //       !           tother_attr_time
    //       !           tother_attr_amount
    //       !         Work View exp_error canam_xml (Transient, Export only)
    //       !           xml_return_code
    //       !           xml_message
    //       !           xml_position
    //       !           xml_source
    //       !         Work View exp_error iyy1_component (Transient, Export
    //       !                     only)
    //       !           severity_code
    //       !           rollback_indicator
    //       !           origin_servid
    //       !           context_string
    //       !           return_code
    //       !           reason_code
    //       !           checksum
    //       !       LOCALS:
    //       !         Entity View loc_exp type
    //       !           tinstance_id
    //       !           treference_id
    //       !           tcreate_user_id
    //       !           tupdate_user_id
    //       !           tkey_attr_text
    //       !           tsearch_attr_text
    //       !           tother_attr_text
    //       !           tother_attr_date
    //       !           tother_attr_time
    //       !           tother_attr_amount
    //       !
    //       !     PROCEDURE STATEMENTS
    //       !
    //     1 !  NOTE: 
    //     1 !  Check description for porpose
    //     1 !  
    //     2 !  NOTE: 
    //     2 !  RELEASE HISTORY
    //     2 !  01_00 01-10-2009 New Release
    //     2 !  
    //     3 !  NOTE: 
    //     3 !  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //     3 !  !!!!!!!!!!!!
    //     3 !  SET <loc imp*> TO <imp*>
    //     3 !  
    //     4 !  USE cyyy0421_xml_parse
    //     4 !     WHICH IMPORTS: Work View imp canam_xml TO Work View imp
    //     4 !              canam_xml
    //     4 !     WHICH EXPORTS: Work View exp_error canam_xml FROM Work View
    //     4 !              exp_error canam_xml
    //     4 !                    Work View exp_error iyy1_component FROM Work
    //     4 !              View exp_error iyy1_component
    //     4 !                    Entity View loc_exp type FROM Entity View
    //     4 !              exp type
    //     5 !   
    //     6 !  NOTE: 
    //     6 !  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //     6 !  !!!!!!!!!!!!
    //     6 !  SET <exp*> TO <loc exp*>
    //     6 !  
    //     7 !  SET exp iyy1_type tinstance_id TO loc_exp type tinstance_id 
    //     8 !  SET exp iyy1_type treference_id TO loc_exp type treference_id 
    //     9 !  SET exp iyy1_type tcreate_user_id TO loc_exp type
    //     9 !              tcreate_user_id 
    //    10 !  SET exp iyy1_type tupdate_user_id TO loc_exp type
    //    10 !              tupdate_user_id 
    //    11 !  SET exp iyy1_type tkey_attr_text TO loc_exp type
    //    11 !              tkey_attr_text 
    //    12 !  SET exp iyy1_type tsearch_attr_text TO loc_exp type
    //    12 !              tsearch_attr_text 
    //    13 !  SET exp iyy1_type tother_attr_text TO loc_exp type
    //    13 !              tother_attr_text 
    //    14 !  SET exp iyy1_type tother_attr_date TO loc_exp type
    //    14 !              tother_attr_date 
    //    15 !  SET exp iyy1_type tother_attr_time TO loc_exp type
    //    15 !              tother_attr_time 
    //    16 !  SET exp iyy1_type tother_attr_amount TO loc_exp type
    //    16 !              tother_attr_amount 
    //    17 !   
    //       +---
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    //  CONSTRUCTOR FOR THE CLASS       
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    public MYY10421(  )
    {
      IefCGenRlse = "CA Gen 8.6";
      IsCopyright = "Copyright (c) 2024 CA Technologies. All rights reserved.";
      IefCGenDate = "2024/01/09";
      IefCGenTime = "13:41:31";
      IefCGenEncy = "9.2.A6";
      IefCGenUserId = "AliAl";
      IefCGenModel = "N8I_ORT_YYY_0112_TEMPLATE";
      IefCGenSubset = "ALL";
      IefCGenName = "MYY10421_XML_PARSE";
      NestingLevel = 0;
      ValChkDeadlockTimeout = false;
      ValChkDBError = false;
    }
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // ACTION BLOCK FUNCTION DECLARATIONS 
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    
    public void Execute( Object in_runtime_parm1, 
    	IRuntimePStepContext in_runtime_parm2, 
    	GlobData in_globdata, 
    	MYY10421_IA import_view, 
    	MYY10421_OA export_view )
    {
      IefRuntimeParm1 = in_runtime_parm1;
      IefRuntimeParm2 = in_runtime_parm2;
      Globdata = in_globdata;
      WIa = import_view;
      WOa = export_view;
      _Execute();
    }
    
    private void _Execute()
    {
      
      f_22020166_localAlloc( "MYY10421_XML_PARSE" );
      if ( Globdata.GetErrorData().GetLastStatus() == ErrorData.LastStatusIefAllocationError )
      	return;
      
      ++(NestingLevel);
      try {
        f_22020166_init(  );
        f_22020166(  );
      } catch( Exception e ) {
        if ( ((Globdata.GetErrorData().GetStatus() == ErrorData.StatusNone) && (Globdata.GetErrorData().GetErrorEncountered() == 
          ErrorData.ErrorEncounteredNoErrorFound)) && (Globdata.GetErrorData().GetViewOverflow() == 
          ErrorData.ErrorEncounteredNoErrorFound) )
        {
          Globdata.GetErrorData().SetStatus( ErrorData.LastStatusFatalError );
          Globdata.GetErrorData().SetLastStatus( ErrorData.LastStatusUnexpectedExceptionError );
          Globdata.GetErrorData().SetErrorEncountered( ErrorData.ErrorEncounteredErrorFound );
          Globdata.GetErrorData(  ).SetErrorMessage( e );
        }
      }
      --(NestingLevel);
    }
    public void f_22020166(  )
    {
      func_0022020166_esc_flag = false;
      Globdata.GetStateData().SetCurrentABId( "0022020166" );
      Globdata.GetStateData().SetCurrentABName( "MYY10421_XML_PARSE" );
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    Check description for porpose                                   
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    RELEASE HISTORY                                                 
      //    01_00 01-10-2009 New Release                                    
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
      //    !!!!!!!!!!!!                                                    
      //    SET <loc imp*> TO <imp*>                                        
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      Globdata.GetStateData().SetLastStatementNumber( "0000000004" );
      
      Cyyy0421Ia = (GEN.ORT.YYY.CYYY0421_IA)(IefRuntimeParm2.GetInstance( typeof(GEN.ORT.YYY.CYYY0421).Assembly,
      	"GEN.ORT.YYY.CYYY0421_IA" ));
      Cyyy0421Oa = (GEN.ORT.YYY.CYYY0421_OA)(IefRuntimeParm2.GetInstance( typeof(GEN.ORT.YYY.CYYY0421).Assembly,
      	"GEN.ORT.YYY.CYYY0421_OA" ));
      Cyyy0421Ia.ImpCanamXmlXmlBuffer = StringAttr.ValueOf(WIa.ImpCanamXmlXmlBuffer, 4094);
      Globdata.GetErrorData().SetErrorEncountered( ErrorData.ErrorEncounteredNoErrorFound );
      IefRuntimeParm2.UseActionBlock( typeof(GEN.ORT.YYY.CYYY0421).Assembly,
      	"GEN.ORT.YYY.CYYY0421",
      	"Execute",
      	Cyyy0421Ia,
      	Cyyy0421Oa );
      if ( ((Globdata.GetErrorData().GetStatus() != ErrorData.StatusNone) || (Globdata.GetErrorData().GetErrorEncountered() != 
        ErrorData.ErrorEncounteredNoErrorFound)) || (Globdata.GetErrorData().GetViewOverflow() != 
        ErrorData.ErrorEncounteredNoErrorFound) )
      {
        throw new ABException();
      }
      Globdata.GetStateData().SetCurrentABId( "0022020166" );
      Globdata.GetStateData().SetCurrentABName( "MYY10421_XML_PARSE" );
      Globdata.GetStateData().SetLastStatementNumber( "0000000004" );
      WLa.LocExpTypeTinstanceId = TimestampAttr.ValueOf(Cyyy0421Oa.ExpTypeTinstanceId);
      WLa.LocExpTypeTreferenceId = TimestampAttr.ValueOf(Cyyy0421Oa.ExpTypeTreferenceId);
      WLa.LocExpTypeTcreateUserId = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpTypeTcreateUserId, 8);
      WLa.LocExpTypeTupdateUserId = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpTypeTupdateUserId, 8);
      WLa.LocExpTypeTkeyAttrText = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpTypeTkeyAttrText, 4);
      WLa.LocExpTypeTsearchAttrText = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpTypeTsearchAttrText, 20);
      WLa.LocExpTypeTotherAttrText = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpTypeTotherAttrText, 2);
      WLa.LocExpTypeTotherAttrDate = DateAttr.ValueOf(Cyyy0421Oa.ExpTypeTotherAttrDate);
      WLa.LocExpTypeTotherAttrTime = TimeAttr.ValueOf(Cyyy0421Oa.ExpTypeTotherAttrTime);
      WLa.LocExpTypeTotherAttrAmount = DecimalAttr.ValueOf(Cyyy0421Oa.ExpTypeTotherAttrAmount);
      WOa.ExpErrorIyy1ComponentSeverityCode = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpErrorIyy1ComponentSeverityCode, 1);
      WOa.ExpErrorIyy1ComponentRollbackIndicator = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpErrorIyy1ComponentRollbackIndicator, 1);
      WOa.ExpErrorIyy1ComponentOriginServid = DoubleAttr.ValueOf(Cyyy0421Oa.ExpErrorIyy1ComponentOriginServid);
      WOa.ExpErrorIyy1ComponentContextString = StringAttr.ValueOf(Cyyy0421Oa.ExpErrorIyy1ComponentContextString, 512);
      WOa.ExpErrorIyy1ComponentReturnCode = IntAttr.ValueOf(Cyyy0421Oa.ExpErrorIyy1ComponentReturnCode);
      WOa.ExpErrorIyy1ComponentReasonCode = IntAttr.ValueOf(Cyyy0421Oa.ExpErrorIyy1ComponentReasonCode);
      WOa.ExpErrorIyy1ComponentChecksum = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpErrorIyy1ComponentChecksum, 15);
      WOa.ExpErrorCanamXmlXmlReturnCode = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpErrorCanamXmlXmlReturnCode, 2);
      WOa.ExpErrorCanamXmlXmlMessage = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpErrorCanamXmlXmlMessage, 80);
      WOa.ExpErrorCanamXmlXmlPosition = DoubleAttr.ValueOf(Cyyy0421Oa.ExpErrorCanamXmlXmlPosition);
      WOa.ExpErrorCanamXmlXmlSource = FixedStringAttr.ValueOf(Cyyy0421Oa.ExpErrorCanamXmlXmlSource, 120);
      Cyyy0421Ia.FreeInstance(  );
      Cyyy0421Ia = null;
      Cyyy0421Oa.FreeInstance(  );
      Cyyy0421Oa = null;
      
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
      //    !!!!!!!!!!!!                                                    
      //    SET <exp*> TO <loc exp*>                                        
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      Globdata.GetStateData().SetLastStatementNumber( "0000000007" );
      WOa.ExpIyy1TypeTinstanceId = TimestampAttr.ValueOf(WLa.LocExpTypeTinstanceId);
      Globdata.GetStateData().SetLastStatementNumber( "0000000008" );
      WOa.ExpIyy1TypeTreferenceId = TimestampAttr.ValueOf(WLa.LocExpTypeTreferenceId);
      Globdata.GetStateData().SetLastStatementNumber( "0000000009" );
      WOa.ExpIyy1TypeTcreateUserId = FixedStringAttr.ValueOf(WLa.LocExpTypeTcreateUserId, 8);
      Globdata.GetStateData().SetLastStatementNumber( "0000000010" );
      WOa.ExpIyy1TypeTupdateUserId = FixedStringAttr.ValueOf(WLa.LocExpTypeTupdateUserId, 8);
      Globdata.GetStateData().SetLastStatementNumber( "0000000011" );
      WOa.ExpIyy1TypeTkeyAttrText = FixedStringAttr.ValueOf(WLa.LocExpTypeTkeyAttrText, 4);
      Globdata.GetStateData().SetLastStatementNumber( "0000000012" );
      WOa.ExpIyy1TypeTsearchAttrText = FixedStringAttr.ValueOf(WLa.LocExpTypeTsearchAttrText, 20);
      Globdata.GetStateData().SetLastStatementNumber( "0000000013" );
      WOa.ExpIyy1TypeTotherAttrText = FixedStringAttr.ValueOf(WLa.LocExpTypeTotherAttrText, 2);
      Globdata.GetStateData().SetLastStatementNumber( "0000000014" );
      WOa.ExpIyy1TypeTotherAttrDate = DateAttr.ValueOf(WLa.LocExpTypeTotherAttrDate);
      Globdata.GetStateData().SetLastStatementNumber( "0000000015" );
      WOa.ExpIyy1TypeTotherAttrTime = TimeAttr.ValueOf(WLa.LocExpTypeTotherAttrTime);
      Globdata.GetStateData().SetLastStatementNumber( "0000000016" );
      WOa.ExpIyy1TypeTotherAttrAmount = DecimalAttr.ValueOf(TIRBDTRU.TruncateToDecimal( WLa.LocExpTypeTotherAttrAmount, 2));
      
      return;
    }
    
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // SUBORDINATE FUNCTIONS
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // INITIALIZATION UTILITY FUNCTIONS 
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    
    public void f_22020166_localAlloc( String abname )
    {
      // Request localview allocation 
      WLa = (GEN.ORT.YYY.MYY10421_LA)(IefRuntimeParm2.GetInstance( GetType().Assembly,
      	"GEN.ORT.YYY.MYY10421_LA" ));
      if ( WLa == null )
      {
        Globdata.GetStateData().SetCurrentABId( "0022020166" );
        Globdata.GetStateData().SetCurrentABName( abname );
        Globdata.GetErrorData().SetErrorEncountered( ErrorData.ErrorEncounteredErrorFound );
        Globdata.GetErrorData().SetLastStatus( ErrorData.LastStatusIefAllocationError );
      }
    }
    
    public void f_22020166_init(  )
    {
      if ( NestingLevel < 2 )
      {
        WLa.Reset();
      }
      WOa.ExpIyy1TypeTinstanceId = "00000000000000000000";
      WOa.ExpIyy1TypeTreferenceId = "00000000000000000000";
      WOa.ExpIyy1TypeTcreateUserId = "        ";
      WOa.ExpIyy1TypeTupdateUserId = "        ";
      WOa.ExpIyy1TypeTkeyAttrText = "    ";
      WOa.ExpIyy1TypeTsearchAttrText = "                    ";
      WOa.ExpIyy1TypeTotherAttrText = "  ";
      WOa.ExpIyy1TypeTotherAttrDate = 00000000;
      WOa.ExpIyy1TypeTotherAttrTime = 00000000;
      WOa.ExpIyy1TypeTotherAttrAmount = DecimalAttr.GetDefaultValue();
      WOa.ExpErrorCanamXmlXmlReturnCode = "  ";
      WOa.ExpErrorCanamXmlXmlMessage = "                                                                                ";
      WOa.ExpErrorCanamXmlXmlPosition = 0.0;
      WOa.ExpErrorCanamXmlXmlSource = 
        "                                                                                                                        ";
      WOa.ExpErrorIyy1ComponentSeverityCode = " ";
      WOa.ExpErrorIyy1ComponentRollbackIndicator = " ";
      WOa.ExpErrorIyy1ComponentOriginServid = 0.0;
      WOa.ExpErrorIyy1ComponentContextString = "";
      WOa.ExpErrorIyy1ComponentReturnCode = 0;
      WOa.ExpErrorIyy1ComponentReasonCode = 0;
      WOa.ExpErrorIyy1ComponentChecksum = "               ";
    }
  }// end class
  
}

