namespace GEN.ORT.YYY
{
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //
  //                    Source Code Generated by
  //                           CA Gen 8.6
  //
  //    Copyright (c) 2024 CA Technologies. All rights reserved.
  //
  //    Name: MYY10231_CHILD_UPDATE            Date: 2024/01/09
  //    Target OS:   CLR                       Time: 13:42:04
  //    Target DBMS: ODBC/ADO.NET              User: AliAl
  //    Access Method: <NONE>         
  //
  //    Generation options:
  //    Debug trace option not selected
  //    Data modeling constraint enforcement not selected
  //    Optimized import view initialization not selected
  //    Enforce default values with DBMS not selected
  //    Init unspecified optional fields to NULL not selected
  //
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // using Statements
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  using System;
  using com.ca.gen.vwrt;
  using com.ca.gen.vwrt.types;
  using com.ca.gen.vwrt.vdf;
  using com.ca.gen.csu.exception;
  
  using com.ca.gen.abrt;
  using com.ca.gen.abrt.functions;
  using com.ca.gen.abrt.cascade;
  using com.ca.gen.abrt.manager;
  using com.ca.gen.abrt.trace;
  using com.ca.gen.exits.common;
  using com.ca.gen.odc;
  using System.Data;
  using System.Collections;
  
  public class MYY10231 : ABBase
  {
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // IMPORT VIEW CLASS VARIABLE
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    MYY10231_IA WIa;
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // EXPORT VIEW CLASS VARIABLE
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    MYY10231_OA WOa;
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // LOCAL VIEW CLASS VARIABLE
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    MYY10231_LA WLa;
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // ACTION BLOCK IMPORT/EXPORT VIEWS CLASS VARIABLES
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    GEN.ORT.YYY.CYYY0231_IA Cyyy0231Ia;
    GEN.ORT.YYY.CYYY0231_OA Cyyy0231Oa;
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // MISC DECLARATIONS AND PROTOTYPES 
    //    FOLLOW AS NEEDED:             
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    bool func_0022020110_esc_flag;
    //       +->   MYY10231_CHILD_UPDATE             01/09/2024  13:42
    //       !       IMPORTS:
    //       !         Work View imp_reference iyy1_server_data (Transient,
    //       !                     Mandatory, Import only)
    //       !           userid
    //       !           reference_id
    //       !         Entity View imp iyy1_child (Transient, Mandatory,
    //       !                     Import only)
    //       !           cinstance_id
    //       !           creference_id
    //       !           cparent_pkey_attr_text
    //       !           ckey_attr_num
    //       !           csearch_attr_text
    //       !           cother_attr_text
    //       !       EXPORTS:
    //       !         Entity View exp iyy1_child (Transient, Export only)
    //       !           creference_id
    //       !         Work View exp_error iyy1_component (Transient, Export
    //       !                     only)
    //       !           severity_code
    //       !           rollback_indicator
    //       !           origin_servid
    //       !           context_string
    //       !           return_code
    //       !           reason_code
    //       !           checksum
    //       !       LOCALS:
    //       !         Entity View loc_imp child
    //       !           cinstance_id
    //       !           creference_id
    //       !           cparent_pkey_attr_text
    //       !           ckey_attr_num
    //       !           csearch_attr_text
    //       !           cother_attr_text
    //       !         Entity View loc_exp child
    //       !           creference_id
    //       !
    //       !     PROCEDURE STATEMENTS
    //       !
    //     1 !  NOTE: 
    //     1 !  See the description for the purpose
    //     2 !   
    //     3 !  NOTE: 
    //     3 !  RELEASE HISTORY
    //     3 !  01_00 23-02-1998 New release
    //     3 !  
    //     4 !  NOTE: 
    //     4 !  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //     4 !  !!!!!!!!!!!!
    //     4 !  SET <loc imp*> TO <imp*>
    //     4 !  
    //     5 !  SET loc_imp child cinstance_id TO imp iyy1_child cinstance_id 
    //     6 !  SET loc_imp child creference_id TO imp iyy1_child
    //     6 !              creference_id 
    //     7 !  SET loc_imp child cparent_pkey_attr_text TO imp iyy1_child
    //     7 !              cparent_pkey_attr_text 
    //     8 !  SET loc_imp child ckey_attr_num TO imp iyy1_child
    //     8 !              ckey_attr_num 
    //     9 !  SET loc_imp child csearch_attr_text TO imp iyy1_child
    //     9 !              csearch_attr_text 
    //    10 !  SET loc_imp child cother_attr_text TO imp iyy1_child
    //    10 !              cother_attr_text 
    //    11 !   
    //    12 !  NOTE: 
    //    12 !  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //    12 !  !!!!!!!!!!!!
    //    12 !  USE <implementation ab>
    //    12 !  
    //    13 !  USE cyyy0231_child_update
    //    13 !     WHICH IMPORTS: Entity View loc_imp child TO Entity View imp
    //    13 !              child
    //    13 !                    Work View imp_reference iyy1_server_data TO
    //    13 !              Work View imp_reference iyy1_server_data
    //    13 !     WHICH EXPORTS: Entity View loc_exp child FROM Entity View
    //    13 !              exp child
    //    13 !                    Work View exp_error iyy1_component FROM Work
    //    13 !              View exp_error iyy1_component
    //    14 !   
    //    15 !  NOTE: 
    //    15 !  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    //    15 !  !!!!!!!!!!!!
    //    15 !  SET <exp*> TO <loc exp*>
    //    15 !  
    //    16 !  SET exp iyy1_child creference_id TO loc_exp child
    //    16 !              creference_id 
    //       +---
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    //  CONSTRUCTOR FOR THE CLASS       
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    public MYY10231(  )
    {
      IefCGenRlse = "CA Gen 8.6";
      IsCopyright = "Copyright (c) 2024 CA Technologies. All rights reserved.";
      IefCGenDate = "2024/01/09";
      IefCGenTime = "13:42:04";
      IefCGenEncy = "9.2.A6";
      IefCGenUserId = "AliAl";
      IefCGenModel = "N8I_ORT_YYY_0112_TEMPLATE";
      IefCGenSubset = "ALL";
      IefCGenName = "MYY10231_CHILD_UPDATE";
      NestingLevel = 0;
      ValChkDeadlockTimeout = false;
      ValChkDBError = false;
    }
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // ACTION BLOCK FUNCTION DECLARATIONS 
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    
    public void Execute( Object in_runtime_parm1, 
    	IRuntimePStepContext in_runtime_parm2, 
    	GlobData in_globdata, 
    	MYY10231_IA import_view, 
    	MYY10231_OA export_view )
    {
      IefRuntimeParm1 = in_runtime_parm1;
      IefRuntimeParm2 = in_runtime_parm2;
      Globdata = in_globdata;
      WIa = import_view;
      WOa = export_view;
      _Execute();
    }
    
    private void _Execute()
    {
      
      f_22020110_localAlloc( "MYY10231_CHILD_UPDATE" );
      if ( Globdata.GetErrorData().GetLastStatus() == ErrorData.LastStatusIefAllocationError )
      	return;
      
      ++(NestingLevel);
      try {
        f_22020110_init(  );
        f_22020110(  );
      } catch( Exception e ) {
        if ( ((Globdata.GetErrorData().GetStatus() == ErrorData.StatusNone) && (Globdata.GetErrorData().GetErrorEncountered() == 
          ErrorData.ErrorEncounteredNoErrorFound)) && (Globdata.GetErrorData().GetViewOverflow() == 
          ErrorData.ErrorEncounteredNoErrorFound) )
        {
          Globdata.GetErrorData().SetStatus( ErrorData.LastStatusFatalError );
          Globdata.GetErrorData().SetLastStatus( ErrorData.LastStatusUnexpectedExceptionError );
          Globdata.GetErrorData().SetErrorEncountered( ErrorData.ErrorEncounteredErrorFound );
          Globdata.GetErrorData(  ).SetErrorMessage( e );
        }
      }
      --(NestingLevel);
    }
    public void f_22020110(  )
    {
      func_0022020110_esc_flag = false;
      Globdata.GetStateData().SetCurrentABId( "0022020110" );
      Globdata.GetStateData().SetCurrentABName( "MYY10231_CHILD_UPDATE" );
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    See the description for the purpose                             
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    RELEASE HISTORY                                                 
      //    01_00 23-02-1998 New release                                    
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
      //    !!!!!!!!!!!!                                                    
      //    SET <loc imp*> TO <imp*>                                        
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      Globdata.GetStateData().SetLastStatementNumber( "0000000005" );
      WLa.LocImpChildCinstanceId = TimestampAttr.ValueOf(WIa.ImpIyy1ChildCinstanceId);
      Globdata.GetStateData().SetLastStatementNumber( "0000000006" );
      WLa.LocImpChildCreferenceId = TimestampAttr.ValueOf(WIa.ImpIyy1ChildCreferenceId);
      Globdata.GetStateData().SetLastStatementNumber( "0000000007" );
      WLa.LocImpChildCparentPkeyAttrText = FixedStringAttr.ValueOf(WIa.ImpIyy1ChildCparentPkeyAttrText, 5);
      Globdata.GetStateData().SetLastStatementNumber( "0000000008" );
      WLa.LocImpChildCkeyAttrNum = IntAttr.ValueOf((int)TIRD2DEC.Execute1((double) WIa.ImpIyy1ChildCkeyAttrNum, 0, 
        TIRD2DEC.ROUND_NONE, 6));
      Globdata.GetStateData().SetLastStatementNumber( "0000000009" );
      WLa.LocImpChildCsearchAttrText = FixedStringAttr.ValueOf(WIa.ImpIyy1ChildCsearchAttrText, 25);
      Globdata.GetStateData().SetLastStatementNumber( "0000000010" );
      WLa.LocImpChildCotherAttrText = FixedStringAttr.ValueOf(WIa.ImpIyy1ChildCotherAttrText, 25);
      
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
      //    !!!!!!!!!!!!                                                    
      //    USE <implementation ab>                                         
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      Globdata.GetStateData().SetLastStatementNumber( "0000000013" );
      
      Cyyy0231Ia = (GEN.ORT.YYY.CYYY0231_IA)(IefRuntimeParm2.GetInstance( typeof(GEN.ORT.YYY.CYYY0231).Assembly,
      	"GEN.ORT.YYY.CYYY0231_IA" ));
      Cyyy0231Oa = (GEN.ORT.YYY.CYYY0231_OA)(IefRuntimeParm2.GetInstance( typeof(GEN.ORT.YYY.CYYY0231).Assembly,
      	"GEN.ORT.YYY.CYYY0231_OA" ));
      Cyyy0231Ia.ImpReferenceIyy1ServerDataUserid = FixedStringAttr.ValueOf(WIa.ImpReferenceIyy1ServerDataUserid, 8);
      Cyyy0231Ia.ImpReferenceIyy1ServerDataReferenceId = TimestampAttr.ValueOf(WIa.ImpReferenceIyy1ServerDataReferenceId);
      Cyyy0231Ia.ImpChildCinstanceId = TimestampAttr.ValueOf(WLa.LocImpChildCinstanceId);
      Cyyy0231Ia.ImpChildCreferenceId = TimestampAttr.ValueOf(WLa.LocImpChildCreferenceId);
      Cyyy0231Ia.ImpChildCparentPkeyAttrText = FixedStringAttr.ValueOf(WLa.LocImpChildCparentPkeyAttrText, 5);
      Cyyy0231Ia.ImpChildCkeyAttrNum = IntAttr.ValueOf(WLa.LocImpChildCkeyAttrNum);
      Cyyy0231Ia.ImpChildCsearchAttrText = FixedStringAttr.ValueOf(WLa.LocImpChildCsearchAttrText, 25);
      Cyyy0231Ia.ImpChildCotherAttrText = FixedStringAttr.ValueOf(WLa.LocImpChildCotherAttrText, 25);
      Globdata.GetErrorData().SetErrorEncountered( ErrorData.ErrorEncounteredNoErrorFound );
      IefRuntimeParm2.UseActionBlock( typeof(GEN.ORT.YYY.CYYY0231).Assembly,
      	"GEN.ORT.YYY.CYYY0231",
      	"Execute",
      	Cyyy0231Ia,
      	Cyyy0231Oa );
      if ( ((Globdata.GetErrorData().GetStatus() != ErrorData.StatusNone) || (Globdata.GetErrorData().GetErrorEncountered() != 
        ErrorData.ErrorEncounteredNoErrorFound)) || (Globdata.GetErrorData().GetViewOverflow() != 
        ErrorData.ErrorEncounteredNoErrorFound) )
      {
        throw new ABException();
      }
      Globdata.GetStateData().SetCurrentABId( "0022020110" );
      Globdata.GetStateData().SetCurrentABName( "MYY10231_CHILD_UPDATE" );
      Globdata.GetStateData().SetLastStatementNumber( "0000000013" );
      WOa.ExpErrorIyy1ComponentSeverityCode = FixedStringAttr.ValueOf(Cyyy0231Oa.ExpErrorIyy1ComponentSeverityCode, 1);
      WOa.ExpErrorIyy1ComponentRollbackIndicator = FixedStringAttr.ValueOf(Cyyy0231Oa.ExpErrorIyy1ComponentRollbackIndicator, 1);
      WOa.ExpErrorIyy1ComponentOriginServid = DoubleAttr.ValueOf(Cyyy0231Oa.ExpErrorIyy1ComponentOriginServid);
      WOa.ExpErrorIyy1ComponentContextString = StringAttr.ValueOf(Cyyy0231Oa.ExpErrorIyy1ComponentContextString, 512);
      WOa.ExpErrorIyy1ComponentReturnCode = IntAttr.ValueOf(Cyyy0231Oa.ExpErrorIyy1ComponentReturnCode);
      WOa.ExpErrorIyy1ComponentReasonCode = IntAttr.ValueOf(Cyyy0231Oa.ExpErrorIyy1ComponentReasonCode);
      WOa.ExpErrorIyy1ComponentChecksum = FixedStringAttr.ValueOf(Cyyy0231Oa.ExpErrorIyy1ComponentChecksum, 15);
      WLa.LocExpChildCreferenceId = TimestampAttr.ValueOf(Cyyy0231Oa.ExpChildCreferenceId);
      Cyyy0231Ia.FreeInstance(  );
      Cyyy0231Ia = null;
      Cyyy0231Oa.FreeInstance(  );
      Cyyy0231Oa = null;
      
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      //    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
      //    !!!!!!!!!!!!                                                    
      //    SET <exp*> TO <loc exp*>                                        
      //                                                                    
      // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
      Globdata.GetStateData().SetLastStatementNumber( "0000000016" );
      WOa.ExpIyy1ChildCreferenceId = TimestampAttr.ValueOf(WLa.LocExpChildCreferenceId);
      return;
    }
    
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // SUBORDINATE FUNCTIONS
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // INITIALIZATION UTILITY FUNCTIONS 
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    
    public void f_22020110_localAlloc( String abname )
    {
      // Request localview allocation 
      WLa = (GEN.ORT.YYY.MYY10231_LA)(IefRuntimeParm2.GetInstance( GetType().Assembly,
      	"GEN.ORT.YYY.MYY10231_LA" ));
      if ( WLa == null )
      {
        Globdata.GetStateData().SetCurrentABId( "0022020110" );
        Globdata.GetStateData().SetCurrentABName( abname );
        Globdata.GetErrorData().SetErrorEncountered( ErrorData.ErrorEncounteredErrorFound );
        Globdata.GetErrorData().SetLastStatus( ErrorData.LastStatusIefAllocationError );
      }
    }
    
    public void f_22020110_init(  )
    {
      if ( NestingLevel < 2 )
      {
        WLa.Reset();
      }
      WOa.ExpIyy1ChildCreferenceId = "00000000000000000000";
      WOa.ExpErrorIyy1ComponentSeverityCode = " ";
      WOa.ExpErrorIyy1ComponentRollbackIndicator = " ";
      WOa.ExpErrorIyy1ComponentOriginServid = 0.0;
      WOa.ExpErrorIyy1ComponentContextString = "";
      WOa.ExpErrorIyy1ComponentReturnCode = 0;
      WOa.ExpErrorIyy1ComponentReasonCode = 0;
      WOa.ExpErrorIyy1ComponentChecksum = "               ";
    }
  }// end class
  
}

