
package gen.ort.yyy;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2023 CA Technologies. All rights reserved.
//
//    Name: EYYY0441_XML_GROUP_PARSE         Date: 2023/07/05
//    Target OS:   JVM                       Time: 15:09:58
//    Target DBMS: JDBC                      User: HakanBal
//    Access Method: JDBC           
//
//    Generation options:
//    Debug trace option selected
//    Data modeling constraint enforcement not selected
//    Optimized import view initialization not selected
//    Enforce default values with DBMS not selected
//    Init unspecified optional fields to NULL not selected
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;

import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
import com.ca.gen.odc.*;

public class EYYY0441 extends ABBase
{
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // IMPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  EYYY0441_IA w_ia;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // EXPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  EYYY0441_OA w_oa;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // REPEATING GROUP VIEW STATUS FIELDS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  boolean ExpGroup_FL_001;
  int ExpGroup_PS_001;
  boolean ExpGroup_RF_001;
  public final static int ExpGroup_MM_001 = 48;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //       +->   EYYY0441_XML_GROUP_PARSE          07/05/2023  15:09
  //       !       IMPORTS:
  //       !         Work View imp canam_xml (Transient, Optional,
  //       !                     Import only)
  //       !           xml_buffer
  //       !       EXPORTS:
  //       !         Group View (48) exp_group
  //       !           Entity View exp_g type (Transient, Export only)
  //       !             tinstance_id
  //       !             treference_id
  //       !             tcreate_user_id
  //       !             tupdate_user_id
  //       !             tkey_attr_text
  //       !             tsearch_attr_text
  //       !             tother_attr_text
  //       !             tother_attr_date
  //       !             tother_attr_time
  //       !             tother_attr_amount
  //       !         Work View exp_error canam_xml (Transient, Export only)
  //       !           xml_return_code
  //       !           xml_message
  //       !           xml_position
  //       !           xml_source
  //       !
  //       !     EXTERNAL ACTION BLOCK
  //       !
  //       +---
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public EYYY0441()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2023 CA Technologies. All rights reserved.";
    iefCGenDate = "2023/07/05";
    iefCGenTime = "15:09:58";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "HakanBal";
    iefCGenModel = "N8I_ORT_YYY_0112_TEMPLATE";
    iefCGenSubset = "ALL";
    iefCGenName = "EYYY0441_XML_GROUP_PARSE";
    nestingLevel = 0;
    valChkDeadlockTimeout = false;
    valChkDBError = false;
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // ACTION BLOCK FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void EYYY0441( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	EYYY0441_IA import_view, 
  	EYYY0441_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _EYYY0441();
  }
  
  private void _EYYY0441()
  {
    
    try {
      f_22020284();
    } catch( ABException e ) {
    }
  }
  public void f_22020284()
  	throws ABException
  {
    
    
    //    User-written code should be inserted here  
    
    
  }
}// end class


package gen.ort.yyy;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2023 CA Technologies. All rights reserved.
//
//    Name: EYYY0441_IA                      Date: 2023/07/05
//    User: HakanBal                         Time: 15:09:58
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: EYYY0441_IA
 **/
public class EYYY0441_IA extends ViewBase implements IImportView, Serializable
{
  // Entity View: IMP
  //        Type: CANAM_XML
  /**
   * Attribute missing flag for: ImpCanamXmlXmlBuffer
   **/
  public char ImpCanamXmlXmlBuffer_AS;
  /**
   * Attribute for: ImpCanamXmlXmlBuffer
   * Domain: Text
   * Length: 4094
   * Varying Length: Y
   **/
  public String ImpCanamXmlXmlBuffer;
  /**
   * Default Constructor
   **/
  
  public EYYY0441_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public EYYY0441_IA(EYYY0441_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static EYYY0441_IA getInstance()
  {
    return new EYYY0441_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new EYYY0441_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ImpCanamXmlXmlBuffer_AS = ' ';
    ImpCanamXmlXmlBuffer = "";
  }
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((EYYY0441_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(EYYY0441_IA orig)
  {
    ImpCanamXmlXmlBuffer_AS = orig.ImpCanamXmlXmlBuffer_AS;
    ImpCanamXmlXmlBuffer = orig.ImpCanamXmlXmlBuffer;
  }
}

package gen.ort.yyy;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2023 CA Technologies. All rights reserved.
//
//    Name: EYYY0441_OA                      Date: 2023/07/05
//    User: HakanBal                         Time: 15:09:58
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: EYYY0441_OA
 **/
public class EYYY0441_OA extends ViewBase implements IExportView, Serializable
{
  // Repeating GV:  EXP_GROUP
  //     Repeats: 48 times
  /**
   * Repeating group view count
   **/
  public int ExpGroup_MA;
  /**
   * Repeating group view occurrance array
   **/
  public char ExpGroup_AC[] = new char[48];
  // Entity View: EXP_G
  //        Type: TYPE
  /**
   * Attribute missing flag for: ExpGTypeTinstanceId
   **/
  public char ExpGTypeTinstanceId_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTinstanceId
   * Domain: Timestamp
   * Length: 20
   **/
  public String ExpGTypeTinstanceId[] = new String[48];
  /**
   * Attribute missing flag for: ExpGTypeTreferenceId
   **/
  public char ExpGTypeTreferenceId_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTreferenceId
   * Domain: Timestamp
   * Length: 20
   **/
  public String ExpGTypeTreferenceId[] = new String[48];
  /**
   * Attribute missing flag for: ExpGTypeTcreateUserId
   **/
  public char ExpGTypeTcreateUserId_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTcreateUserId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String ExpGTypeTcreateUserId[] = new String[48];
  /**
   * Attribute missing flag for: ExpGTypeTupdateUserId
   **/
  public char ExpGTypeTupdateUserId_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTupdateUserId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String ExpGTypeTupdateUserId[] = new String[48];
  /**
   * Attribute missing flag for: ExpGTypeTkeyAttrText
   **/
  public char ExpGTypeTkeyAttrText_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTkeyAttrText
   * Domain: Text
   * Length: 4
   * Varying Length: N
   **/
  public String ExpGTypeTkeyAttrText[] = new String[48];
  /**
   * Attribute missing flag for: ExpGTypeTsearchAttrText
   **/
  public char ExpGTypeTsearchAttrText_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTsearchAttrText
   * Domain: Text
   * Length: 20
   * Varying Length: N
   **/
  public String ExpGTypeTsearchAttrText[] = new String[48];
  /**
   * Attribute missing flag for: ExpGTypeTotherAttrText
   **/
  public char ExpGTypeTotherAttrText_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTotherAttrText
   * Domain: Text
   * Length: 2
   * Varying Length: N
   **/
  public String ExpGTypeTotherAttrText[] = new String[48];
  /**
   * Attribute missing flag for: ExpGTypeTotherAttrDate
   **/
  public char ExpGTypeTotherAttrDate_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTotherAttrDate
   * Domain: Date
   * Length: 8
   **/
  public int ExpGTypeTotherAttrDate[] = new int[48];
  /**
   * Attribute missing flag for: ExpGTypeTotherAttrTime
   **/
  public char ExpGTypeTotherAttrTime_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTotherAttrTime
   * Domain: Time
   * Length: 6
   **/
  public int ExpGTypeTotherAttrTime[] = new int[48];
  /**
   * Attribute missing flag for: ExpGTypeTotherAttrAmount
   **/
  public char ExpGTypeTotherAttrAmount_AS[] = new char[48];
  /**
   * Attribute for: ExpGTypeTotherAttrAmount
   * Domain: Number
   * Length: 17
   * Decimal Places: 2
   * Decimal Precision: Y
   **/
  public BigDecimal ExpGTypeTotherAttrAmount[] = new BigDecimal[48];
  // Entity View: EXP_ERROR
  //        Type: CANAM_XML
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlReturnCode
   **/
  public char ExpErrorCanamXmlXmlReturnCode_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlReturnCode
   * Domain: Text
   * Length: 2
   * Varying Length: N
   **/
  public String ExpErrorCanamXmlXmlReturnCode;
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlMessage
   **/
  public char ExpErrorCanamXmlXmlMessage_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlMessage
   * Domain: Text
   * Length: 80
   * Varying Length: N
   **/
  public String ExpErrorCanamXmlXmlMessage;
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlPosition
   **/
  public char ExpErrorCanamXmlXmlPosition_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlPosition
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double ExpErrorCanamXmlXmlPosition;
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlSource
   **/
  public char ExpErrorCanamXmlXmlSource_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlSource
   * Domain: Text
   * Length: 120
   * Varying Length: N
   **/
  public String ExpErrorCanamXmlXmlSource;
  /**
   * Default Constructor
   **/
  
  public EYYY0441_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public EYYY0441_OA(EYYY0441_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static EYYY0441_OA getInstance()
  {
    return new EYYY0441_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new EYYY0441_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ExpGroup_MA = 0;
    for(int a = 0; a < 48; a++)
    {
      ExpGroup_AC[a] = ' ';
      ExpGTypeTinstanceId_AS[a] = ' ';
      ExpGTypeTinstanceId[a] = "00000000000000000000";
      ExpGTypeTreferenceId_AS[a] = ' ';
      ExpGTypeTreferenceId[a] = "00000000000000000000";
      ExpGTypeTcreateUserId_AS[a] = ' ';
      ExpGTypeTcreateUserId[a] = "        ";
      ExpGTypeTupdateUserId_AS[a] = ' ';
      ExpGTypeTupdateUserId[a] = "        ";
      ExpGTypeTkeyAttrText_AS[a] = ' ';
      ExpGTypeTkeyAttrText[a] = "    ";
      ExpGTypeTsearchAttrText_AS[a] = ' ';
      ExpGTypeTsearchAttrText[a] = "                    ";
      ExpGTypeTotherAttrText_AS[a] = ' ';
      ExpGTypeTotherAttrText[a] = "  ";
      ExpGTypeTotherAttrDate_AS[a] = ' ';
      ExpGTypeTotherAttrDate[a] = 00000000;
      ExpGTypeTotherAttrTime_AS[a] = ' ';
      ExpGTypeTotherAttrTime[a] = 00000000;
      ExpGTypeTotherAttrAmount_AS[a] = ' ';
      ExpGTypeTotherAttrAmount[a] = BigDecimalAttr.getDefaultValue();
    }
    ExpErrorCanamXmlXmlReturnCode_AS = ' ';
    ExpErrorCanamXmlXmlReturnCode = "  ";
    ExpErrorCanamXmlXmlMessage_AS = ' ';
    ExpErrorCanamXmlXmlMessage = "                                                                                ";
    ExpErrorCanamXmlXmlPosition_AS = ' ';
    ExpErrorCanamXmlXmlPosition = 0.0;
    ExpErrorCanamXmlXmlSource_AS = ' ';
    ExpErrorCanamXmlXmlSource = 
      "                                                                                                                        ";
  }
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((EYYY0441_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(EYYY0441_OA orig)
  {
    ExpGroup_MA = orig.ExpGroup_MA;
    for(int a = 0; a < 48; a++)
    {
      ExpGroup_AC[a] = orig.ExpGroup_AC[a];
      ExpGTypeTinstanceId_AS[a] = orig.ExpGTypeTinstanceId_AS[a];
      ExpGTypeTinstanceId[a] = orig.ExpGTypeTinstanceId[a];
      ExpGTypeTreferenceId_AS[a] = orig.ExpGTypeTreferenceId_AS[a];
      ExpGTypeTreferenceId[a] = orig.ExpGTypeTreferenceId[a];
      ExpGTypeTcreateUserId_AS[a] = orig.ExpGTypeTcreateUserId_AS[a];
      ExpGTypeTcreateUserId[a] = orig.ExpGTypeTcreateUserId[a];
      ExpGTypeTupdateUserId_AS[a] = orig.ExpGTypeTupdateUserId_AS[a];
      ExpGTypeTupdateUserId[a] = orig.ExpGTypeTupdateUserId[a];
      ExpGTypeTkeyAttrText_AS[a] = orig.ExpGTypeTkeyAttrText_AS[a];
      ExpGTypeTkeyAttrText[a] = orig.ExpGTypeTkeyAttrText[a];
      ExpGTypeTsearchAttrText_AS[a] = orig.ExpGTypeTsearchAttrText_AS[a];
      ExpGTypeTsearchAttrText[a] = orig.ExpGTypeTsearchAttrText[a];
      ExpGTypeTotherAttrText_AS[a] = orig.ExpGTypeTotherAttrText_AS[a];
      ExpGTypeTotherAttrText[a] = orig.ExpGTypeTotherAttrText[a];
      ExpGTypeTotherAttrDate_AS[a] = orig.ExpGTypeTotherAttrDate_AS[a];
      ExpGTypeTotherAttrDate[a] = orig.ExpGTypeTotherAttrDate[a];
      ExpGTypeTotherAttrTime_AS[a] = orig.ExpGTypeTotherAttrTime_AS[a];
      ExpGTypeTotherAttrTime[a] = orig.ExpGTypeTotherAttrTime[a];
      ExpGTypeTotherAttrAmount_AS[a] = orig.ExpGTypeTotherAttrAmount_AS[a];
      ExpGTypeTotherAttrAmount[a] = orig.ExpGTypeTotherAttrAmount[a];
    }
    ExpErrorCanamXmlXmlReturnCode_AS = orig.ExpErrorCanamXmlXmlReturnCode_AS;
    ExpErrorCanamXmlXmlReturnCode = orig.ExpErrorCanamXmlXmlReturnCode;
    ExpErrorCanamXmlXmlMessage_AS = orig.ExpErrorCanamXmlXmlMessage_AS;
    ExpErrorCanamXmlXmlMessage = orig.ExpErrorCanamXmlXmlMessage;
    ExpErrorCanamXmlXmlPosition_AS = orig.ExpErrorCanamXmlXmlPosition_AS;
    ExpErrorCanamXmlXmlPosition = orig.ExpErrorCanamXmlXmlPosition;
    ExpErrorCanamXmlXmlSource_AS = orig.ExpErrorCanamXmlXmlSource_AS;
    ExpErrorCanamXmlXmlSource = orig.ExpErrorCanamXmlXmlSource;
  }
}
