
package gen.ort.yyy;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2023 CA Technologies. All rights reserved.
//
//    Name: MYY10421_XML_PARSE               Date: 2023/07/05
//    Target OS:   JVM                       Time: 15:10:04
//    Target DBMS: JDBC                      User: HakanBal
//    Access Method: JDBC           
//
//    Generation options:
//    Debug trace option selected
//    Data modeling constraint enforcement not selected
//    Optimized import view initialization not selected
//    Enforce default values with DBMS not selected
//    Init unspecified optional fields to NULL not selected
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;

import com.ca.gen.abrt.*;
import com.ca.gen.abrt.functions.*;
import com.ca.gen.abrt.cascade.*;
import com.ca.gen.abrt.trace.*;
import com.ca.gen.exits.common.*;
import com.ca.gen.odc.*;

public class MYY10421 extends ABBase
{
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // IMPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  MYY10421_IA w_ia;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // EXPORT VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  MYY10421_OA w_oa;
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // LOCAL VIEW CLASS VARIABLE
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  MYY10421_LA w_la;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // ACTION BLOCK IMPORT/EXPORT VIEWS CLASS VARIABLES
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  gen.ort.yyy.CYYY0421_IA cyyy0421_ia;
  gen.ort.yyy.CYYY0421_OA cyyy0421_oa;
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // MISC DECLARATIONS AND PROTOTYPES 
  //    FOLLOW AS NEEDED:             
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  boolean func_0022020166_esc_flag;
  PadView padview[] = new PadView [46];
  int trace_ret_code;
  PadText padtext[] = initPadText();
  public PadText [] initPadText()
  {
    PadText [] result = new PadText [PADTEXT_SIZE];
    result[0] = PadText.getInstance(   0,"+->   MYY10421_XML_PARSE                07/05/2023  15:10");
    result[1] = PadText.getInstance(   0,"!       IMPORTS:");
    result[2] = PadText.getInstance(   0,"!         Work View imp canam_xml (Transient, Optional, Import only)");
    result[3] = PadText.getInstance(   0,"!           xml_buffer");
    result[4] = PadText.getInstance(   0,"!       EXPORTS:");
    result[5] = PadText.getInstance(   0,"!         Entity View exp iyy1_type (Transient, Export only)");
    result[6] = PadText.getInstance(   0,"!           tinstance_id");
    result[7] = PadText.getInstance(   0,"!           treference_id");
    result[8] = PadText.getInstance(   0,"!           tcreate_user_id");
    result[9] = PadText.getInstance(   0,"!           tupdate_user_id");
    result[10] = PadText.getInstance(   0,"!           tkey_attr_text");
    result[11] = PadText.getInstance(   0,"!           tsearch_attr_text");
    result[12] = PadText.getInstance(   0,"!           tother_attr_text");
    result[13] = PadText.getInstance(   0,"!           tother_attr_date");
    result[14] = PadText.getInstance(   0,"!           tother_attr_time");
    result[15] = PadText.getInstance(   0,"!           tother_attr_amount");
    result[16] = PadText.getInstance(   0,"!         Work View exp_error canam_xml (Transient, Export only)");
    result[17] = PadText.getInstance(   0,"!           xml_return_code");
    result[18] = PadText.getInstance(   0,"!           xml_message");
    result[19] = PadText.getInstance(   0,"!           xml_position");
    result[20] = PadText.getInstance(   0,"!           xml_source");
    result[21] = PadText.getInstance(   0,"!         Work View exp_error iyy1_component (Transient, Export only)");
    result[22] = PadText.getInstance(   0,"!           severity_code");
    result[23] = PadText.getInstance(   0,"!           rollback_indicator");
    result[24] = PadText.getInstance(   0,"!           origin_servid");
    result[25] = PadText.getInstance(   0,"!           context_string");
    result[26] = PadText.getInstance(   0,"!           return_code");
    result[27] = PadText.getInstance(   0,"!           reason_code");
    result[28] = PadText.getInstance(   0,"!           checksum");
    result[29] = PadText.getInstance(   0,"!       LOCALS:");
    result[30] = PadText.getInstance(   0,"!         Entity View loc_exp type");
    result[31] = PadText.getInstance(   0,"!           tinstance_id");
    result[32] = PadText.getInstance(   0,"!           treference_id");
    result[33] = PadText.getInstance(   0,"!           tcreate_user_id");
    result[34] = PadText.getInstance(   0,"!           tupdate_user_id");
    result[35] = PadText.getInstance(   0,"!           tkey_attr_text");
    result[36] = PadText.getInstance(   0,"!           tsearch_attr_text");
    result[37] = PadText.getInstance(   0,"!           tother_attr_text");
    result[38] = PadText.getInstance(   0,"!           tother_attr_date");
    result[39] = PadText.getInstance(   0,"!           tother_attr_time");
    result[40] = PadText.getInstance(   0,"!           tother_attr_amount");
    result[41] = PadText.getInstance(   0,"!");
    result[42] = PadText.getInstance(   0,"!     PROCEDURE STATEMENTS");
    result[43] = PadText.getInstance(   0,"!");
    result[44] = PadText.getInstance(   1,"!  NOTE: ");
    result[45] = PadText.getInstance(   1,"!  Check description for porpose");
    result[46] = PadText.getInstance(   1,"!  ");
    result[47] = PadText.getInstance(   2,"!  NOTE: ");
    result[48] = PadText.getInstance(   2,"!  RELEASE HISTORY");
    result[49] = PadText.getInstance(   2,"!  01_00 01-10-2009 New Release");
    result[50] = PadText.getInstance(   2,"!  ");
    result[51] = PadText.getInstance(   3,"!  NOTE: ");
    result[52] = PadText.getInstance(   3,"!  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
    result[53] = PadText.getInstance(   3,"!  SET <loc imp*> TO <imp*>");
    result[54] = PadText.getInstance(   3,"!  ");
    result[55] = PadText.getInstance(   4,"!  USE cyyy0421_xml_parse");
    result[56] = PadText.getInstance(   4,"!     WHICH IMPORTS: Work View imp canam_xml TO Work View imp canam_xml");
    result[57] = PadText.getInstance(   4,"!     WHICH EXPORTS: Work View exp_error canam_xml FROM Work View exp_error canam_xml");
    result[58] = PadText.getInstance(   4,
      "!                    Work View exp_error iyy1_component FROM Work View exp_error iyy1_component");
    result[59] = PadText.getInstance(   4,"!                    Entity View loc_exp type FROM Entity View exp type");
    result[60] = PadText.getInstance(   5,"!   ");
    result[61] = PadText.getInstance(   6,"!  NOTE: ");
    result[62] = PadText.getInstance(   6,"!  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!");
    result[63] = PadText.getInstance(   6,"!  SET <exp*> TO <loc exp*>");
    result[64] = PadText.getInstance(   6,"!  ");
    result[65] = PadText.getInstance(   7,"!  SET exp iyy1_type tinstance_id TO loc_exp type tinstance_id ");
    result[66] = PadText.getInstance(   8,"!  SET exp iyy1_type treference_id TO loc_exp type treference_id ");
    result[67] = PadText.getInstance(   9,"!  SET exp iyy1_type tcreate_user_id TO loc_exp type tcreate_user_id ");
    result[68] = PadText.getInstance(  10,"!  SET exp iyy1_type tupdate_user_id TO loc_exp type tupdate_user_id ");
    result[69] = PadText.getInstance(  11,"!  SET exp iyy1_type tkey_attr_text TO loc_exp type tkey_attr_text ");
    result[70] = PadText.getInstance(  12,"!  SET exp iyy1_type tsearch_attr_text TO loc_exp type tsearch_attr_text ");
    result[71] = PadText.getInstance(  13,"!  SET exp iyy1_type tother_attr_text TO loc_exp type tother_attr_text ");
    result[72] = PadText.getInstance(  14,"!  SET exp iyy1_type tother_attr_date TO loc_exp type tother_attr_date ");
    result[73] = PadText.getInstance(  15,"!  SET exp iyy1_type tother_attr_time TO loc_exp type tother_attr_time ");
    result[74] = PadText.getInstance(  16,"!  SET exp iyy1_type tother_attr_amount TO loc_exp type tother_attr_amount ");
    result[75] = PadText.getInstance(  17,"!   ");
    result[76] = PadText.getInstance(   0,"+---");
    result[77] = PadText.getInstance(PadText.LASTLINE,"************************* BOTTOM OF DATA *************************");
    return result;
  }
  final static int PADTEXT_SIZE = 78;
  //       +->   MYY10421_XML_PARSE                07/05/2023  15:10
  //       !       IMPORTS:
  //       !         Work View imp canam_xml (Transient, Optional, Import only)
  //       !           xml_buffer
  //       !       EXPORTS:
  //       !         Entity View exp iyy1_type (Transient, Export only)
  //       !           tinstance_id
  //       !           treference_id
  //       !           tcreate_user_id
  //       !           tupdate_user_id
  //       !           tkey_attr_text
  //       !           tsearch_attr_text
  //       !           tother_attr_text
  //       !           tother_attr_date
  //       !           tother_attr_time
  //       !           tother_attr_amount
  //       !         Work View exp_error canam_xml (Transient, Export only)
  //       !           xml_return_code
  //       !           xml_message
  //       !           xml_position
  //       !           xml_source
  //       !         Work View exp_error iyy1_component (Transient, Export only)
  //       !           severity_code
  //       !           rollback_indicator
  //       !           origin_servid
  //       !           context_string
  //       !           return_code
  //       !           reason_code
  //       !           checksum
  //       !       LOCALS:
  //       !         Entity View loc_exp type
  //       !           tinstance_id
  //       !           treference_id
  //       !           tcreate_user_id
  //       !           tupdate_user_id
  //       !           tkey_attr_text
  //       !           tsearch_attr_text
  //       !           tother_attr_text
  //       !           tother_attr_date
  //       !           tother_attr_time
  //       !           tother_attr_amount
  //       !
  //       !     PROCEDURE STATEMENTS
  //       !
  //     1 !  NOTE: 
  //     1 !  Check description for porpose
  //     1 !  
  //     2 !  NOTE: 
  //     2 !  RELEASE HISTORY
  //     2 !  01_00 01-10-2009 New Release
  //     2 !  
  //     3 !  NOTE: 
  //     3 !  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  //     3 !  SET <loc imp*> TO <imp*>
  //     3 !  
  //     4 !  USE cyyy0421_xml_parse
  //     4 !     WHICH IMPORTS: Work View imp canam_xml TO Work View imp canam_xml
  //     4 !     WHICH EXPORTS: Work View exp_error canam_xml FROM Work View exp_error canam_xml
  //     4 !                    Work View exp_error iyy1_component FROM Work View exp_error iyy1_component
  //     4 !                    Entity View loc_exp type FROM Entity View exp type
  //     5 !   
  //     6 !  NOTE: 
  //     6 !  !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  //     6 !  SET <exp*> TO <loc exp*>
  //     6 !  
  //     7 !  SET exp iyy1_type tinstance_id TO loc_exp type tinstance_id 
  //     8 !  SET exp iyy1_type treference_id TO loc_exp type treference_id 
  //     9 !  SET exp iyy1_type tcreate_user_id TO loc_exp type tcreate_user_id 
  //    10 !  SET exp iyy1_type tupdate_user_id TO loc_exp type tupdate_user_id 
  //    11 !  SET exp iyy1_type tkey_attr_text TO loc_exp type tkey_attr_text 
  //    12 !  SET exp iyy1_type tsearch_attr_text TO loc_exp type tsearch_attr_text 
  //    13 !  SET exp iyy1_type tother_attr_text TO loc_exp type tother_attr_text 
  //    14 !  SET exp iyy1_type tother_attr_date TO loc_exp type tother_attr_date 
  //    15 !  SET exp iyy1_type tother_attr_time TO loc_exp type tother_attr_time 
  //    16 !  SET exp iyy1_type tother_attr_amount TO loc_exp type tother_attr_amount 
  //    17 !   
  //       +---
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  //  CONSTRUCTOR FOR THE CLASS       
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  public MYY10421()
  {
    iefCGenRlse = "CA Gen 8.6";
    ssCopyright = "Copyright (c) 2023 CA Technologies. All rights reserved.";
    iefCGenDate = "2023/07/05";
    iefCGenTime = "15:10:04";
    iefCGenEncy = "9.2.A6";
    iefCGenUserId = "HakanBal";
    iefCGenModel = "N8I_ORT_YYY_0112_TEMPLATE";
    iefCGenSubset = "ALL";
    iefCGenName = "MYY10421_XML_PARSE";
    nestingLevel = 0;
    valChkDeadlockTimeout = false;
    valChkDBError = false;
  }
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // ACTION BLOCK FUNCTION DECLARATIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void MYY10421( Object in_runtime_parm1, 
  	IRuntimePStepContext in_runtime_parm2, 
  	GlobData in_globdata, 
  	MYY10421_IA import_view, 
  	MYY10421_OA export_view )
  {
    iefRuntimeParm1 = in_runtime_parm1;
    iefRuntimeParm2 = in_runtime_parm2;
    globdata = in_globdata;
    w_ia = import_view;
    w_oa = export_view;
    _MYY10421();
  }
  
  private void _MYY10421()
  {
    
    f_22020166_localAlloc("MYY10421_XML_PARSE");
    if ( globdata.getErrorData().getLastStatus() == ErrorData.IEF_ALLOCATION_ERROR_FL_LS )
    	return;
    
    ++(nestingLevel);
    try {
      f_22020166_init();
      f_22020166();
    } catch( ABException e ) {
    } finally {
      --(nestingLevel);
    }
    String last_stmt_num_saved = globdata.getStateData().getLastStatementNumber();
    globdata.getStateData().setLastStatementNumber( "9999999999" );
    try {
      f_0_trace();
    } catch( ABException e ) {
    }
    globdata.getStateData().setLastStatementNumber( last_stmt_num_saved );
  }
  public void f_22020166()
  	throws ABException
  {
    func_0022020166_esc_flag = false;
    globdata.getStateData().setCurrentABId( "0022020166" );
    globdata.getStateData().setCurrentABName( "MYY10421_XML_PARSE" );
    padview_init();
    globdata.getStateData().setLastStatementNumber( "0000000000" );
    f_0_trace();
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    //    Check description for porpose                                   
    //                                                                    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    //    RELEASE HISTORY                                                 
    //    01_00 01-10-2009 New Release                                    
    //                                                                    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    //    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
    //    !!!!!!!!!!!!                                                    
    //    SET <loc imp*> TO <imp*>                                        
    //                                                                    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    globdata.getStateData().setLastStatementNumber( "0000000004" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      
      cyyy0421_ia = (gen.ort.yyy.CYYY0421_IA)(iefRuntimeParm2.getInstance("gen.ort.yyy.CYYY0421_IA"));
      cyyy0421_oa = (gen.ort.yyy.CYYY0421_OA)(iefRuntimeParm2.getInstance("gen.ort.yyy.CYYY0421_OA"));
      cyyy0421_ia.ImpCanamXmlXmlBuffer = StringAttr.valueOf(w_ia.ImpCanamXmlXmlBuffer, (short)4094);
      globdata.getErrorData().setErrorEncounteredSW( ErrorData.NO_ERROR_FOUND_SW );
      iefRuntimeParm2.useActionBlock("gen.ort.yyy.CYYY0421", "CYYY0421", cyyy0421_ia, cyyy0421_oa);
      if ( ((!(globdata.getErrorData().getStatus().equals( ErrorData.NONE_SF ))) || (globdata.getErrorData().getErrorEncounteredSW() 
        != ErrorData.NO_ERROR_FOUND_SW)) || (globdata.getErrorData().getViewOverflowSW() != ErrorData.NO_ERROR_FOUND_SW) )
      {
        throw new ABException();
      }
      globdata.getStateData().setCurrentABId( "0022020166" );
      globdata.getStateData().setCurrentABName( "MYY10421_XML_PARSE" );
      globdata.getStateData().setLastStatementNumber( "0000000004" );
      w_la.LocExpTypeTinstanceId = TimestampAttr.valueOf(cyyy0421_oa.ExpTypeTinstanceId);
      w_la.LocExpTypeTreferenceId = TimestampAttr.valueOf(cyyy0421_oa.ExpTypeTreferenceId);
      w_la.LocExpTypeTcreateUserId = FixedStringAttr.valueOf(cyyy0421_oa.ExpTypeTcreateUserId, (short)8);
      w_la.LocExpTypeTupdateUserId = FixedStringAttr.valueOf(cyyy0421_oa.ExpTypeTupdateUserId, (short)8);
      w_la.LocExpTypeTkeyAttrText = FixedStringAttr.valueOf(cyyy0421_oa.ExpTypeTkeyAttrText, (short)4);
      w_la.LocExpTypeTsearchAttrText = FixedStringAttr.valueOf(cyyy0421_oa.ExpTypeTsearchAttrText, (short)20);
      w_la.LocExpTypeTotherAttrText = FixedStringAttr.valueOf(cyyy0421_oa.ExpTypeTotherAttrText, (short)2);
      w_la.LocExpTypeTotherAttrDate = DateAttr.valueOf(cyyy0421_oa.ExpTypeTotherAttrDate);
      w_la.LocExpTypeTotherAttrTime = TimeAttr.valueOf(cyyy0421_oa.ExpTypeTotherAttrTime);
      w_la.LocExpTypeTotherAttrAmount = BigDecimalAttr.valueOf(cyyy0421_oa.ExpTypeTotherAttrAmount);
      w_oa.ExpErrorIyy1ComponentSeverityCode = FixedStringAttr.valueOf(cyyy0421_oa.ExpErrorIyy1ComponentSeverityCode, (short)1);
      w_oa.ExpErrorIyy1ComponentRollbackIndicator = FixedStringAttr.valueOf(cyyy0421_oa.ExpErrorIyy1ComponentRollbackIndicator, (
        short)1);
      w_oa.ExpErrorIyy1ComponentOriginServid = DoubleAttr.valueOf(cyyy0421_oa.ExpErrorIyy1ComponentOriginServid);
      w_oa.ExpErrorIyy1ComponentContextString = StringAttr.valueOf(cyyy0421_oa.ExpErrorIyy1ComponentContextString, (short)512);
      w_oa.ExpErrorIyy1ComponentReturnCode = IntAttr.valueOf(cyyy0421_oa.ExpErrorIyy1ComponentReturnCode);
      w_oa.ExpErrorIyy1ComponentReasonCode = IntAttr.valueOf(cyyy0421_oa.ExpErrorIyy1ComponentReasonCode);
      w_oa.ExpErrorIyy1ComponentChecksum = FixedStringAttr.valueOf(cyyy0421_oa.ExpErrorIyy1ComponentChecksum, (short)15);
      w_oa.ExpErrorCanamXmlXmlReturnCode = FixedStringAttr.valueOf(cyyy0421_oa.ExpErrorCanamXmlXmlReturnCode, (short)2);
      w_oa.ExpErrorCanamXmlXmlMessage = FixedStringAttr.valueOf(cyyy0421_oa.ExpErrorCanamXmlXmlMessage, (short)80);
      w_oa.ExpErrorCanamXmlXmlPosition = DoubleAttr.valueOf(cyyy0421_oa.ExpErrorCanamXmlXmlPosition);
      w_oa.ExpErrorCanamXmlXmlSource = FixedStringAttr.valueOf(cyyy0421_oa.ExpErrorCanamXmlXmlSource, (short)120);
      cyyy0421_ia.freeInstance();
      cyyy0421_ia = null;
      cyyy0421_oa.freeInstance();
      cyyy0421_oa = null;
    }
    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    //    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!  
    //    !!!!!!!!!!!!                                                    
    //    SET <exp*> TO <loc exp*>                                        
    //                                                                    
    // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
    globdata.getStateData().setLastStatementNumber( "0000000007" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTinstanceId = TimestampAttr.valueOf(w_la.LocExpTypeTinstanceId);
    }
    globdata.getStateData().setLastStatementNumber( "0000000008" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTreferenceId = TimestampAttr.valueOf(w_la.LocExpTypeTreferenceId);
    }
    globdata.getStateData().setLastStatementNumber( "0000000009" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTcreateUserId = FixedStringAttr.valueOf(w_la.LocExpTypeTcreateUserId, (short)8);
    }
    globdata.getStateData().setLastStatementNumber( "0000000010" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTupdateUserId = FixedStringAttr.valueOf(w_la.LocExpTypeTupdateUserId, (short)8);
    }
    globdata.getStateData().setLastStatementNumber( "0000000011" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTkeyAttrText = FixedStringAttr.valueOf(w_la.LocExpTypeTkeyAttrText, (short)4);
    }
    globdata.getStateData().setLastStatementNumber( "0000000012" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTsearchAttrText = FixedStringAttr.valueOf(w_la.LocExpTypeTsearchAttrText, (short)20);
    }
    globdata.getStateData().setLastStatementNumber( "0000000013" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTotherAttrText = FixedStringAttr.valueOf(w_la.LocExpTypeTotherAttrText, (short)2);
    }
    globdata.getStateData().setLastStatementNumber( "0000000014" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTotherAttrDate = DateAttr.valueOf(w_la.LocExpTypeTotherAttrDate);
    }
    globdata.getStateData().setLastStatementNumber( "0000000015" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTotherAttrTime = TimeAttr.valueOf(w_la.LocExpTypeTotherAttrTime);
    }
    globdata.getStateData().setLastStatementNumber( "0000000016" );
    f_0_trace();
    if ( trace_ret_code != 8 )
    {
      w_oa.ExpIyy1TypeTotherAttrAmount = BigDecimalAttr.valueOf(TIRBDTRU.truncateToBigDecimal( w_la.LocExpTypeTotherAttrAmount, 2));
    }
    
  }
  
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // SUBORDINATE FUNCTIONS
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  // INITIALIZATION UTILITY FUNCTIONS 
  // * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
  
  public void f_22020166_localAlloc(String abname)
  {
    // Request localview allocation 
    w_la = (gen.ort.yyy.MYY10421_LA)(iefRuntimeParm2.getInstance("gen.ort.yyy.MYY10421_LA"));
    if ( w_la == null )
    {
      globdata.getStateData().setCurrentABId( "0022020166" );
      globdata.getStateData().setCurrentABName( abname );
      globdata.getErrorData().setErrorEncounteredSW( ErrorData.ERROR_FOUND_SW );
      globdata.getErrorData().setLastStatus( ErrorData.IEF_ALLOCATION_ERROR_FL_LS );
    }
  }
  
  public void f_22020166_init()
  	throws ABException
  {
    if ( nestingLevel < 2 )
    {
      w_la.reset();
    }
    w_oa.ExpIyy1TypeTinstanceId = "00000000000000000000";
    w_oa.ExpIyy1TypeTreferenceId = "00000000000000000000";
    w_oa.ExpIyy1TypeTcreateUserId = "        ";
    w_oa.ExpIyy1TypeTupdateUserId = "        ";
    w_oa.ExpIyy1TypeTkeyAttrText = "    ";
    w_oa.ExpIyy1TypeTsearchAttrText = "                    ";
    w_oa.ExpIyy1TypeTotherAttrText = "  ";
    w_oa.ExpIyy1TypeTotherAttrDate = 00000000;
    w_oa.ExpIyy1TypeTotherAttrTime = 00000000;
    w_oa.ExpIyy1TypeTotherAttrAmount = BigDecimalAttr.getDefaultValue();
    w_oa.ExpErrorCanamXmlXmlReturnCode = "  ";
    w_oa.ExpErrorCanamXmlXmlMessage = "                                                                                ";
    w_oa.ExpErrorCanamXmlXmlPosition = 0.0;
    w_oa.ExpErrorCanamXmlXmlSource = 
      "                                                                                                                        ";
    w_oa.ExpErrorIyy1ComponentSeverityCode = " ";
    w_oa.ExpErrorIyy1ComponentRollbackIndicator = " ";
    w_oa.ExpErrorIyy1ComponentOriginServid = 0.0;
    w_oa.ExpErrorIyy1ComponentContextString = "";
    w_oa.ExpErrorIyy1ComponentReturnCode = 0;
    w_oa.ExpErrorIyy1ComponentReasonCode = 0;
    w_oa.ExpErrorIyy1ComponentChecksum = "               ";
  }
  
  public void f_0_trace()
  	throws ABException
  {
    trace_ret_code = TIRTRCE.TIRTRCE(iefRuntimeParm1, iefRuntimeParm2, globdata, padtext, padview);
    if ( trace_ret_code == 20 )
    {
      throw new ABException();
    }
  }
  
  public void padview_init()
  {
padview[0] = PadView.getInstance("IMPORT                          ", 0, 0, 0, (short)1, PadView.VT_BASE, PadView.DT_NONE, w_ia, 
      "w_ia");
    padview[1] = PadView.getInstance("IMP                             ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_ia, 
      null);
    padview[2] = PadView.getInstance("CANAM_XML                       ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, w_ia,
       null);
    padview[3] = PadView.getInstance("XML_BUFFER                      ", 4094, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_VARCHAR, w_ia, "ImpCanamXmlXmlBuffer");
padview[4] = PadView.getInstance("EXPORT                          ", 0, 0, 0, (short)1, PadView.VT_BASE, PadView.DT_NONE, w_oa, 
      "w_oa");
    padview[5] = PadView.getInstance("EXP                             ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_oa, 
      null);
    padview[6] = PadView.getInstance("IYY1_TYPE                       ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, w_oa,
       null);
    padview[7] = PadView.getInstance("TINSTANCE_ID                    ", 20, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_TIMESTAMP, w_oa, "ExpIyy1TypeTinstanceId");
    padview[8] = PadView.getInstance("TREFERENCE_ID                   ", 20, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_TIMESTAMP, w_oa, "ExpIyy1TypeTreferenceId");
    padview[9] = PadView.getInstance("TCREATE_USER_ID                 ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpIyy1TypeTcreateUserId");
    padview[10] = PadView.getInstance("TUPDATE_USER_ID                 ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpIyy1TypeTupdateUserId");
    padview[11] = PadView.getInstance("TKEY_ATTR_TEXT                  ", 4, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpIyy1TypeTkeyAttrText");
    padview[12] = PadView.getInstance("TSEARCH_ATTR_TEXT               ", 20, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpIyy1TypeTsearchAttrText");
    padview[13] = PadView.getInstance("TOTHER_ATTR_TEXT                ", 2, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpIyy1TypeTotherAttrText");
    padview[14] = PadView.getInstance("TOTHER_ATTR_DATE                ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_DATE, 
      w_oa, "ExpIyy1TypeTotherAttrDate");
    padview[15] = PadView.getInstance("TOTHER_ATTR_TIME                ", 6, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TIME, 
      w_oa, "ExpIyy1TypeTotherAttrTime");
    padview[16] = PadView.getInstance("TOTHER_ATTR_AMOUNT              ", 17, 2, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_FIXED,
       w_oa, "ExpIyy1TypeTotherAttrAmount");
    padview[17] = PadView.getInstance("EXP_ERROR                       ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_oa, 
      null);
    padview[18] = PadView.getInstance("CANAM_XML                       ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, 
      w_oa, null);
    padview[19] = PadView.getInstance("XML_RETURN_CODE                 ", 2, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpErrorCanamXmlXmlReturnCode");
    padview[20] = PadView.getInstance("XML_MESSAGE                     ", 80, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpErrorCanamXmlXmlMessage");
    padview[21] = PadView.getInstance("XML_POSITION                    ", 15, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_NUMERIC, w_oa, "ExpErrorCanamXmlXmlPosition");
    padview[22] = PadView.getInstance("XML_SOURCE                      ", 120, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT,
       w_oa, "ExpErrorCanamXmlXmlSource");
    padview[23] = PadView.getInstance("EXP_ERROR                       ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_oa, 
      null);
    padview[24] = PadView.getInstance("IYY1_COMPONENT                  ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, 
      w_oa, null);
    padview[25] = PadView.getInstance("SEVERITY_CODE                   ", 1, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpErrorIyy1ComponentSeverityCode");
    padview[26] = PadView.getInstance("ROLLBACK_INDICATOR              ", 1, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpErrorIyy1ComponentRollbackIndicator");
    padview[27] = PadView.getInstance("ORIGIN_SERVID                   ", 15, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_NUMERIC, w_oa, "ExpErrorIyy1ComponentOriginServid");
    padview[28] = PadView.getInstance("CONTEXT_STRING                  ", 512, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_VARCHAR, w_oa, "ExpErrorIyy1ComponentContextString");
    padview[29] = PadView.getInstance("RETURN_CODE                     ", 5, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_NUMERIC, w_oa, "ExpErrorIyy1ComponentReturnCode");
    padview[30] = PadView.getInstance("REASON_CODE                     ", 5, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_NUMERIC, w_oa, "ExpErrorIyy1ComponentReasonCode");
    padview[31] = PadView.getInstance("CHECKSUM                        ", 15, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_oa, "ExpErrorIyy1ComponentChecksum");
    padview[32] = PadView.getInstance("LOCAL                           ", 0, 0, 0, (short)1, PadView.VT_BASE, PadView.DT_NONE, w_la, 
      "w_la");
    padview[33] = PadView.getInstance("LOC_EXP                         ", 0, 0, 0, (short)2, PadView.VT_VIEW, PadView.DT_NONE, w_la, 
      null);
    padview[34] = PadView.getInstance("TYPE                            ", 0, 0, 0, (short)3, PadView.VT_ENTITY, PadView.DT_NONE, 
      w_la, null);
    padview[35] = PadView.getInstance("TINSTANCE_ID                    ", 20, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_TIMESTAMP, w_la, "LocExpTypeTinstanceId");
    padview[36] = PadView.getInstance("TREFERENCE_ID                   ", 20, 0, 0, (short)3, PadView.VT_PREDICATE, 
      PadView.DT_TIMESTAMP, w_la, "LocExpTypeTreferenceId");
    padview[37] = PadView.getInstance("TCREATE_USER_ID                 ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_la, "LocExpTypeTcreateUserId");
    padview[38] = PadView.getInstance("TUPDATE_USER_ID                 ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_la, "LocExpTypeTupdateUserId");
    padview[39] = PadView.getInstance("TKEY_ATTR_TEXT                  ", 4, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_la, "LocExpTypeTkeyAttrText");
    padview[40] = PadView.getInstance("TSEARCH_ATTR_TEXT               ", 20, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_la, "LocExpTypeTsearchAttrText");
    padview[41] = PadView.getInstance("TOTHER_ATTR_TEXT                ", 2, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TEXT, 
      w_la, "LocExpTypeTotherAttrText");
    padview[42] = PadView.getInstance("TOTHER_ATTR_DATE                ", 8, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_DATE, 
      w_la, "LocExpTypeTotherAttrDate");
    padview[43] = PadView.getInstance("TOTHER_ATTR_TIME                ", 6, 0, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_TIME, 
      w_la, "LocExpTypeTotherAttrTime");
    padview[44] = PadView.getInstance("TOTHER_ATTR_AMOUNT              ", 17, 2, 0, (short)3, PadView.VT_PREDICATE, PadView.DT_FIXED,
       w_la, "LocExpTypeTotherAttrAmount");
    padview[45] = PadView.getInstance("******** BOTTOM OF DATA ********", 0, 0, 0, (short)0, PadView.VT_END, PadView.DT_NONE, w_la, 
      null);
  }
}// end class


package gen.ort.yyy;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2023 CA Technologies. All rights reserved.
//
//    Name: MYY10421_IA                      Date: 2023/07/05
//    User: HakanBal                         Time: 15:10:04
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: MYY10421_IA
 **/
public class MYY10421_IA extends ViewBase implements IImportView, Serializable
{
  // Entity View: IMP
  //        Type: CANAM_XML
  /**
   * Attribute missing flag for: ImpCanamXmlXmlBuffer
   **/
  public char ImpCanamXmlXmlBuffer_AS;
  /**
   * Attribute for: ImpCanamXmlXmlBuffer
   * Domain: Text
   * Length: 4094
   * Varying Length: Y
   **/
  public String ImpCanamXmlXmlBuffer;
  /**
   * Default Constructor
   **/
  
  public MYY10421_IA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public MYY10421_IA(MYY10421_IA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static MYY10421_IA getInstance()
  {
    return new MYY10421_IA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new MYY10421_IA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ImpCanamXmlXmlBuffer_AS = ' ';
    ImpCanamXmlXmlBuffer = "";
  }
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IImportView orig)
  {
    this.copyFrom((MYY10421_IA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(MYY10421_IA orig)
  {
    ImpCanamXmlXmlBuffer_AS = orig.ImpCanamXmlXmlBuffer_AS;
    ImpCanamXmlXmlBuffer = orig.ImpCanamXmlXmlBuffer;
  }
}

package gen.ort.yyy;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2023 CA Technologies. All rights reserved.
//
//    Name: MYY10421_LA                      Date: 2023/07/05
//    User: HakanBal                         Time: 15:10:04
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF LOCAL VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: MYY10421_LA
 **/
public class MYY10421_LA extends ViewBase implements ILocalView, Serializable
{
  // Entity View: LOC_EXP
  //        Type: TYPE
  /**
   * Attribute missing flag for: LocExpTypeTinstanceId
   **/
  public char LocExpTypeTinstanceId_AS;
  /**
   * Attribute for: LocExpTypeTinstanceId
   * Domain: Timestamp
   * Length: 20
   **/
  public String LocExpTypeTinstanceId;
  /**
   * Attribute missing flag for: LocExpTypeTreferenceId
   **/
  public char LocExpTypeTreferenceId_AS;
  /**
   * Attribute for: LocExpTypeTreferenceId
   * Domain: Timestamp
   * Length: 20
   **/
  public String LocExpTypeTreferenceId;
  /**
   * Attribute missing flag for: LocExpTypeTcreateUserId
   **/
  public char LocExpTypeTcreateUserId_AS;
  /**
   * Attribute for: LocExpTypeTcreateUserId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String LocExpTypeTcreateUserId;
  /**
   * Attribute missing flag for: LocExpTypeTupdateUserId
   **/
  public char LocExpTypeTupdateUserId_AS;
  /**
   * Attribute for: LocExpTypeTupdateUserId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String LocExpTypeTupdateUserId;
  /**
   * Attribute missing flag for: LocExpTypeTkeyAttrText
   **/
  public char LocExpTypeTkeyAttrText_AS;
  /**
   * Attribute for: LocExpTypeTkeyAttrText
   * Domain: Text
   * Length: 4
   * Varying Length: N
   **/
  public String LocExpTypeTkeyAttrText;
  /**
   * Attribute missing flag for: LocExpTypeTsearchAttrText
   **/
  public char LocExpTypeTsearchAttrText_AS;
  /**
   * Attribute for: LocExpTypeTsearchAttrText
   * Domain: Text
   * Length: 20
   * Varying Length: N
   **/
  public String LocExpTypeTsearchAttrText;
  /**
   * Attribute missing flag for: LocExpTypeTotherAttrText
   **/
  public char LocExpTypeTotherAttrText_AS;
  /**
   * Attribute for: LocExpTypeTotherAttrText
   * Domain: Text
   * Length: 2
   * Varying Length: N
   **/
  public String LocExpTypeTotherAttrText;
  /**
   * Attribute missing flag for: LocExpTypeTotherAttrDate
   **/
  public char LocExpTypeTotherAttrDate_AS;
  /**
   * Attribute for: LocExpTypeTotherAttrDate
   * Domain: Date
   * Length: 8
   **/
  public int LocExpTypeTotherAttrDate;
  /**
   * Attribute missing flag for: LocExpTypeTotherAttrTime
   **/
  public char LocExpTypeTotherAttrTime_AS;
  /**
   * Attribute for: LocExpTypeTotherAttrTime
   * Domain: Time
   * Length: 6
   **/
  public int LocExpTypeTotherAttrTime;
  /**
   * Attribute missing flag for: LocExpTypeTotherAttrAmount
   **/
  public char LocExpTypeTotherAttrAmount_AS;
  /**
   * Attribute for: LocExpTypeTotherAttrAmount
   * Domain: Number
   * Length: 17
   * Decimal Places: 2
   * Decimal Precision: Y
   **/
  public BigDecimal LocExpTypeTotherAttrAmount;
  /**
   * Default Constructor
   **/
  
  public MYY10421_LA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public MYY10421_LA(MYY10421_LA orig)
  {
    LocExpTypeTinstanceId_AS = orig.LocExpTypeTinstanceId_AS;
    LocExpTypeTinstanceId = orig.LocExpTypeTinstanceId;
    LocExpTypeTreferenceId_AS = orig.LocExpTypeTreferenceId_AS;
    LocExpTypeTreferenceId = orig.LocExpTypeTreferenceId;
    LocExpTypeTcreateUserId_AS = orig.LocExpTypeTcreateUserId_AS;
    LocExpTypeTcreateUserId = orig.LocExpTypeTcreateUserId;
    LocExpTypeTupdateUserId_AS = orig.LocExpTypeTupdateUserId_AS;
    LocExpTypeTupdateUserId = orig.LocExpTypeTupdateUserId;
    LocExpTypeTkeyAttrText_AS = orig.LocExpTypeTkeyAttrText_AS;
    LocExpTypeTkeyAttrText = orig.LocExpTypeTkeyAttrText;
    LocExpTypeTsearchAttrText_AS = orig.LocExpTypeTsearchAttrText_AS;
    LocExpTypeTsearchAttrText = orig.LocExpTypeTsearchAttrText;
    LocExpTypeTotherAttrText_AS = orig.LocExpTypeTotherAttrText_AS;
    LocExpTypeTotherAttrText = orig.LocExpTypeTotherAttrText;
    LocExpTypeTotherAttrDate_AS = orig.LocExpTypeTotherAttrDate_AS;
    LocExpTypeTotherAttrDate = orig.LocExpTypeTotherAttrDate;
    LocExpTypeTotherAttrTime_AS = orig.LocExpTypeTotherAttrTime_AS;
    LocExpTypeTotherAttrTime = orig.LocExpTypeTotherAttrTime;
    LocExpTypeTotherAttrAmount_AS = orig.LocExpTypeTotherAttrAmount_AS;
    LocExpTypeTotherAttrAmount = orig.LocExpTypeTotherAttrAmount;
  }
  /**
   * Static instance creator function
   **/
  
  public static MYY10421_LA getInstance()
  {
    return new MYY10421_LA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new MYY10421_LA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    LocExpTypeTinstanceId_AS = ' ';
    LocExpTypeTinstanceId = "00000000000000000000";
    LocExpTypeTreferenceId_AS = ' ';
    LocExpTypeTreferenceId = "00000000000000000000";
    LocExpTypeTcreateUserId_AS = ' ';
    LocExpTypeTcreateUserId = "        ";
    LocExpTypeTupdateUserId_AS = ' ';
    LocExpTypeTupdateUserId = "        ";
    LocExpTypeTkeyAttrText_AS = ' ';
    LocExpTypeTkeyAttrText = "    ";
    LocExpTypeTsearchAttrText_AS = ' ';
    LocExpTypeTsearchAttrText = "                    ";
    LocExpTypeTotherAttrText_AS = ' ';
    LocExpTypeTotherAttrText = "  ";
    LocExpTypeTotherAttrDate_AS = ' ';
    LocExpTypeTotherAttrDate = 00000000;
    LocExpTypeTotherAttrTime_AS = ' ';
    LocExpTypeTotherAttrTime = 00000000;
    LocExpTypeTotherAttrAmount_AS = ' ';
    LocExpTypeTotherAttrAmount = BigDecimalAttr.getDefaultValue();
  }
}

package gen.ort.yyy;
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2023 CA Technologies. All rights reserved.
//
//    Name: MYY10421_OA                      Date: 2023/07/05
//    User: HakanBal                         Time: 15:10:04
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// Import Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
import java.lang.*;
import java.io.*;
import java.util.*;
import java.math.*;
import java.sql.*;
import com.ca.gen.vwrt.*;
import com.ca.gen.vwrt.types.*;
import com.ca.gen.vwrt.vdf.*;
import com.ca.gen.csu.exception.*;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
/**
 * Internal data view storage for: MYY10421_OA
 **/
public class MYY10421_OA extends ViewBase implements IExportView, Serializable
{
  // Entity View: EXP
  //        Type: IYY1_TYPE
  /**
   * Attribute missing flag for: ExpIyy1TypeTinstanceId
   **/
  public char ExpIyy1TypeTinstanceId_AS;
  /**
   * Attribute for: ExpIyy1TypeTinstanceId
   * Domain: Timestamp
   * Length: 20
   **/
  public String ExpIyy1TypeTinstanceId;
  /**
   * Attribute missing flag for: ExpIyy1TypeTreferenceId
   **/
  public char ExpIyy1TypeTreferenceId_AS;
  /**
   * Attribute for: ExpIyy1TypeTreferenceId
   * Domain: Timestamp
   * Length: 20
   **/
  public String ExpIyy1TypeTreferenceId;
  /**
   * Attribute missing flag for: ExpIyy1TypeTcreateUserId
   **/
  public char ExpIyy1TypeTcreateUserId_AS;
  /**
   * Attribute for: ExpIyy1TypeTcreateUserId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String ExpIyy1TypeTcreateUserId;
  /**
   * Attribute missing flag for: ExpIyy1TypeTupdateUserId
   **/
  public char ExpIyy1TypeTupdateUserId_AS;
  /**
   * Attribute for: ExpIyy1TypeTupdateUserId
   * Domain: Text
   * Length: 8
   * Varying Length: N
   **/
  public String ExpIyy1TypeTupdateUserId;
  /**
   * Attribute missing flag for: ExpIyy1TypeTkeyAttrText
   **/
  public char ExpIyy1TypeTkeyAttrText_AS;
  /**
   * Attribute for: ExpIyy1TypeTkeyAttrText
   * Domain: Text
   * Length: 4
   * Varying Length: N
   **/
  public String ExpIyy1TypeTkeyAttrText;
  /**
   * Attribute missing flag for: ExpIyy1TypeTsearchAttrText
   **/
  public char ExpIyy1TypeTsearchAttrText_AS;
  /**
   * Attribute for: ExpIyy1TypeTsearchAttrText
   * Domain: Text
   * Length: 20
   * Varying Length: N
   **/
  public String ExpIyy1TypeTsearchAttrText;
  /**
   * Attribute missing flag for: ExpIyy1TypeTotherAttrText
   **/
  public char ExpIyy1TypeTotherAttrText_AS;
  /**
   * Attribute for: ExpIyy1TypeTotherAttrText
   * Domain: Text
   * Length: 2
   * Varying Length: N
   **/
  public String ExpIyy1TypeTotherAttrText;
  /**
   * Attribute missing flag for: ExpIyy1TypeTotherAttrDate
   **/
  public char ExpIyy1TypeTotherAttrDate_AS;
  /**
   * Attribute for: ExpIyy1TypeTotherAttrDate
   * Domain: Date
   * Length: 8
   **/
  public int ExpIyy1TypeTotherAttrDate;
  /**
   * Attribute missing flag for: ExpIyy1TypeTotherAttrTime
   **/
  public char ExpIyy1TypeTotherAttrTime_AS;
  /**
   * Attribute for: ExpIyy1TypeTotherAttrTime
   * Domain: Time
   * Length: 6
   **/
  public int ExpIyy1TypeTotherAttrTime;
  /**
   * Attribute missing flag for: ExpIyy1TypeTotherAttrAmount
   **/
  public char ExpIyy1TypeTotherAttrAmount_AS;
  /**
   * Attribute for: ExpIyy1TypeTotherAttrAmount
   * Domain: Number
   * Length: 17
   * Decimal Places: 2
   * Decimal Precision: Y
   **/
  public BigDecimal ExpIyy1TypeTotherAttrAmount;
  // Entity View: EXP_ERROR
  //        Type: CANAM_XML
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlReturnCode
   **/
  public char ExpErrorCanamXmlXmlReturnCode_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlReturnCode
   * Domain: Text
   * Length: 2
   * Varying Length: N
   **/
  public String ExpErrorCanamXmlXmlReturnCode;
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlMessage
   **/
  public char ExpErrorCanamXmlXmlMessage_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlMessage
   * Domain: Text
   * Length: 80
   * Varying Length: N
   **/
  public String ExpErrorCanamXmlXmlMessage;
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlPosition
   **/
  public char ExpErrorCanamXmlXmlPosition_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlPosition
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double ExpErrorCanamXmlXmlPosition;
  /**
   * Attribute missing flag for: ExpErrorCanamXmlXmlSource
   **/
  public char ExpErrorCanamXmlXmlSource_AS;
  /**
   * Attribute for: ExpErrorCanamXmlXmlSource
   * Domain: Text
   * Length: 120
   * Varying Length: N
   **/
  public String ExpErrorCanamXmlXmlSource;
  // Entity View: EXP_ERROR
  //        Type: IYY1_COMPONENT
  /**
   * Attribute missing flag for: ExpErrorIyy1ComponentSeverityCode
   **/
  public char ExpErrorIyy1ComponentSeverityCode_AS;
  /**
   * Attribute for: ExpErrorIyy1ComponentSeverityCode
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String ExpErrorIyy1ComponentSeverityCode;
  /**
   * Attribute missing flag for: ExpErrorIyy1ComponentRollbackIndicator
   **/
  public char ExpErrorIyy1ComponentRollbackIndicator_AS;
  /**
   * Attribute for: ExpErrorIyy1ComponentRollbackIndicator
   * Domain: Text
   * Length: 1
   * Varying Length: N
   **/
  public String ExpErrorIyy1ComponentRollbackIndicator;
  /**
   * Attribute missing flag for: ExpErrorIyy1ComponentOriginServid
   **/
  public char ExpErrorIyy1ComponentOriginServid_AS;
  /**
   * Attribute for: ExpErrorIyy1ComponentOriginServid
   * Domain: Number
   * Length: 15
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public double ExpErrorIyy1ComponentOriginServid;
  /**
   * Attribute missing flag for: ExpErrorIyy1ComponentContextString
   **/
  public char ExpErrorIyy1ComponentContextString_AS;
  /**
   * Attribute for: ExpErrorIyy1ComponentContextString
   * Domain: Text
   * Length: 512
   * Varying Length: Y
   **/
  public String ExpErrorIyy1ComponentContextString;
  /**
   * Attribute missing flag for: ExpErrorIyy1ComponentReturnCode
   **/
  public char ExpErrorIyy1ComponentReturnCode_AS;
  /**
   * Attribute for: ExpErrorIyy1ComponentReturnCode
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int ExpErrorIyy1ComponentReturnCode;
  /**
   * Attribute missing flag for: ExpErrorIyy1ComponentReasonCode
   **/
  public char ExpErrorIyy1ComponentReasonCode_AS;
  /**
   * Attribute for: ExpErrorIyy1ComponentReasonCode
   * Domain: Number
   * Length: 5
   * Decimal Places: 0
   * Decimal Precision: N
   **/
  public int ExpErrorIyy1ComponentReasonCode;
  /**
   * Attribute missing flag for: ExpErrorIyy1ComponentChecksum
   **/
  public char ExpErrorIyy1ComponentChecksum_AS;
  /**
   * Attribute for: ExpErrorIyy1ComponentChecksum
   * Domain: Text
   * Length: 15
   * Varying Length: N
   **/
  public String ExpErrorIyy1ComponentChecksum;
  /**
   * Default Constructor
   **/
  
  public MYY10421_OA()
  {
    reset();
  }
  /**
   * Copy Constructor
   **/
  
  public MYY10421_OA(MYY10421_OA orig)
  {
    copyFrom(orig);
  }
  /**
   * Static instance creator function
   **/
  
  public static MYY10421_OA getInstance()
  {
    return new MYY10421_OA();
  }
  /**
   * Static free instance method
   **/
  
  public void freeInstance()
  {
  }
  /**
   * clone constructor
   **/
  
  @Override public Object clone()
  	throws CloneNotSupportedException
  {
    return(new MYY10421_OA(this));
  }
  /**
   * Resets all properties to the defaults.
   **/
  
  public void reset()
  {
    ExpIyy1TypeTinstanceId_AS = ' ';
    ExpIyy1TypeTinstanceId = "00000000000000000000";
    ExpIyy1TypeTreferenceId_AS = ' ';
    ExpIyy1TypeTreferenceId = "00000000000000000000";
    ExpIyy1TypeTcreateUserId_AS = ' ';
    ExpIyy1TypeTcreateUserId = "        ";
    ExpIyy1TypeTupdateUserId_AS = ' ';
    ExpIyy1TypeTupdateUserId = "        ";
    ExpIyy1TypeTkeyAttrText_AS = ' ';
    ExpIyy1TypeTkeyAttrText = "    ";
    ExpIyy1TypeTsearchAttrText_AS = ' ';
    ExpIyy1TypeTsearchAttrText = "                    ";
    ExpIyy1TypeTotherAttrText_AS = ' ';
    ExpIyy1TypeTotherAttrText = "  ";
    ExpIyy1TypeTotherAttrDate_AS = ' ';
    ExpIyy1TypeTotherAttrDate = 00000000;
    ExpIyy1TypeTotherAttrTime_AS = ' ';
    ExpIyy1TypeTotherAttrTime = 00000000;
    ExpIyy1TypeTotherAttrAmount_AS = ' ';
    ExpIyy1TypeTotherAttrAmount = BigDecimalAttr.getDefaultValue();
    ExpErrorCanamXmlXmlReturnCode_AS = ' ';
    ExpErrorCanamXmlXmlReturnCode = "  ";
    ExpErrorCanamXmlXmlMessage_AS = ' ';
    ExpErrorCanamXmlXmlMessage = "                                                                                ";
    ExpErrorCanamXmlXmlPosition_AS = ' ';
    ExpErrorCanamXmlXmlPosition = 0.0;
    ExpErrorCanamXmlXmlSource_AS = ' ';
    ExpErrorCanamXmlXmlSource = 
      "                                                                                                                        ";
    ExpErrorIyy1ComponentSeverityCode_AS = ' ';
    ExpErrorIyy1ComponentSeverityCode = " ";
    ExpErrorIyy1ComponentRollbackIndicator_AS = ' ';
    ExpErrorIyy1ComponentRollbackIndicator = " ";
    ExpErrorIyy1ComponentOriginServid_AS = ' ';
    ExpErrorIyy1ComponentOriginServid = 0.0;
    ExpErrorIyy1ComponentContextString_AS = ' ';
    ExpErrorIyy1ComponentContextString = "";
    ExpErrorIyy1ComponentReturnCode_AS = ' ';
    ExpErrorIyy1ComponentReturnCode = 0;
    ExpErrorIyy1ComponentReasonCode_AS = ' ';
    ExpErrorIyy1ComponentReasonCode = 0;
    ExpErrorIyy1ComponentChecksum_AS = ' ';
    ExpErrorIyy1ComponentChecksum = "               ";
  }
  /**
   * Sets the current state of the instance to the VDF version.
   **/
  public void setFromVDF(VDF vdf)
  {
    throw new RuntimeException("can only execute setFromVDF for a Procedure Step.");
  }
  
  /**
   * Gets the VDF version of the current state of the instance.
   **/
  public VDF getVDF()
  {
    throw new RuntimeException("can only execute getVDF for a Procedure Step.");
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(IExportView orig)
  {
    this.copyFrom((MYY10421_OA) orig);
  }
  
  /**
   * Sets the current instance based on the passed view.
   **/
  public void copyFrom(MYY10421_OA orig)
  {
    ExpIyy1TypeTinstanceId_AS = orig.ExpIyy1TypeTinstanceId_AS;
    ExpIyy1TypeTinstanceId = orig.ExpIyy1TypeTinstanceId;
    ExpIyy1TypeTreferenceId_AS = orig.ExpIyy1TypeTreferenceId_AS;
    ExpIyy1TypeTreferenceId = orig.ExpIyy1TypeTreferenceId;
    ExpIyy1TypeTcreateUserId_AS = orig.ExpIyy1TypeTcreateUserId_AS;
    ExpIyy1TypeTcreateUserId = orig.ExpIyy1TypeTcreateUserId;
    ExpIyy1TypeTupdateUserId_AS = orig.ExpIyy1TypeTupdateUserId_AS;
    ExpIyy1TypeTupdateUserId = orig.ExpIyy1TypeTupdateUserId;
    ExpIyy1TypeTkeyAttrText_AS = orig.ExpIyy1TypeTkeyAttrText_AS;
    ExpIyy1TypeTkeyAttrText = orig.ExpIyy1TypeTkeyAttrText;
    ExpIyy1TypeTsearchAttrText_AS = orig.ExpIyy1TypeTsearchAttrText_AS;
    ExpIyy1TypeTsearchAttrText = orig.ExpIyy1TypeTsearchAttrText;
    ExpIyy1TypeTotherAttrText_AS = orig.ExpIyy1TypeTotherAttrText_AS;
    ExpIyy1TypeTotherAttrText = orig.ExpIyy1TypeTotherAttrText;
    ExpIyy1TypeTotherAttrDate_AS = orig.ExpIyy1TypeTotherAttrDate_AS;
    ExpIyy1TypeTotherAttrDate = orig.ExpIyy1TypeTotherAttrDate;
    ExpIyy1TypeTotherAttrTime_AS = orig.ExpIyy1TypeTotherAttrTime_AS;
    ExpIyy1TypeTotherAttrTime = orig.ExpIyy1TypeTotherAttrTime;
    ExpIyy1TypeTotherAttrAmount_AS = orig.ExpIyy1TypeTotherAttrAmount_AS;
    ExpIyy1TypeTotherAttrAmount = orig.ExpIyy1TypeTotherAttrAmount;
    ExpErrorCanamXmlXmlReturnCode_AS = orig.ExpErrorCanamXmlXmlReturnCode_AS;
    ExpErrorCanamXmlXmlReturnCode = orig.ExpErrorCanamXmlXmlReturnCode;
    ExpErrorCanamXmlXmlMessage_AS = orig.ExpErrorCanamXmlXmlMessage_AS;
    ExpErrorCanamXmlXmlMessage = orig.ExpErrorCanamXmlXmlMessage;
    ExpErrorCanamXmlXmlPosition_AS = orig.ExpErrorCanamXmlXmlPosition_AS;
    ExpErrorCanamXmlXmlPosition = orig.ExpErrorCanamXmlXmlPosition;
    ExpErrorCanamXmlXmlSource_AS = orig.ExpErrorCanamXmlXmlSource_AS;
    ExpErrorCanamXmlXmlSource = orig.ExpErrorCanamXmlXmlSource;
    ExpErrorIyy1ComponentSeverityCode_AS = orig.ExpErrorIyy1ComponentSeverityCode_AS;
    ExpErrorIyy1ComponentSeverityCode = orig.ExpErrorIyy1ComponentSeverityCode;
    ExpErrorIyy1ComponentRollbackIndicator_AS = orig.ExpErrorIyy1ComponentRollbackIndicator_AS;
    ExpErrorIyy1ComponentRollbackIndicator = orig.ExpErrorIyy1ComponentRollbackIndicator;
    ExpErrorIyy1ComponentOriginServid_AS = orig.ExpErrorIyy1ComponentOriginServid_AS;
    ExpErrorIyy1ComponentOriginServid = orig.ExpErrorIyy1ComponentOriginServid;
    ExpErrorIyy1ComponentContextString_AS = orig.ExpErrorIyy1ComponentContextString_AS;
    ExpErrorIyy1ComponentContextString = orig.ExpErrorIyy1ComponentContextString;
    ExpErrorIyy1ComponentReturnCode_AS = orig.ExpErrorIyy1ComponentReturnCode_AS;
    ExpErrorIyy1ComponentReturnCode = orig.ExpErrorIyy1ComponentReturnCode;
    ExpErrorIyy1ComponentReasonCode_AS = orig.ExpErrorIyy1ComponentReasonCode_AS;
    ExpErrorIyy1ComponentReasonCode = orig.ExpErrorIyy1ComponentReasonCode;
    ExpErrorIyy1ComponentChecksum_AS = orig.ExpErrorIyy1ComponentChecksum_AS;
    ExpErrorIyy1ComponentChecksum = orig.ExpErrorIyy1ComponentChecksum;
  }
}
