// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2024 CA Technologies. All rights reserved.
//
//    Name: CYY1S071_OA                      Date: 2024/01/09
//    User: AliAl                            Time: 13:41:13
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// using Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
using System;
using com.ca.gen.vwrt;
using com.ca.gen.vwrt.types;
using com.ca.gen.vwrt.vdf;
using com.ca.gen.csu.exception;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
namespace GEN.ORT.YYY
{
  /// <summary>
  /// Internal data view storage for: CYY1S071_OA
  /// </summary>
  [Serializable]
  public class CYY1S071_OA : ViewBase, IExportView
  {
    static VDF localVdf = null;
    
    private static CYY1S071_OA[] freeArray = new CYY1S071_OA[30];
    private static int countFree = 0;
    
    // Entity View: EXP_REFERENCE
    //        Type: IYY1_SERVER_DATA
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpReferenceIyy1ServerDataServerDate
    /// </summary>
    private char _ExpReferenceIyy1ServerDataServerDate_AS;
    /// <summary>
    /// Attribute missing flag for: ExpReferenceIyy1ServerDataServerDate
    /// </summary>
    public char ExpReferenceIyy1ServerDataServerDate_AS {
      get {
        return(_ExpReferenceIyy1ServerDataServerDate_AS);
      }
      set {
        _ExpReferenceIyy1ServerDataServerDate_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpReferenceIyy1ServerDataServerDate
    /// </summary>
    private DynamicAttr _ExpReferenceIyy1ServerDataServerDate_AT;
    /// <summary>
    /// Dynamic attribute for: ExpReferenceIyy1ServerDataServerDate
    /// </summary>
    public DynamicAttr ExpReferenceIyy1ServerDataServerDate_AT {
      get {
        return(_ExpReferenceIyy1ServerDataServerDate_AT);
      }
      set {
        _ExpReferenceIyy1ServerDataServerDate_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpReferenceIyy1ServerDataServerDate
    /// Domain: Date
    /// Length: 8
    /// </summary>
    private int _ExpReferenceIyy1ServerDataServerDate;
    /// <summary>
    /// Attribute for: ExpReferenceIyy1ServerDataServerDate
    /// </summary>
    public int ExpReferenceIyy1ServerDataServerDate {
      get {
        return(_ExpReferenceIyy1ServerDataServerDate);
      }
      set {
        _ExpReferenceIyy1ServerDataServerDate = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpReferenceIyy1ServerDataServerTime
    /// </summary>
    private char _ExpReferenceIyy1ServerDataServerTime_AS;
    /// <summary>
    /// Attribute missing flag for: ExpReferenceIyy1ServerDataServerTime
    /// </summary>
    public char ExpReferenceIyy1ServerDataServerTime_AS {
      get {
        return(_ExpReferenceIyy1ServerDataServerTime_AS);
      }
      set {
        _ExpReferenceIyy1ServerDataServerTime_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpReferenceIyy1ServerDataServerTime
    /// </summary>
    private DynamicAttr _ExpReferenceIyy1ServerDataServerTime_AT;
    /// <summary>
    /// Dynamic attribute for: ExpReferenceIyy1ServerDataServerTime
    /// </summary>
    public DynamicAttr ExpReferenceIyy1ServerDataServerTime_AT {
      get {
        return(_ExpReferenceIyy1ServerDataServerTime_AT);
      }
      set {
        _ExpReferenceIyy1ServerDataServerTime_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpReferenceIyy1ServerDataServerTime
    /// Domain: Time
    /// Length: 6
    /// </summary>
    private int _ExpReferenceIyy1ServerDataServerTime;
    /// <summary>
    /// Attribute for: ExpReferenceIyy1ServerDataServerTime
    /// </summary>
    public int ExpReferenceIyy1ServerDataServerTime {
      get {
        return(_ExpReferenceIyy1ServerDataServerTime);
      }
      set {
        _ExpReferenceIyy1ServerDataServerTime = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpReferenceIyy1ServerDataReferenceId
    /// </summary>
    private char _ExpReferenceIyy1ServerDataReferenceId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpReferenceIyy1ServerDataReferenceId
    /// </summary>
    public char ExpReferenceIyy1ServerDataReferenceId_AS {
      get {
        return(_ExpReferenceIyy1ServerDataReferenceId_AS);
      }
      set {
        _ExpReferenceIyy1ServerDataReferenceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpReferenceIyy1ServerDataReferenceId
    /// </summary>
    private DynamicAttr _ExpReferenceIyy1ServerDataReferenceId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpReferenceIyy1ServerDataReferenceId
    /// </summary>
    public DynamicAttr ExpReferenceIyy1ServerDataReferenceId_AT {
      get {
        return(_ExpReferenceIyy1ServerDataReferenceId_AT);
      }
      set {
        _ExpReferenceIyy1ServerDataReferenceId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpReferenceIyy1ServerDataReferenceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ExpReferenceIyy1ServerDataReferenceId;
    /// <summary>
    /// Attribute for: ExpReferenceIyy1ServerDataReferenceId
    /// </summary>
    public string ExpReferenceIyy1ServerDataReferenceId {
      get {
        return(_ExpReferenceIyy1ServerDataReferenceId);
      }
      set {
        _ExpReferenceIyy1ServerDataReferenceId = value;
      }
    }
    // Entity View: EXP
    //        Type: ISC1_AUTHORIZATION_INFO
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIsc1AuthorizationInfoTokenId
    /// </summary>
    private char _ExpIsc1AuthorizationInfoTokenId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIsc1AuthorizationInfoTokenId
    /// </summary>
    public char ExpIsc1AuthorizationInfoTokenId_AS {
      get {
        return(_ExpIsc1AuthorizationInfoTokenId_AS);
      }
      set {
        _ExpIsc1AuthorizationInfoTokenId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpIsc1AuthorizationInfoTokenId
    /// </summary>
    private DynamicAttr _ExpIsc1AuthorizationInfoTokenId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpIsc1AuthorizationInfoTokenId
    /// </summary>
    public DynamicAttr ExpIsc1AuthorizationInfoTokenId_AT {
      get {
        return(_ExpIsc1AuthorizationInfoTokenId_AT);
      }
      set {
        _ExpIsc1AuthorizationInfoTokenId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIsc1AuthorizationInfoTokenId
    /// Domain: Text
    /// Length: 32
    /// Varying Length: N
    /// </summary>
    private string _ExpIsc1AuthorizationInfoTokenId;
    /// <summary>
    /// Attribute for: ExpIsc1AuthorizationInfoTokenId
    /// </summary>
    public string ExpIsc1AuthorizationInfoTokenId {
      get {
        return(_ExpIsc1AuthorizationInfoTokenId);
      }
      set {
        _ExpIsc1AuthorizationInfoTokenId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityInd
    /// </summary>
    private char _ExpIsc1AuthorizationInfoAuthorityInd_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityInd
    /// </summary>
    public char ExpIsc1AuthorizationInfoAuthorityInd_AS {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityInd_AS);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityInd_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityInd
    /// </summary>
    private DynamicAttr _ExpIsc1AuthorizationInfoAuthorityInd_AT;
    /// <summary>
    /// Dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityInd
    /// </summary>
    public DynamicAttr ExpIsc1AuthorizationInfoAuthorityInd_AT {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityInd_AT);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityInd_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIsc1AuthorizationInfoAuthorityInd
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpIsc1AuthorizationInfoAuthorityInd;
    /// <summary>
    /// Attribute for: ExpIsc1AuthorizationInfoAuthorityInd
    /// </summary>
    public string ExpIsc1AuthorizationInfoAuthorityInd {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityInd);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityInd = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusR
    /// </summary>
    private char _ExpIsc1AuthorizationInfoAuthorityStatusR_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusR
    /// </summary>
    public char ExpIsc1AuthorizationInfoAuthorityStatusR_AS {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusR_AS);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusR_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusR
    /// </summary>
    private DynamicAttr _ExpIsc1AuthorizationInfoAuthorityStatusR_AT;
    /// <summary>
    /// Dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusR
    /// </summary>
    public DynamicAttr ExpIsc1AuthorizationInfoAuthorityStatusR_AT {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusR_AT);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusR_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIsc1AuthorizationInfoAuthorityStatusR
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpIsc1AuthorizationInfoAuthorityStatusR;
    /// <summary>
    /// Attribute for: ExpIsc1AuthorizationInfoAuthorityStatusR
    /// </summary>
    public string ExpIsc1AuthorizationInfoAuthorityStatusR {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusR);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusR = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusU
    /// </summary>
    private char _ExpIsc1AuthorizationInfoAuthorityStatusU_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusU
    /// </summary>
    public char ExpIsc1AuthorizationInfoAuthorityStatusU_AS {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusU_AS);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusU_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusU
    /// </summary>
    private DynamicAttr _ExpIsc1AuthorizationInfoAuthorityStatusU_AT;
    /// <summary>
    /// Dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusU
    /// </summary>
    public DynamicAttr ExpIsc1AuthorizationInfoAuthorityStatusU_AT {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusU_AT);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusU_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIsc1AuthorizationInfoAuthorityStatusU
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpIsc1AuthorizationInfoAuthorityStatusU;
    /// <summary>
    /// Attribute for: ExpIsc1AuthorizationInfoAuthorityStatusU
    /// </summary>
    public string ExpIsc1AuthorizationInfoAuthorityStatusU {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusU);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusU = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusD
    /// </summary>
    private char _ExpIsc1AuthorizationInfoAuthorityStatusD_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusD
    /// </summary>
    public char ExpIsc1AuthorizationInfoAuthorityStatusD_AS {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusD_AS);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusD_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusD
    /// </summary>
    private DynamicAttr _ExpIsc1AuthorizationInfoAuthorityStatusD_AT;
    /// <summary>
    /// Dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusD
    /// </summary>
    public DynamicAttr ExpIsc1AuthorizationInfoAuthorityStatusD_AT {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusD_AT);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusD_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIsc1AuthorizationInfoAuthorityStatusD
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpIsc1AuthorizationInfoAuthorityStatusD;
    /// <summary>
    /// Attribute for: ExpIsc1AuthorizationInfoAuthorityStatusD
    /// </summary>
    public string ExpIsc1AuthorizationInfoAuthorityStatusD {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusD);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusD = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusL
    /// </summary>
    private char _ExpIsc1AuthorizationInfoAuthorityStatusL_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIsc1AuthorizationInfoAuthorityStatusL
    /// </summary>
    public char ExpIsc1AuthorizationInfoAuthorityStatusL_AS {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusL_AS);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusL_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusL
    /// </summary>
    private DynamicAttr _ExpIsc1AuthorizationInfoAuthorityStatusL_AT;
    /// <summary>
    /// Dynamic attribute for: ExpIsc1AuthorizationInfoAuthorityStatusL
    /// </summary>
    public DynamicAttr ExpIsc1AuthorizationInfoAuthorityStatusL_AT {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusL_AT);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusL_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIsc1AuthorizationInfoAuthorityStatusL
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpIsc1AuthorizationInfoAuthorityStatusL;
    /// <summary>
    /// Attribute for: ExpIsc1AuthorizationInfoAuthorityStatusL
    /// </summary>
    public string ExpIsc1AuthorizationInfoAuthorityStatusL {
      get {
        return(_ExpIsc1AuthorizationInfoAuthorityStatusL);
      }
      set {
        _ExpIsc1AuthorizationInfoAuthorityStatusL = value;
      }
    }
    // Entity View: EXP_ALL
    //        Type: TYPE
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTinstanceId
    /// </summary>
    private char _ExpAllTypeTinstanceId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTinstanceId
    /// </summary>
    public char ExpAllTypeTinstanceId_AS {
      get {
        return(_ExpAllTypeTinstanceId_AS);
      }
      set {
        _ExpAllTypeTinstanceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTinstanceId
    /// </summary>
    private DynamicAttr _ExpAllTypeTinstanceId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTinstanceId
    /// </summary>
    public DynamicAttr ExpAllTypeTinstanceId_AT {
      get {
        return(_ExpAllTypeTinstanceId_AT);
      }
      set {
        _ExpAllTypeTinstanceId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTinstanceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ExpAllTypeTinstanceId;
    /// <summary>
    /// Attribute for: ExpAllTypeTinstanceId
    /// </summary>
    public string ExpAllTypeTinstanceId {
      get {
        return(_ExpAllTypeTinstanceId);
      }
      set {
        _ExpAllTypeTinstanceId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTreferenceId
    /// </summary>
    private char _ExpAllTypeTreferenceId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTreferenceId
    /// </summary>
    public char ExpAllTypeTreferenceId_AS {
      get {
        return(_ExpAllTypeTreferenceId_AS);
      }
      set {
        _ExpAllTypeTreferenceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTreferenceId
    /// </summary>
    private DynamicAttr _ExpAllTypeTreferenceId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTreferenceId
    /// </summary>
    public DynamicAttr ExpAllTypeTreferenceId_AT {
      get {
        return(_ExpAllTypeTreferenceId_AT);
      }
      set {
        _ExpAllTypeTreferenceId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTreferenceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ExpAllTypeTreferenceId;
    /// <summary>
    /// Attribute for: ExpAllTypeTreferenceId
    /// </summary>
    public string ExpAllTypeTreferenceId {
      get {
        return(_ExpAllTypeTreferenceId);
      }
      set {
        _ExpAllTypeTreferenceId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTcreateUserId
    /// </summary>
    private char _ExpAllTypeTcreateUserId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTcreateUserId
    /// </summary>
    public char ExpAllTypeTcreateUserId_AS {
      get {
        return(_ExpAllTypeTcreateUserId_AS);
      }
      set {
        _ExpAllTypeTcreateUserId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTcreateUserId
    /// </summary>
    private DynamicAttr _ExpAllTypeTcreateUserId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTcreateUserId
    /// </summary>
    public DynamicAttr ExpAllTypeTcreateUserId_AT {
      get {
        return(_ExpAllTypeTcreateUserId_AT);
      }
      set {
        _ExpAllTypeTcreateUserId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTcreateUserId
    /// Domain: Text
    /// Length: 8
    /// Varying Length: N
    /// </summary>
    private string _ExpAllTypeTcreateUserId;
    /// <summary>
    /// Attribute for: ExpAllTypeTcreateUserId
    /// </summary>
    public string ExpAllTypeTcreateUserId {
      get {
        return(_ExpAllTypeTcreateUserId);
      }
      set {
        _ExpAllTypeTcreateUserId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTupdateUserId
    /// </summary>
    private char _ExpAllTypeTupdateUserId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTupdateUserId
    /// </summary>
    public char ExpAllTypeTupdateUserId_AS {
      get {
        return(_ExpAllTypeTupdateUserId_AS);
      }
      set {
        _ExpAllTypeTupdateUserId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTupdateUserId
    /// </summary>
    private DynamicAttr _ExpAllTypeTupdateUserId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTupdateUserId
    /// </summary>
    public DynamicAttr ExpAllTypeTupdateUserId_AT {
      get {
        return(_ExpAllTypeTupdateUserId_AT);
      }
      set {
        _ExpAllTypeTupdateUserId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTupdateUserId
    /// Domain: Text
    /// Length: 8
    /// Varying Length: N
    /// </summary>
    private string _ExpAllTypeTupdateUserId;
    /// <summary>
    /// Attribute for: ExpAllTypeTupdateUserId
    /// </summary>
    public string ExpAllTypeTupdateUserId {
      get {
        return(_ExpAllTypeTupdateUserId);
      }
      set {
        _ExpAllTypeTupdateUserId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTkeyAttrText
    /// </summary>
    private char _ExpAllTypeTkeyAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTkeyAttrText
    /// </summary>
    public char ExpAllTypeTkeyAttrText_AS {
      get {
        return(_ExpAllTypeTkeyAttrText_AS);
      }
      set {
        _ExpAllTypeTkeyAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTkeyAttrText
    /// </summary>
    private DynamicAttr _ExpAllTypeTkeyAttrText_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTkeyAttrText
    /// </summary>
    public DynamicAttr ExpAllTypeTkeyAttrText_AT {
      get {
        return(_ExpAllTypeTkeyAttrText_AT);
      }
      set {
        _ExpAllTypeTkeyAttrText_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTkeyAttrText
    /// Domain: Text
    /// Length: 4
    /// Varying Length: N
    /// </summary>
    private string _ExpAllTypeTkeyAttrText;
    /// <summary>
    /// Attribute for: ExpAllTypeTkeyAttrText
    /// </summary>
    public string ExpAllTypeTkeyAttrText {
      get {
        return(_ExpAllTypeTkeyAttrText);
      }
      set {
        _ExpAllTypeTkeyAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTsearchAttrText
    /// </summary>
    private char _ExpAllTypeTsearchAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTsearchAttrText
    /// </summary>
    public char ExpAllTypeTsearchAttrText_AS {
      get {
        return(_ExpAllTypeTsearchAttrText_AS);
      }
      set {
        _ExpAllTypeTsearchAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTsearchAttrText
    /// </summary>
    private DynamicAttr _ExpAllTypeTsearchAttrText_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTsearchAttrText
    /// </summary>
    public DynamicAttr ExpAllTypeTsearchAttrText_AT {
      get {
        return(_ExpAllTypeTsearchAttrText_AT);
      }
      set {
        _ExpAllTypeTsearchAttrText_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTsearchAttrText
    /// Domain: Text
    /// Length: 20
    /// Varying Length: N
    /// </summary>
    private string _ExpAllTypeTsearchAttrText;
    /// <summary>
    /// Attribute for: ExpAllTypeTsearchAttrText
    /// </summary>
    public string ExpAllTypeTsearchAttrText {
      get {
        return(_ExpAllTypeTsearchAttrText);
      }
      set {
        _ExpAllTypeTsearchAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTotherAttrText
    /// </summary>
    private char _ExpAllTypeTotherAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTotherAttrText
    /// </summary>
    public char ExpAllTypeTotherAttrText_AS {
      get {
        return(_ExpAllTypeTotherAttrText_AS);
      }
      set {
        _ExpAllTypeTotherAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTotherAttrText
    /// </summary>
    private DynamicAttr _ExpAllTypeTotherAttrText_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTotherAttrText
    /// </summary>
    public DynamicAttr ExpAllTypeTotherAttrText_AT {
      get {
        return(_ExpAllTypeTotherAttrText_AT);
      }
      set {
        _ExpAllTypeTotherAttrText_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTotherAttrText
    /// Domain: Text
    /// Length: 2
    /// Varying Length: N
    /// </summary>
    private string _ExpAllTypeTotherAttrText;
    /// <summary>
    /// Attribute for: ExpAllTypeTotherAttrText
    /// </summary>
    public string ExpAllTypeTotherAttrText {
      get {
        return(_ExpAllTypeTotherAttrText);
      }
      set {
        _ExpAllTypeTotherAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTotherAttrDate
    /// </summary>
    private char _ExpAllTypeTotherAttrDate_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTotherAttrDate
    /// </summary>
    public char ExpAllTypeTotherAttrDate_AS {
      get {
        return(_ExpAllTypeTotherAttrDate_AS);
      }
      set {
        _ExpAllTypeTotherAttrDate_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTotherAttrDate
    /// </summary>
    private DynamicAttr _ExpAllTypeTotherAttrDate_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTotherAttrDate
    /// </summary>
    public DynamicAttr ExpAllTypeTotherAttrDate_AT {
      get {
        return(_ExpAllTypeTotherAttrDate_AT);
      }
      set {
        _ExpAllTypeTotherAttrDate_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTotherAttrDate
    /// Domain: Date
    /// Length: 8
    /// </summary>
    private int _ExpAllTypeTotherAttrDate;
    /// <summary>
    /// Attribute for: ExpAllTypeTotherAttrDate
    /// </summary>
    public int ExpAllTypeTotherAttrDate {
      get {
        return(_ExpAllTypeTotherAttrDate);
      }
      set {
        _ExpAllTypeTotherAttrDate = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTotherAttrTime
    /// </summary>
    private char _ExpAllTypeTotherAttrTime_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTotherAttrTime
    /// </summary>
    public char ExpAllTypeTotherAttrTime_AS {
      get {
        return(_ExpAllTypeTotherAttrTime_AS);
      }
      set {
        _ExpAllTypeTotherAttrTime_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTotherAttrTime
    /// </summary>
    private DynamicAttr _ExpAllTypeTotherAttrTime_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTotherAttrTime
    /// </summary>
    public DynamicAttr ExpAllTypeTotherAttrTime_AT {
      get {
        return(_ExpAllTypeTotherAttrTime_AT);
      }
      set {
        _ExpAllTypeTotherAttrTime_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTotherAttrTime
    /// Domain: Time
    /// Length: 6
    /// </summary>
    private int _ExpAllTypeTotherAttrTime;
    /// <summary>
    /// Attribute for: ExpAllTypeTotherAttrTime
    /// </summary>
    public int ExpAllTypeTotherAttrTime {
      get {
        return(_ExpAllTypeTotherAttrTime);
      }
      set {
        _ExpAllTypeTotherAttrTime = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpAllTypeTotherAttrAmount
    /// </summary>
    private char _ExpAllTypeTotherAttrAmount_AS;
    /// <summary>
    /// Attribute missing flag for: ExpAllTypeTotherAttrAmount
    /// </summary>
    public char ExpAllTypeTotherAttrAmount_AS {
      get {
        return(_ExpAllTypeTotherAttrAmount_AS);
      }
      set {
        _ExpAllTypeTotherAttrAmount_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpAllTypeTotherAttrAmount
    /// </summary>
    private DynamicAttr _ExpAllTypeTotherAttrAmount_AT;
    /// <summary>
    /// Dynamic attribute for: ExpAllTypeTotherAttrAmount
    /// </summary>
    public DynamicAttr ExpAllTypeTotherAttrAmount_AT {
      get {
        return(_ExpAllTypeTotherAttrAmount_AT);
      }
      set {
        _ExpAllTypeTotherAttrAmount_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpAllTypeTotherAttrAmount
    /// Domain: Number
    /// Length: 17
    /// Decimal Places: 2
    /// Decimal Precision: Y
    /// </summary>
    private decimal _ExpAllTypeTotherAttrAmount;
    /// <summary>
    /// Attribute for: ExpAllTypeTotherAttrAmount
    /// </summary>
    public decimal ExpAllTypeTotherAttrAmount {
      get {
        return(_ExpAllTypeTotherAttrAmount);
      }
      set {
        _ExpAllTypeTotherAttrAmount = value;
      }
    }
    // Entity View: EXP_TS
    //        Type: TYPE
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpTsTypeTinstanceId
    /// </summary>
    private char _ExpTsTypeTinstanceId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpTsTypeTinstanceId
    /// </summary>
    public char ExpTsTypeTinstanceId_AS {
      get {
        return(_ExpTsTypeTinstanceId_AS);
      }
      set {
        _ExpTsTypeTinstanceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpTsTypeTinstanceId
    /// </summary>
    private DynamicAttr _ExpTsTypeTinstanceId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpTsTypeTinstanceId
    /// </summary>
    public DynamicAttr ExpTsTypeTinstanceId_AT {
      get {
        return(_ExpTsTypeTinstanceId_AT);
      }
      set {
        _ExpTsTypeTinstanceId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpTsTypeTinstanceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ExpTsTypeTinstanceId;
    /// <summary>
    /// Attribute for: ExpTsTypeTinstanceId
    /// </summary>
    public string ExpTsTypeTinstanceId {
      get {
        return(_ExpTsTypeTinstanceId);
      }
      set {
        _ExpTsTypeTinstanceId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpTsTypeTreferenceId
    /// </summary>
    private char _ExpTsTypeTreferenceId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpTsTypeTreferenceId
    /// </summary>
    public char ExpTsTypeTreferenceId_AS {
      get {
        return(_ExpTsTypeTreferenceId_AS);
      }
      set {
        _ExpTsTypeTreferenceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpTsTypeTreferenceId
    /// </summary>
    private DynamicAttr _ExpTsTypeTreferenceId_AT;
    /// <summary>
    /// Dynamic attribute for: ExpTsTypeTreferenceId
    /// </summary>
    public DynamicAttr ExpTsTypeTreferenceId_AT {
      get {
        return(_ExpTsTypeTreferenceId_AT);
      }
      set {
        _ExpTsTypeTreferenceId_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpTsTypeTreferenceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ExpTsTypeTreferenceId;
    /// <summary>
    /// Attribute for: ExpTsTypeTreferenceId
    /// </summary>
    public string ExpTsTypeTreferenceId {
      get {
        return(_ExpTsTypeTreferenceId);
      }
      set {
        _ExpTsTypeTreferenceId = value;
      }
    }
    // Entity View: EXP_MSG
    //        Type: IYY1_COMPONENT
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpMsgIyy1ComponentSeverityCode
    /// </summary>
    private char _ExpMsgIyy1ComponentSeverityCode_AS;
    /// <summary>
    /// Attribute missing flag for: ExpMsgIyy1ComponentSeverityCode
    /// </summary>
    public char ExpMsgIyy1ComponentSeverityCode_AS {
      get {
        return(_ExpMsgIyy1ComponentSeverityCode_AS);
      }
      set {
        _ExpMsgIyy1ComponentSeverityCode_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpMsgIyy1ComponentSeverityCode
    /// </summary>
    private DynamicAttr _ExpMsgIyy1ComponentSeverityCode_AT;
    /// <summary>
    /// Dynamic attribute for: ExpMsgIyy1ComponentSeverityCode
    /// </summary>
    public DynamicAttr ExpMsgIyy1ComponentSeverityCode_AT {
      get {
        return(_ExpMsgIyy1ComponentSeverityCode_AT);
      }
      set {
        _ExpMsgIyy1ComponentSeverityCode_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpMsgIyy1ComponentSeverityCode
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpMsgIyy1ComponentSeverityCode;
    /// <summary>
    /// Attribute for: ExpMsgIyy1ComponentSeverityCode
    /// </summary>
    public string ExpMsgIyy1ComponentSeverityCode {
      get {
        return(_ExpMsgIyy1ComponentSeverityCode);
      }
      set {
        _ExpMsgIyy1ComponentSeverityCode = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpMsgIyy1ComponentMessageTx
    /// </summary>
    private char _ExpMsgIyy1ComponentMessageTx_AS;
    /// <summary>
    /// Attribute missing flag for: ExpMsgIyy1ComponentMessageTx
    /// </summary>
    public char ExpMsgIyy1ComponentMessageTx_AS {
      get {
        return(_ExpMsgIyy1ComponentMessageTx_AS);
      }
      set {
        _ExpMsgIyy1ComponentMessageTx_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpMsgIyy1ComponentMessageTx
    /// </summary>
    private DynamicAttr _ExpMsgIyy1ComponentMessageTx_AT;
    /// <summary>
    /// Dynamic attribute for: ExpMsgIyy1ComponentMessageTx
    /// </summary>
    public DynamicAttr ExpMsgIyy1ComponentMessageTx_AT {
      get {
        return(_ExpMsgIyy1ComponentMessageTx_AT);
      }
      set {
        _ExpMsgIyy1ComponentMessageTx_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpMsgIyy1ComponentMessageTx
    /// Domain: Text
    /// Length: 512
    /// Varying Length: Y
    /// </summary>
    private string _ExpMsgIyy1ComponentMessageTx;
    /// <summary>
    /// Attribute for: ExpMsgIyy1ComponentMessageTx
    /// </summary>
    public string ExpMsgIyy1ComponentMessageTx {
      get {
        return(_ExpMsgIyy1ComponentMessageTx);
      }
      set {
        _ExpMsgIyy1ComponentMessageTx = value;
      }
    }
    // Entity View: EXP_ERROR
    //        Type: IYY1_COMPONENT
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    private char _ExpErrorIyy1ComponentSeverityCode_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    public char ExpErrorIyy1ComponentSeverityCode_AS {
      get {
        return(_ExpErrorIyy1ComponentSeverityCode_AS);
      }
      set {
        _ExpErrorIyy1ComponentSeverityCode_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    private DynamicAttr _ExpErrorIyy1ComponentSeverityCode_AT;
    /// <summary>
    /// Dynamic attribute for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    public DynamicAttr ExpErrorIyy1ComponentSeverityCode_AT {
      get {
        return(_ExpErrorIyy1ComponentSeverityCode_AT);
      }
      set {
        _ExpErrorIyy1ComponentSeverityCode_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentSeverityCode
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpErrorIyy1ComponentSeverityCode;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    public string ExpErrorIyy1ComponentSeverityCode {
      get {
        return(_ExpErrorIyy1ComponentSeverityCode);
      }
      set {
        _ExpErrorIyy1ComponentSeverityCode = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    private char _ExpErrorIyy1ComponentRollbackIndicator_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    public char ExpErrorIyy1ComponentRollbackIndicator_AS {
      get {
        return(_ExpErrorIyy1ComponentRollbackIndicator_AS);
      }
      set {
        _ExpErrorIyy1ComponentRollbackIndicator_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    private DynamicAttr _ExpErrorIyy1ComponentRollbackIndicator_AT;
    /// <summary>
    /// Dynamic attribute for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    public DynamicAttr ExpErrorIyy1ComponentRollbackIndicator_AT {
      get {
        return(_ExpErrorIyy1ComponentRollbackIndicator_AT);
      }
      set {
        _ExpErrorIyy1ComponentRollbackIndicator_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentRollbackIndicator
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpErrorIyy1ComponentRollbackIndicator;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    public string ExpErrorIyy1ComponentRollbackIndicator {
      get {
        return(_ExpErrorIyy1ComponentRollbackIndicator);
      }
      set {
        _ExpErrorIyy1ComponentRollbackIndicator = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    private char _ExpErrorIyy1ComponentOriginServid_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    public char ExpErrorIyy1ComponentOriginServid_AS {
      get {
        return(_ExpErrorIyy1ComponentOriginServid_AS);
      }
      set {
        _ExpErrorIyy1ComponentOriginServid_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    private DynamicAttr _ExpErrorIyy1ComponentOriginServid_AT;
    /// <summary>
    /// Dynamic attribute for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    public DynamicAttr ExpErrorIyy1ComponentOriginServid_AT {
      get {
        return(_ExpErrorIyy1ComponentOriginServid_AT);
      }
      set {
        _ExpErrorIyy1ComponentOriginServid_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentOriginServid
    /// Domain: Number
    /// Length: 15
    /// Decimal Places: 0
    /// Decimal Precision: N
    /// </summary>
    private double _ExpErrorIyy1ComponentOriginServid;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    public double ExpErrorIyy1ComponentOriginServid {
      get {
        return(_ExpErrorIyy1ComponentOriginServid);
      }
      set {
        _ExpErrorIyy1ComponentOriginServid = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentContextString
    /// </summary>
    private char _ExpErrorIyy1ComponentContextString_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentContextString
    /// </summary>
    public char ExpErrorIyy1ComponentContextString_AS {
      get {
        return(_ExpErrorIyy1ComponentContextString_AS);
      }
      set {
        _ExpErrorIyy1ComponentContextString_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpErrorIyy1ComponentContextString
    /// </summary>
    private DynamicAttr _ExpErrorIyy1ComponentContextString_AT;
    /// <summary>
    /// Dynamic attribute for: ExpErrorIyy1ComponentContextString
    /// </summary>
    public DynamicAttr ExpErrorIyy1ComponentContextString_AT {
      get {
        return(_ExpErrorIyy1ComponentContextString_AT);
      }
      set {
        _ExpErrorIyy1ComponentContextString_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentContextString
    /// Domain: Text
    /// Length: 512
    /// Varying Length: Y
    /// </summary>
    private string _ExpErrorIyy1ComponentContextString;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentContextString
    /// </summary>
    public string ExpErrorIyy1ComponentContextString {
      get {
        return(_ExpErrorIyy1ComponentContextString);
      }
      set {
        _ExpErrorIyy1ComponentContextString = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    private char _ExpErrorIyy1ComponentReturnCode_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    public char ExpErrorIyy1ComponentReturnCode_AS {
      get {
        return(_ExpErrorIyy1ComponentReturnCode_AS);
      }
      set {
        _ExpErrorIyy1ComponentReturnCode_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    private DynamicAttr _ExpErrorIyy1ComponentReturnCode_AT;
    /// <summary>
    /// Dynamic attribute for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    public DynamicAttr ExpErrorIyy1ComponentReturnCode_AT {
      get {
        return(_ExpErrorIyy1ComponentReturnCode_AT);
      }
      set {
        _ExpErrorIyy1ComponentReturnCode_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentReturnCode
    /// Domain: Number
    /// Length: 5
    /// Decimal Places: 0
    /// Decimal Precision: N
    /// </summary>
    private int _ExpErrorIyy1ComponentReturnCode;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    public int ExpErrorIyy1ComponentReturnCode {
      get {
        return(_ExpErrorIyy1ComponentReturnCode);
      }
      set {
        _ExpErrorIyy1ComponentReturnCode = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    private char _ExpErrorIyy1ComponentReasonCode_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    public char ExpErrorIyy1ComponentReasonCode_AS {
      get {
        return(_ExpErrorIyy1ComponentReasonCode_AS);
      }
      set {
        _ExpErrorIyy1ComponentReasonCode_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    private DynamicAttr _ExpErrorIyy1ComponentReasonCode_AT;
    /// <summary>
    /// Dynamic attribute for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    public DynamicAttr ExpErrorIyy1ComponentReasonCode_AT {
      get {
        return(_ExpErrorIyy1ComponentReasonCode_AT);
      }
      set {
        _ExpErrorIyy1ComponentReasonCode_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentReasonCode
    /// Domain: Number
    /// Length: 5
    /// Decimal Places: 0
    /// Decimal Precision: N
    /// </summary>
    private int _ExpErrorIyy1ComponentReasonCode;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    public int ExpErrorIyy1ComponentReasonCode {
      get {
        return(_ExpErrorIyy1ComponentReasonCode);
      }
      set {
        _ExpErrorIyy1ComponentReasonCode = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    private char _ExpErrorIyy1ComponentChecksum_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    public char ExpErrorIyy1ComponentChecksum_AS {
      get {
        return(_ExpErrorIyy1ComponentChecksum_AS);
      }
      set {
        _ExpErrorIyy1ComponentChecksum_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, dynamic attribute for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    private DynamicAttr _ExpErrorIyy1ComponentChecksum_AT;
    /// <summary>
    /// Dynamic attribute for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    public DynamicAttr ExpErrorIyy1ComponentChecksum_AT {
      get {
        return(_ExpErrorIyy1ComponentChecksum_AT);
      }
      set {
        _ExpErrorIyy1ComponentChecksum_AT = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentChecksum
    /// Domain: Text
    /// Length: 15
    /// Varying Length: N
    /// </summary>
    private string _ExpErrorIyy1ComponentChecksum;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    public string ExpErrorIyy1ComponentChecksum {
      get {
        return(_ExpErrorIyy1ComponentChecksum);
      }
      set {
        _ExpErrorIyy1ComponentChecksum = value;
      }
    }
    /// <summary>
    /// Default Constructor
    /// </summary>
    
    public CYY1S071_OA(  )
    {
      Reset(  );
    }
    /// <summary>
    /// Copy Constructor
    /// </summary>
    
    public CYY1S071_OA( CYY1S071_OA orig )
    {
      ExpReferenceIyy1ServerDataServerDate_AT = orig.ExpReferenceIyy1ServerDataServerDate_AT;
      ExpReferenceIyy1ServerDataServerDate_AS = orig.ExpReferenceIyy1ServerDataServerDate_AS;
      ExpReferenceIyy1ServerDataServerDate = orig.ExpReferenceIyy1ServerDataServerDate;
      ExpReferenceIyy1ServerDataServerTime_AT = orig.ExpReferenceIyy1ServerDataServerTime_AT;
      ExpReferenceIyy1ServerDataServerTime_AS = orig.ExpReferenceIyy1ServerDataServerTime_AS;
      ExpReferenceIyy1ServerDataServerTime = orig.ExpReferenceIyy1ServerDataServerTime;
      ExpReferenceIyy1ServerDataReferenceId_AT = orig.ExpReferenceIyy1ServerDataReferenceId_AT;
      ExpReferenceIyy1ServerDataReferenceId_AS = orig.ExpReferenceIyy1ServerDataReferenceId_AS;
      ExpReferenceIyy1ServerDataReferenceId = orig.ExpReferenceIyy1ServerDataReferenceId;
      ExpIsc1AuthorizationInfoTokenId_AT = orig.ExpIsc1AuthorizationInfoTokenId_AT;
      ExpIsc1AuthorizationInfoTokenId_AS = orig.ExpIsc1AuthorizationInfoTokenId_AS;
      ExpIsc1AuthorizationInfoTokenId = orig.ExpIsc1AuthorizationInfoTokenId;
      ExpIsc1AuthorizationInfoAuthorityInd_AT = orig.ExpIsc1AuthorizationInfoAuthorityInd_AT;
      ExpIsc1AuthorizationInfoAuthorityInd_AS = orig.ExpIsc1AuthorizationInfoAuthorityInd_AS;
      ExpIsc1AuthorizationInfoAuthorityInd = orig.ExpIsc1AuthorizationInfoAuthorityInd;
      ExpIsc1AuthorizationInfoAuthorityStatusR_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusR_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusR_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusR_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusR = orig.ExpIsc1AuthorizationInfoAuthorityStatusR;
      ExpIsc1AuthorizationInfoAuthorityStatusU_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusU_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusU_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusU_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusU = orig.ExpIsc1AuthorizationInfoAuthorityStatusU;
      ExpIsc1AuthorizationInfoAuthorityStatusD_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusD_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusD_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusD_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusD = orig.ExpIsc1AuthorizationInfoAuthorityStatusD;
      ExpIsc1AuthorizationInfoAuthorityStatusL_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusL_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusL_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusL_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusL = orig.ExpIsc1AuthorizationInfoAuthorityStatusL;
      ExpAllTypeTinstanceId_AT = orig.ExpAllTypeTinstanceId_AT;
      ExpAllTypeTinstanceId_AS = orig.ExpAllTypeTinstanceId_AS;
      ExpAllTypeTinstanceId = orig.ExpAllTypeTinstanceId;
      ExpAllTypeTreferenceId_AT = orig.ExpAllTypeTreferenceId_AT;
      ExpAllTypeTreferenceId_AS = orig.ExpAllTypeTreferenceId_AS;
      ExpAllTypeTreferenceId = orig.ExpAllTypeTreferenceId;
      ExpAllTypeTcreateUserId_AT = orig.ExpAllTypeTcreateUserId_AT;
      ExpAllTypeTcreateUserId_AS = orig.ExpAllTypeTcreateUserId_AS;
      ExpAllTypeTcreateUserId = orig.ExpAllTypeTcreateUserId;
      ExpAllTypeTupdateUserId_AT = orig.ExpAllTypeTupdateUserId_AT;
      ExpAllTypeTupdateUserId_AS = orig.ExpAllTypeTupdateUserId_AS;
      ExpAllTypeTupdateUserId = orig.ExpAllTypeTupdateUserId;
      ExpAllTypeTkeyAttrText_AT = orig.ExpAllTypeTkeyAttrText_AT;
      ExpAllTypeTkeyAttrText_AS = orig.ExpAllTypeTkeyAttrText_AS;
      ExpAllTypeTkeyAttrText = orig.ExpAllTypeTkeyAttrText;
      ExpAllTypeTsearchAttrText_AT = orig.ExpAllTypeTsearchAttrText_AT;
      ExpAllTypeTsearchAttrText_AS = orig.ExpAllTypeTsearchAttrText_AS;
      ExpAllTypeTsearchAttrText = orig.ExpAllTypeTsearchAttrText;
      ExpAllTypeTotherAttrText_AT = orig.ExpAllTypeTotherAttrText_AT;
      ExpAllTypeTotherAttrText_AS = orig.ExpAllTypeTotherAttrText_AS;
      ExpAllTypeTotherAttrText = orig.ExpAllTypeTotherAttrText;
      ExpAllTypeTotherAttrDate_AT = orig.ExpAllTypeTotherAttrDate_AT;
      ExpAllTypeTotherAttrDate_AS = orig.ExpAllTypeTotherAttrDate_AS;
      ExpAllTypeTotherAttrDate = orig.ExpAllTypeTotherAttrDate;
      ExpAllTypeTotherAttrTime_AT = orig.ExpAllTypeTotherAttrTime_AT;
      ExpAllTypeTotherAttrTime_AS = orig.ExpAllTypeTotherAttrTime_AS;
      ExpAllTypeTotherAttrTime = orig.ExpAllTypeTotherAttrTime;
      ExpAllTypeTotherAttrAmount_AT = orig.ExpAllTypeTotherAttrAmount_AT;
      ExpAllTypeTotherAttrAmount_AS = orig.ExpAllTypeTotherAttrAmount_AS;
      ExpAllTypeTotherAttrAmount = orig.ExpAllTypeTotherAttrAmount;
      ExpTsTypeTinstanceId_AT = orig.ExpTsTypeTinstanceId_AT;
      ExpTsTypeTinstanceId_AS = orig.ExpTsTypeTinstanceId_AS;
      ExpTsTypeTinstanceId = orig.ExpTsTypeTinstanceId;
      ExpTsTypeTreferenceId_AT = orig.ExpTsTypeTreferenceId_AT;
      ExpTsTypeTreferenceId_AS = orig.ExpTsTypeTreferenceId_AS;
      ExpTsTypeTreferenceId = orig.ExpTsTypeTreferenceId;
      ExpMsgIyy1ComponentSeverityCode_AT = orig.ExpMsgIyy1ComponentSeverityCode_AT;
      ExpMsgIyy1ComponentSeverityCode_AS = orig.ExpMsgIyy1ComponentSeverityCode_AS;
      ExpMsgIyy1ComponentSeverityCode = orig.ExpMsgIyy1ComponentSeverityCode;
      ExpMsgIyy1ComponentMessageTx_AT = orig.ExpMsgIyy1ComponentMessageTx_AT;
      ExpMsgIyy1ComponentMessageTx_AS = orig.ExpMsgIyy1ComponentMessageTx_AS;
      ExpMsgIyy1ComponentMessageTx = orig.ExpMsgIyy1ComponentMessageTx;
      ExpErrorIyy1ComponentSeverityCode_AT = orig.ExpErrorIyy1ComponentSeverityCode_AT;
      ExpErrorIyy1ComponentSeverityCode_AS = orig.ExpErrorIyy1ComponentSeverityCode_AS;
      ExpErrorIyy1ComponentSeverityCode = orig.ExpErrorIyy1ComponentSeverityCode;
      ExpErrorIyy1ComponentRollbackIndicator_AT = orig.ExpErrorIyy1ComponentRollbackIndicator_AT;
      ExpErrorIyy1ComponentRollbackIndicator_AS = orig.ExpErrorIyy1ComponentRollbackIndicator_AS;
      ExpErrorIyy1ComponentRollbackIndicator = orig.ExpErrorIyy1ComponentRollbackIndicator;
      ExpErrorIyy1ComponentOriginServid_AT = orig.ExpErrorIyy1ComponentOriginServid_AT;
      ExpErrorIyy1ComponentOriginServid_AS = orig.ExpErrorIyy1ComponentOriginServid_AS;
      ExpErrorIyy1ComponentOriginServid = orig.ExpErrorIyy1ComponentOriginServid;
      ExpErrorIyy1ComponentContextString_AT = orig.ExpErrorIyy1ComponentContextString_AT;
      ExpErrorIyy1ComponentContextString_AS = orig.ExpErrorIyy1ComponentContextString_AS;
      ExpErrorIyy1ComponentContextString = orig.ExpErrorIyy1ComponentContextString;
      ExpErrorIyy1ComponentReturnCode_AT = orig.ExpErrorIyy1ComponentReturnCode_AT;
      ExpErrorIyy1ComponentReturnCode_AS = orig.ExpErrorIyy1ComponentReturnCode_AS;
      ExpErrorIyy1ComponentReturnCode = orig.ExpErrorIyy1ComponentReturnCode;
      ExpErrorIyy1ComponentReasonCode_AT = orig.ExpErrorIyy1ComponentReasonCode_AT;
      ExpErrorIyy1ComponentReasonCode_AS = orig.ExpErrorIyy1ComponentReasonCode_AS;
      ExpErrorIyy1ComponentReasonCode = orig.ExpErrorIyy1ComponentReasonCode;
      ExpErrorIyy1ComponentChecksum_AT = orig.ExpErrorIyy1ComponentChecksum_AT;
      ExpErrorIyy1ComponentChecksum_AS = orig.ExpErrorIyy1ComponentChecksum_AS;
      ExpErrorIyy1ComponentChecksum = orig.ExpErrorIyy1ComponentChecksum;
    }
    /// <summary>
    /// Static instance creator function
    /// </summary>
    
    public static CYY1S071_OA GetInstance(  )
    {
      if ( countFree == 0 )
      {
        return(new CYY1S071_OA());
      }
      else 
      {
        lock (freeArray)
        {
          if ( countFree == 0 )
          {
            return(new CYY1S071_OA());
          }
          else 
          {
            CYY1S071_OA result = freeArray[--countFree];
            freeArray[countFree] = null;
            result.Reset(  );
            return(result);
          }
        }
      }
    }
    /// <summary>
    /// Static free instance method
    /// </summary>
    
    public void FreeInstance(  )
    {
      lock (freeArray)
      {
        if ( countFree < freeArray.Length )
        {
          freeArray[countFree++] = this;
        }
      }
    }
    /// <summary>
    /// clone constructor
    /// </summary>
    
    public override Object Clone(  )
    {
      return(new CYY1S071_OA(this));
    }
    /// <summary>
    /// Resets all properties to the defaults.
    /// </summary>
    
    public void Reset(  )
    {
      ExpReferenceIyy1ServerDataServerDate_AT = null;
      ExpReferenceIyy1ServerDataServerDate_AS = ' ';
      ExpReferenceIyy1ServerDataServerDate = 00000000;
      ExpReferenceIyy1ServerDataServerTime_AT = null;
      ExpReferenceIyy1ServerDataServerTime_AS = ' ';
      ExpReferenceIyy1ServerDataServerTime = 00000000;
      ExpReferenceIyy1ServerDataReferenceId_AT = null;
      ExpReferenceIyy1ServerDataReferenceId_AS = ' ';
      ExpReferenceIyy1ServerDataReferenceId = "00000000000000000000";
      ExpIsc1AuthorizationInfoTokenId_AT = null;
      ExpIsc1AuthorizationInfoTokenId_AS = ' ';
      ExpIsc1AuthorizationInfoTokenId = "                                ";
      ExpIsc1AuthorizationInfoAuthorityInd_AT = null;
      ExpIsc1AuthorizationInfoAuthorityInd_AS = ' ';
      ExpIsc1AuthorizationInfoAuthorityInd = " ";
      ExpIsc1AuthorizationInfoAuthorityStatusR_AT = null;
      ExpIsc1AuthorizationInfoAuthorityStatusR_AS = ' ';
      ExpIsc1AuthorizationInfoAuthorityStatusR = " ";
      ExpIsc1AuthorizationInfoAuthorityStatusU_AT = null;
      ExpIsc1AuthorizationInfoAuthorityStatusU_AS = ' ';
      ExpIsc1AuthorizationInfoAuthorityStatusU = " ";
      ExpIsc1AuthorizationInfoAuthorityStatusD_AT = null;
      ExpIsc1AuthorizationInfoAuthorityStatusD_AS = ' ';
      ExpIsc1AuthorizationInfoAuthorityStatusD = " ";
      ExpIsc1AuthorizationInfoAuthorityStatusL_AT = null;
      ExpIsc1AuthorizationInfoAuthorityStatusL_AS = ' ';
      ExpIsc1AuthorizationInfoAuthorityStatusL = " ";
      ExpAllTypeTinstanceId_AT = null;
      ExpAllTypeTinstanceId_AS = ' ';
      ExpAllTypeTinstanceId = "00000000000000000000";
      ExpAllTypeTreferenceId_AT = null;
      ExpAllTypeTreferenceId_AS = ' ';
      ExpAllTypeTreferenceId = "00000000000000000000";
      ExpAllTypeTcreateUserId_AT = null;
      ExpAllTypeTcreateUserId_AS = ' ';
      ExpAllTypeTcreateUserId = "        ";
      ExpAllTypeTupdateUserId_AT = null;
      ExpAllTypeTupdateUserId_AS = ' ';
      ExpAllTypeTupdateUserId = "        ";
      ExpAllTypeTkeyAttrText_AT = null;
      ExpAllTypeTkeyAttrText_AS = ' ';
      ExpAllTypeTkeyAttrText = "    ";
      ExpAllTypeTsearchAttrText_AT = null;
      ExpAllTypeTsearchAttrText_AS = ' ';
      ExpAllTypeTsearchAttrText = "                    ";
      ExpAllTypeTotherAttrText_AT = null;
      ExpAllTypeTotherAttrText_AS = ' ';
      ExpAllTypeTotherAttrText = "  ";
      ExpAllTypeTotherAttrDate_AT = null;
      ExpAllTypeTotherAttrDate_AS = ' ';
      ExpAllTypeTotherAttrDate = 00000000;
      ExpAllTypeTotherAttrTime_AT = null;
      ExpAllTypeTotherAttrTime_AS = ' ';
      ExpAllTypeTotherAttrTime = 00000000;
      ExpAllTypeTotherAttrAmount_AT = null;
      ExpAllTypeTotherAttrAmount_AS = ' ';
      ExpAllTypeTotherAttrAmount = DecimalAttr.GetDefaultValue();
      ExpTsTypeTinstanceId_AT = null;
      ExpTsTypeTinstanceId_AS = ' ';
      ExpTsTypeTinstanceId = "00000000000000000000";
      ExpTsTypeTreferenceId_AT = null;
      ExpTsTypeTreferenceId_AS = ' ';
      ExpTsTypeTreferenceId = "00000000000000000000";
      ExpMsgIyy1ComponentSeverityCode_AT = null;
      ExpMsgIyy1ComponentSeverityCode_AS = ' ';
      ExpMsgIyy1ComponentSeverityCode = " ";
      ExpMsgIyy1ComponentMessageTx_AT = null;
      ExpMsgIyy1ComponentMessageTx_AS = ' ';
      ExpMsgIyy1ComponentMessageTx = "";
      ExpErrorIyy1ComponentSeverityCode_AT = null;
      ExpErrorIyy1ComponentSeverityCode_AS = ' ';
      ExpErrorIyy1ComponentSeverityCode = " ";
      ExpErrorIyy1ComponentRollbackIndicator_AT = null;
      ExpErrorIyy1ComponentRollbackIndicator_AS = ' ';
      ExpErrorIyy1ComponentRollbackIndicator = " ";
      ExpErrorIyy1ComponentOriginServid_AT = null;
      ExpErrorIyy1ComponentOriginServid_AS = ' ';
      ExpErrorIyy1ComponentOriginServid = 0.0;
      ExpErrorIyy1ComponentContextString_AT = null;
      ExpErrorIyy1ComponentContextString_AS = ' ';
      ExpErrorIyy1ComponentContextString = "";
      ExpErrorIyy1ComponentReturnCode_AT = null;
      ExpErrorIyy1ComponentReturnCode_AS = ' ';
      ExpErrorIyy1ComponentReturnCode = 0;
      ExpErrorIyy1ComponentReasonCode_AT = null;
      ExpErrorIyy1ComponentReasonCode_AS = ' ';
      ExpErrorIyy1ComponentReasonCode = 0;
      ExpErrorIyy1ComponentChecksum_AT = null;
      ExpErrorIyy1ComponentChecksum_AS = ' ';
      ExpErrorIyy1ComponentChecksum = "               ";
    }
    /// <summary>
    /// Gets the VDF array for the instance, initialized.
    /// </summary>
    
    public static VDF GetViewDefinition()
    {
      if ( localVdf == null )
      {
        VDFEntry [] vdfEntries = {
          new VDFEntry( (int)1,
          	"",
          	"ExpReferenceIyy1ServerData",
          	"Iyy1ServerData",
          	"ServerDate",
          	VDFDataType.Date,
          	(short)1,
          	(short)0,
          	8,
          	(short)0,
          	null ), 
          new VDFEntry( (int)2,
          	"",
          	"ExpReferenceIyy1ServerData",
          	"Iyy1ServerData",
          	"ServerTime",
          	VDFDataType.Time,
          	(short)1,
          	(short)0,
          	6,
          	(short)0,
          	null ), 
          new VDFEntry( (int)3,
          	"",
          	"ExpReferenceIyy1ServerData",
          	"Iyy1ServerData",
          	"ReferenceId",
          	VDFDataType.Timestamp,
          	(short)1,
          	(short)0,
          	20,
          	(short)0,
          	null ), 
          new VDFEntry( (int)4,
          	"",
          	"ExpIsc1AuthorizationInfo",
          	"Isc1AuthorizationInfo",
          	"TokenId",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	32,
          	(short)0,
          	null ), 
          new VDFEntry( (int)5,
          	"",
          	"ExpIsc1AuthorizationInfo",
          	"Isc1AuthorizationInfo",
          	"AuthorityInd",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)6,
          	"",
          	"ExpIsc1AuthorizationInfo",
          	"Isc1AuthorizationInfo",
          	"AuthorityStatusR",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)7,
          	"",
          	"ExpIsc1AuthorizationInfo",
          	"Isc1AuthorizationInfo",
          	"AuthorityStatusU",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)8,
          	"",
          	"ExpIsc1AuthorizationInfo",
          	"Isc1AuthorizationInfo",
          	"AuthorityStatusD",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)9,
          	"",
          	"ExpIsc1AuthorizationInfo",
          	"Isc1AuthorizationInfo",
          	"AuthorityStatusL",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)10,
          	"",
          	"ExpAllType",
          	"Type",
          	"TinstanceId",
          	VDFDataType.Timestamp,
          	(short)1,
          	(short)0,
          	20,
          	(short)0,
          	null ), 
          new VDFEntry( (int)11,
          	"",
          	"ExpAllType",
          	"Type",
          	"TreferenceId",
          	VDFDataType.Timestamp,
          	(short)1,
          	(short)0,
          	20,
          	(short)0,
          	null ), 
          new VDFEntry( (int)12,
          	"",
          	"ExpAllType",
          	"Type",
          	"TcreateUserId",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	8,
          	(short)0,
          	null ), 
          new VDFEntry( (int)13,
          	"",
          	"ExpAllType",
          	"Type",
          	"TupdateUserId",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	8,
          	(short)0,
          	null ), 
          new VDFEntry( (int)14,
          	"",
          	"ExpAllType",
          	"Type",
          	"TkeyAttrText",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	4,
          	(short)0,
          	null ), 
          new VDFEntry( (int)15,
          	"",
          	"ExpAllType",
          	"Type",
          	"TsearchAttrText",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	20,
          	(short)0,
          	null ), 
          new VDFEntry( (int)16,
          	"",
          	"ExpAllType",
          	"Type",
          	"TotherAttrText",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	2,
          	(short)0,
          	null ), 
          new VDFEntry( (int)17,
          	"",
          	"ExpAllType",
          	"Type",
          	"TotherAttrDate",
          	VDFDataType.Date,
          	(short)1,
          	(short)0,
          	8,
          	(short)0,
          	null ), 
          new VDFEntry( (int)18,
          	"",
          	"ExpAllType",
          	"Type",
          	"TotherAttrTime",
          	VDFDataType.Time,
          	(short)1,
          	(short)0,
          	6,
          	(short)0,
          	null ), 
          new VDFEntry( (int)19,
          	"",
          	"ExpAllType",
          	"Type",
          	"TotherAttrAmount",
          	VDFDataType.Fixed,
          	(short)1,
          	(short)0,
          	17,
          	(short)2,
          	null ), 
          new VDFEntry( (int)20,
          	"",
          	"ExpTsType",
          	"Type",
          	"TinstanceId",
          	VDFDataType.Timestamp,
          	(short)1,
          	(short)0,
          	20,
          	(short)0,
          	null ), 
          new VDFEntry( (int)21,
          	"",
          	"ExpTsType",
          	"Type",
          	"TreferenceId",
          	VDFDataType.Timestamp,
          	(short)1,
          	(short)0,
          	20,
          	(short)0,
          	null ), 
          new VDFEntry( (int)22,
          	"",
          	"ExpMsgIyy1Component",
          	"Iyy1Component",
          	"SeverityCode",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)23,
          	"",
          	"ExpMsgIyy1Component",
          	"Iyy1Component",
          	"MessageTx",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	512,
          	(short)0,
          	null ), 
          new VDFEntry( (int)24,
          	"",
          	"ExpErrorIyy1Component",
          	"Iyy1Component",
          	"SeverityCode",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)25,
          	"",
          	"ExpErrorIyy1Component",
          	"Iyy1Component",
          	"RollbackIndicator",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	1,
          	(short)0,
          	null ), 
          new VDFEntry( (int)26,
          	"",
          	"ExpErrorIyy1Component",
          	"Iyy1Component",
          	"OriginServid",
          	VDFDataType.Double,
          	(short)1,
          	(short)0,
          	15,
          	(short)0,
          	null ), 
          new VDFEntry( (int)27,
          	"",
          	"ExpErrorIyy1Component",
          	"Iyy1Component",
          	"ContextString",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	512,
          	(short)0,
          	null ), 
          new VDFEntry( (int)28,
          	"",
          	"ExpErrorIyy1Component",
          	"Iyy1Component",
          	"ReturnCode",
          	VDFDataType.Int,
          	(short)1,
          	(short)0,
          	8,
          	(short)0,
          	null ), 
          new VDFEntry( (int)29,
          	"",
          	"ExpErrorIyy1Component",
          	"Iyy1Component",
          	"ReasonCode",
          	VDFDataType.Int,
          	(short)1,
          	(short)0,
          	8,
          	(short)0,
          	null ), 
          new VDFEntry( (int)30,
          	"",
          	"ExpErrorIyy1Component",
          	"Iyy1Component",
          	"Checksum",
          	VDFDataType.String,
          	(short)1,
          	(short)0,
          	15,
          	(short)0,
          	null ), 
        };
        localVdf = new VDF(vdfEntries);
      }
      try {
        VDF result = (VDF)localVdf.Clone();
        result.InitViewData();
        return result;
      } catch( Exception e ) {
        throw new GenException(e.GetType().Name + " caught, Clone is not supported in VDF");;
        
      }
    }
    
    /// <summary>
    /// Sets the current state of the instance to the VDF version.
    /// </summary>
    public void SetFromVDF( VDF vdf )
    {
      // predicate view item
      if ( vdf.Entries[0].DataValue.Data != null )
      {
        _ExpReferenceIyy1ServerDataServerDate = (int)vdf.Entries[0].DataValue.Data;
      }
      else 
      {
        _ExpReferenceIyy1ServerDataServerDate = DateAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[1].DataValue.Data != null )
      {
        _ExpReferenceIyy1ServerDataServerTime = (int)vdf.Entries[1].DataValue.Data;
      }
      else 
      {
        _ExpReferenceIyy1ServerDataServerTime = TimeAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[2].DataValue.Data != null )
      {
        _ExpReferenceIyy1ServerDataReferenceId = (string)vdf.Entries[2].DataValue.Data;
      }
      else 
      {
        _ExpReferenceIyy1ServerDataReferenceId = TimestampAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[3].DataValue.Data != null )
      {
        _ExpIsc1AuthorizationInfoTokenId = (string)vdf.Entries[3].DataValue.Data;
      }
      else 
      {
        _ExpIsc1AuthorizationInfoTokenId = FixedStringAttr.GetDefaultValue(32);
      }
      // predicate view item
      if ( vdf.Entries[4].DataValue.Data != null )
      {
        _ExpIsc1AuthorizationInfoAuthorityInd = (string)vdf.Entries[4].DataValue.Data;
      }
      else 
      {
        _ExpIsc1AuthorizationInfoAuthorityInd = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[5].DataValue.Data != null )
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusR = (string)vdf.Entries[5].DataValue.Data;
      }
      else 
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusR = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[6].DataValue.Data != null )
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusU = (string)vdf.Entries[6].DataValue.Data;
      }
      else 
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusU = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[7].DataValue.Data != null )
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusD = (string)vdf.Entries[7].DataValue.Data;
      }
      else 
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusD = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[8].DataValue.Data != null )
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusL = (string)vdf.Entries[8].DataValue.Data;
      }
      else 
      {
        _ExpIsc1AuthorizationInfoAuthorityStatusL = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[9].DataValue.Data != null )
      {
        _ExpAllTypeTinstanceId = (string)vdf.Entries[9].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTinstanceId = TimestampAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[10].DataValue.Data != null )
      {
        _ExpAllTypeTreferenceId = (string)vdf.Entries[10].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTreferenceId = TimestampAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[11].DataValue.Data != null )
      {
        _ExpAllTypeTcreateUserId = (string)vdf.Entries[11].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTcreateUserId = FixedStringAttr.GetDefaultValue(8);
      }
      // predicate view item
      if ( vdf.Entries[12].DataValue.Data != null )
      {
        _ExpAllTypeTupdateUserId = (string)vdf.Entries[12].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTupdateUserId = FixedStringAttr.GetDefaultValue(8);
      }
      // predicate view item
      if ( vdf.Entries[13].DataValue.Data != null )
      {
        _ExpAllTypeTkeyAttrText = (string)vdf.Entries[13].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTkeyAttrText = FixedStringAttr.GetDefaultValue(4);
      }
      // predicate view item
      if ( vdf.Entries[14].DataValue.Data != null )
      {
        _ExpAllTypeTsearchAttrText = (string)vdf.Entries[14].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTsearchAttrText = FixedStringAttr.GetDefaultValue(20);
      }
      // predicate view item
      if ( vdf.Entries[15].DataValue.Data != null )
      {
        _ExpAllTypeTotherAttrText = (string)vdf.Entries[15].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTotherAttrText = FixedStringAttr.GetDefaultValue(2);
      }
      // predicate view item
      if ( vdf.Entries[16].DataValue.Data != null )
      {
        _ExpAllTypeTotherAttrDate = (int)vdf.Entries[16].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTotherAttrDate = DateAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[17].DataValue.Data != null )
      {
        _ExpAllTypeTotherAttrTime = (int)vdf.Entries[17].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTotherAttrTime = TimeAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[18].DataValue.Data != null )
      {
        _ExpAllTypeTotherAttrAmount = (decimal)vdf.Entries[18].DataValue.Data;
      }
      else 
      {
        _ExpAllTypeTotherAttrAmount = DecimalAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[19].DataValue.Data != null )
      {
        _ExpTsTypeTinstanceId = (string)vdf.Entries[19].DataValue.Data;
      }
      else 
      {
        _ExpTsTypeTinstanceId = TimestampAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[20].DataValue.Data != null )
      {
        _ExpTsTypeTreferenceId = (string)vdf.Entries[20].DataValue.Data;
      }
      else 
      {
        _ExpTsTypeTreferenceId = TimestampAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[21].DataValue.Data != null )
      {
        _ExpMsgIyy1ComponentSeverityCode = (string)vdf.Entries[21].DataValue.Data;
      }
      else 
      {
        _ExpMsgIyy1ComponentSeverityCode = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[22].DataValue.Data != null )
      {
        _ExpMsgIyy1ComponentMessageTx = (string)vdf.Entries[22].DataValue.Data;
      }
      else 
      {
        _ExpMsgIyy1ComponentMessageTx = StringAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[23].DataValue.Data != null )
      {
        _ExpErrorIyy1ComponentSeverityCode = (string)vdf.Entries[23].DataValue.Data;
      }
      else 
      {
        _ExpErrorIyy1ComponentSeverityCode = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[24].DataValue.Data != null )
      {
        _ExpErrorIyy1ComponentRollbackIndicator = (string)vdf.Entries[24].DataValue.Data;
      }
      else 
      {
        _ExpErrorIyy1ComponentRollbackIndicator = FixedStringAttr.GetDefaultValue(1);
      }
      // predicate view item
      if ( vdf.Entries[25].DataValue.Data != null )
      {
        _ExpErrorIyy1ComponentOriginServid = (double)vdf.Entries[25].DataValue.Data;
      }
      else 
      {
        _ExpErrorIyy1ComponentOriginServid = DoubleAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[26].DataValue.Data != null )
      {
        _ExpErrorIyy1ComponentContextString = (string)vdf.Entries[26].DataValue.Data;
      }
      else 
      {
        _ExpErrorIyy1ComponentContextString = StringAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[27].DataValue.Data != null )
      {
        _ExpErrorIyy1ComponentReturnCode = (int)vdf.Entries[27].DataValue.Data;
      }
      else 
      {
        _ExpErrorIyy1ComponentReturnCode = IntAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[28].DataValue.Data != null )
      {
        _ExpErrorIyy1ComponentReasonCode = (int)vdf.Entries[28].DataValue.Data;
      }
      else 
      {
        _ExpErrorIyy1ComponentReasonCode = IntAttr.GetDefaultValue();
      }
      // predicate view item
      if ( vdf.Entries[29].DataValue.Data != null )
      {
        _ExpErrorIyy1ComponentChecksum = (string)vdf.Entries[29].DataValue.Data;
      }
      else 
      {
        _ExpErrorIyy1ComponentChecksum = FixedStringAttr.GetDefaultValue(15);
      }
    }
    
    /// <summary>
    /// Gets the VDF version of the current state of the instance.
    /// </summary>
    public VDF GetVDF(  )
    {
      VDF vdf = GetViewDefinition(  );
      // predicate view item
      vdf.Entries[0].DataValue.Data = _ExpReferenceIyy1ServerDataServerDate;
      // predicate view item
      vdf.Entries[1].DataValue.Data = _ExpReferenceIyy1ServerDataServerTime;
      // predicate view item
      vdf.Entries[2].DataValue.Data = _ExpReferenceIyy1ServerDataReferenceId;
      // predicate view item
      vdf.Entries[3].DataValue.Data = _ExpIsc1AuthorizationInfoTokenId;
      // predicate view item
      vdf.Entries[4].DataValue.Data = _ExpIsc1AuthorizationInfoAuthorityInd;
      // predicate view item
      vdf.Entries[5].DataValue.Data = _ExpIsc1AuthorizationInfoAuthorityStatusR;
      // predicate view item
      vdf.Entries[6].DataValue.Data = _ExpIsc1AuthorizationInfoAuthorityStatusU;
      // predicate view item
      vdf.Entries[7].DataValue.Data = _ExpIsc1AuthorizationInfoAuthorityStatusD;
      // predicate view item
      vdf.Entries[8].DataValue.Data = _ExpIsc1AuthorizationInfoAuthorityStatusL;
      // predicate view item
      vdf.Entries[9].DataValue.Data = _ExpAllTypeTinstanceId;
      // predicate view item
      vdf.Entries[10].DataValue.Data = _ExpAllTypeTreferenceId;
      // predicate view item
      vdf.Entries[11].DataValue.Data = _ExpAllTypeTcreateUserId;
      // predicate view item
      vdf.Entries[12].DataValue.Data = _ExpAllTypeTupdateUserId;
      // predicate view item
      vdf.Entries[13].DataValue.Data = _ExpAllTypeTkeyAttrText;
      // predicate view item
      vdf.Entries[14].DataValue.Data = _ExpAllTypeTsearchAttrText;
      // predicate view item
      vdf.Entries[15].DataValue.Data = _ExpAllTypeTotherAttrText;
      // predicate view item
      vdf.Entries[16].DataValue.Data = _ExpAllTypeTotherAttrDate;
      // predicate view item
      vdf.Entries[17].DataValue.Data = _ExpAllTypeTotherAttrTime;
      // predicate view item
      vdf.Entries[18].DataValue.Data = _ExpAllTypeTotherAttrAmount;
      // predicate view item
      vdf.Entries[19].DataValue.Data = _ExpTsTypeTinstanceId;
      // predicate view item
      vdf.Entries[20].DataValue.Data = _ExpTsTypeTreferenceId;
      // predicate view item
      vdf.Entries[21].DataValue.Data = _ExpMsgIyy1ComponentSeverityCode;
      // predicate view item
      vdf.Entries[22].DataValue.Data = _ExpMsgIyy1ComponentMessageTx;
      // predicate view item
      vdf.Entries[23].DataValue.Data = _ExpErrorIyy1ComponentSeverityCode;
      // predicate view item
      vdf.Entries[24].DataValue.Data = _ExpErrorIyy1ComponentRollbackIndicator;
      // predicate view item
      vdf.Entries[25].DataValue.Data = _ExpErrorIyy1ComponentOriginServid;
      // predicate view item
      vdf.Entries[26].DataValue.Data = _ExpErrorIyy1ComponentContextString;
      // predicate view item
      vdf.Entries[27].DataValue.Data = _ExpErrorIyy1ComponentReturnCode;
      // predicate view item
      vdf.Entries[28].DataValue.Data = _ExpErrorIyy1ComponentReasonCode;
      // predicate view item
      vdf.Entries[29].DataValue.Data = _ExpErrorIyy1ComponentChecksum;
      return(vdf);
    }
    
    /// <summary>
    /// Sets the current instance based on the passed view.
    /// </summary>
    public void CopyFrom( IExportView orig )
    {
      this.CopyFrom((CYY1S071_OA) orig);
    }
    
    /// <summary>
    /// Sets the current instance based on the passed view.
    /// </summary>
    public void CopyFrom( CYY1S071_OA orig )
    {
      ExpReferenceIyy1ServerDataServerDate_AT = orig.ExpReferenceIyy1ServerDataServerDate_AT;
      ExpReferenceIyy1ServerDataServerDate_AS = orig.ExpReferenceIyy1ServerDataServerDate_AS;
      ExpReferenceIyy1ServerDataServerDate = orig.ExpReferenceIyy1ServerDataServerDate;
      ExpReferenceIyy1ServerDataServerTime_AT = orig.ExpReferenceIyy1ServerDataServerTime_AT;
      ExpReferenceIyy1ServerDataServerTime_AS = orig.ExpReferenceIyy1ServerDataServerTime_AS;
      ExpReferenceIyy1ServerDataServerTime = orig.ExpReferenceIyy1ServerDataServerTime;
      ExpReferenceIyy1ServerDataReferenceId_AT = orig.ExpReferenceIyy1ServerDataReferenceId_AT;
      ExpReferenceIyy1ServerDataReferenceId_AS = orig.ExpReferenceIyy1ServerDataReferenceId_AS;
      ExpReferenceIyy1ServerDataReferenceId = orig.ExpReferenceIyy1ServerDataReferenceId;
      ExpIsc1AuthorizationInfoTokenId_AT = orig.ExpIsc1AuthorizationInfoTokenId_AT;
      ExpIsc1AuthorizationInfoTokenId_AS = orig.ExpIsc1AuthorizationInfoTokenId_AS;
      ExpIsc1AuthorizationInfoTokenId = orig.ExpIsc1AuthorizationInfoTokenId;
      ExpIsc1AuthorizationInfoAuthorityInd_AT = orig.ExpIsc1AuthorizationInfoAuthorityInd_AT;
      ExpIsc1AuthorizationInfoAuthorityInd_AS = orig.ExpIsc1AuthorizationInfoAuthorityInd_AS;
      ExpIsc1AuthorizationInfoAuthorityInd = orig.ExpIsc1AuthorizationInfoAuthorityInd;
      ExpIsc1AuthorizationInfoAuthorityStatusR_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusR_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusR_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusR_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusR = orig.ExpIsc1AuthorizationInfoAuthorityStatusR;
      ExpIsc1AuthorizationInfoAuthorityStatusU_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusU_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusU_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusU_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusU = orig.ExpIsc1AuthorizationInfoAuthorityStatusU;
      ExpIsc1AuthorizationInfoAuthorityStatusD_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusD_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusD_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusD_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusD = orig.ExpIsc1AuthorizationInfoAuthorityStatusD;
      ExpIsc1AuthorizationInfoAuthorityStatusL_AT = orig.ExpIsc1AuthorizationInfoAuthorityStatusL_AT;
      ExpIsc1AuthorizationInfoAuthorityStatusL_AS = orig.ExpIsc1AuthorizationInfoAuthorityStatusL_AS;
      ExpIsc1AuthorizationInfoAuthorityStatusL = orig.ExpIsc1AuthorizationInfoAuthorityStatusL;
      ExpAllTypeTinstanceId_AT = orig.ExpAllTypeTinstanceId_AT;
      ExpAllTypeTinstanceId_AS = orig.ExpAllTypeTinstanceId_AS;
      ExpAllTypeTinstanceId = orig.ExpAllTypeTinstanceId;
      ExpAllTypeTreferenceId_AT = orig.ExpAllTypeTreferenceId_AT;
      ExpAllTypeTreferenceId_AS = orig.ExpAllTypeTreferenceId_AS;
      ExpAllTypeTreferenceId = orig.ExpAllTypeTreferenceId;
      ExpAllTypeTcreateUserId_AT = orig.ExpAllTypeTcreateUserId_AT;
      ExpAllTypeTcreateUserId_AS = orig.ExpAllTypeTcreateUserId_AS;
      ExpAllTypeTcreateUserId = orig.ExpAllTypeTcreateUserId;
      ExpAllTypeTupdateUserId_AT = orig.ExpAllTypeTupdateUserId_AT;
      ExpAllTypeTupdateUserId_AS = orig.ExpAllTypeTupdateUserId_AS;
      ExpAllTypeTupdateUserId = orig.ExpAllTypeTupdateUserId;
      ExpAllTypeTkeyAttrText_AT = orig.ExpAllTypeTkeyAttrText_AT;
      ExpAllTypeTkeyAttrText_AS = orig.ExpAllTypeTkeyAttrText_AS;
      ExpAllTypeTkeyAttrText = orig.ExpAllTypeTkeyAttrText;
      ExpAllTypeTsearchAttrText_AT = orig.ExpAllTypeTsearchAttrText_AT;
      ExpAllTypeTsearchAttrText_AS = orig.ExpAllTypeTsearchAttrText_AS;
      ExpAllTypeTsearchAttrText = orig.ExpAllTypeTsearchAttrText;
      ExpAllTypeTotherAttrText_AT = orig.ExpAllTypeTotherAttrText_AT;
      ExpAllTypeTotherAttrText_AS = orig.ExpAllTypeTotherAttrText_AS;
      ExpAllTypeTotherAttrText = orig.ExpAllTypeTotherAttrText;
      ExpAllTypeTotherAttrDate_AT = orig.ExpAllTypeTotherAttrDate_AT;
      ExpAllTypeTotherAttrDate_AS = orig.ExpAllTypeTotherAttrDate_AS;
      ExpAllTypeTotherAttrDate = orig.ExpAllTypeTotherAttrDate;
      ExpAllTypeTotherAttrTime_AT = orig.ExpAllTypeTotherAttrTime_AT;
      ExpAllTypeTotherAttrTime_AS = orig.ExpAllTypeTotherAttrTime_AS;
      ExpAllTypeTotherAttrTime = orig.ExpAllTypeTotherAttrTime;
      ExpAllTypeTotherAttrAmount_AT = orig.ExpAllTypeTotherAttrAmount_AT;
      ExpAllTypeTotherAttrAmount_AS = orig.ExpAllTypeTotherAttrAmount_AS;
      ExpAllTypeTotherAttrAmount = orig.ExpAllTypeTotherAttrAmount;
      ExpTsTypeTinstanceId_AT = orig.ExpTsTypeTinstanceId_AT;
      ExpTsTypeTinstanceId_AS = orig.ExpTsTypeTinstanceId_AS;
      ExpTsTypeTinstanceId = orig.ExpTsTypeTinstanceId;
      ExpTsTypeTreferenceId_AT = orig.ExpTsTypeTreferenceId_AT;
      ExpTsTypeTreferenceId_AS = orig.ExpTsTypeTreferenceId_AS;
      ExpTsTypeTreferenceId = orig.ExpTsTypeTreferenceId;
      ExpMsgIyy1ComponentSeverityCode_AT = orig.ExpMsgIyy1ComponentSeverityCode_AT;
      ExpMsgIyy1ComponentSeverityCode_AS = orig.ExpMsgIyy1ComponentSeverityCode_AS;
      ExpMsgIyy1ComponentSeverityCode = orig.ExpMsgIyy1ComponentSeverityCode;
      ExpMsgIyy1ComponentMessageTx_AT = orig.ExpMsgIyy1ComponentMessageTx_AT;
      ExpMsgIyy1ComponentMessageTx_AS = orig.ExpMsgIyy1ComponentMessageTx_AS;
      ExpMsgIyy1ComponentMessageTx = orig.ExpMsgIyy1ComponentMessageTx;
      ExpErrorIyy1ComponentSeverityCode_AT = orig.ExpErrorIyy1ComponentSeverityCode_AT;
      ExpErrorIyy1ComponentSeverityCode_AS = orig.ExpErrorIyy1ComponentSeverityCode_AS;
      ExpErrorIyy1ComponentSeverityCode = orig.ExpErrorIyy1ComponentSeverityCode;
      ExpErrorIyy1ComponentRollbackIndicator_AT = orig.ExpErrorIyy1ComponentRollbackIndicator_AT;
      ExpErrorIyy1ComponentRollbackIndicator_AS = orig.ExpErrorIyy1ComponentRollbackIndicator_AS;
      ExpErrorIyy1ComponentRollbackIndicator = orig.ExpErrorIyy1ComponentRollbackIndicator;
      ExpErrorIyy1ComponentOriginServid_AT = orig.ExpErrorIyy1ComponentOriginServid_AT;
      ExpErrorIyy1ComponentOriginServid_AS = orig.ExpErrorIyy1ComponentOriginServid_AS;
      ExpErrorIyy1ComponentOriginServid = orig.ExpErrorIyy1ComponentOriginServid;
      ExpErrorIyy1ComponentContextString_AT = orig.ExpErrorIyy1ComponentContextString_AT;
      ExpErrorIyy1ComponentContextString_AS = orig.ExpErrorIyy1ComponentContextString_AS;
      ExpErrorIyy1ComponentContextString = orig.ExpErrorIyy1ComponentContextString;
      ExpErrorIyy1ComponentReturnCode_AT = orig.ExpErrorIyy1ComponentReturnCode_AT;
      ExpErrorIyy1ComponentReturnCode_AS = orig.ExpErrorIyy1ComponentReturnCode_AS;
      ExpErrorIyy1ComponentReturnCode = orig.ExpErrorIyy1ComponentReturnCode;
      ExpErrorIyy1ComponentReasonCode_AT = orig.ExpErrorIyy1ComponentReasonCode_AT;
      ExpErrorIyy1ComponentReasonCode_AS = orig.ExpErrorIyy1ComponentReasonCode_AS;
      ExpErrorIyy1ComponentReasonCode = orig.ExpErrorIyy1ComponentReasonCode;
      ExpErrorIyy1ComponentChecksum_AT = orig.ExpErrorIyy1ComponentChecksum_AT;
      ExpErrorIyy1ComponentChecksum_AS = orig.ExpErrorIyy1ComponentChecksum_AS;
      ExpErrorIyy1ComponentChecksum = orig.ExpErrorIyy1ComponentChecksum;
    }
  }
}
