// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2024 CA Technologies. All rights reserved.
//
//    Name: MYY10111_LA                      Date: 2024/01/09
//    User: AliAl                            Time: 13:42:00
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// using Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
using System;
using com.ca.gen.vwrt;
using com.ca.gen.vwrt.types;
using com.ca.gen.vwrt.vdf;
using com.ca.gen.csu.exception;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF LOCAL VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
namespace GEN.ORT.YYY
{
  /// <summary>
  /// Internal data view storage for: MYY10111_LA
  /// </summary>
  [Serializable]
  public class MYY10111_LA : ViewBase, ILocalView
  {
    private static MYY10111_LA[] freeArray = new MYY10111_LA[30];
    private static int countFree = 0;
    
    // Entity View: LOC_IMP
    //        Type: PARENT
    /// <summary>
    /// Internal storage for attribute missing flag for: LocImpParentPkeyAttrText
    /// </summary>
    private char _LocImpParentPkeyAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: LocImpParentPkeyAttrText
    /// </summary>
    public char LocImpParentPkeyAttrText_AS {
      get {
        return(_LocImpParentPkeyAttrText_AS);
      }
      set {
        _LocImpParentPkeyAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: LocImpParentPkeyAttrText
    /// Domain: Text
    /// Length: 5
    /// Varying Length: N
    /// </summary>
    private string _LocImpParentPkeyAttrText;
    /// <summary>
    /// Attribute for: LocImpParentPkeyAttrText
    /// </summary>
    public string LocImpParentPkeyAttrText {
      get {
        return(_LocImpParentPkeyAttrText);
      }
      set {
        _LocImpParentPkeyAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: LocImpParentPsearchAttrText
    /// </summary>
    private char _LocImpParentPsearchAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: LocImpParentPsearchAttrText
    /// </summary>
    public char LocImpParentPsearchAttrText_AS {
      get {
        return(_LocImpParentPsearchAttrText_AS);
      }
      set {
        _LocImpParentPsearchAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: LocImpParentPsearchAttrText
    /// Domain: Text
    /// Length: 25
    /// Varying Length: N
    /// </summary>
    private string _LocImpParentPsearchAttrText;
    /// <summary>
    /// Attribute for: LocImpParentPsearchAttrText
    /// </summary>
    public string LocImpParentPsearchAttrText {
      get {
        return(_LocImpParentPsearchAttrText);
      }
      set {
        _LocImpParentPsearchAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: LocImpParentPotherAttrText
    /// </summary>
    private char _LocImpParentPotherAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: LocImpParentPotherAttrText
    /// </summary>
    public char LocImpParentPotherAttrText_AS {
      get {
        return(_LocImpParentPotherAttrText_AS);
      }
      set {
        _LocImpParentPotherAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: LocImpParentPotherAttrText
    /// Domain: Text
    /// Length: 25
    /// Varying Length: N
    /// </summary>
    private string _LocImpParentPotherAttrText;
    /// <summary>
    /// Attribute for: LocImpParentPotherAttrText
    /// </summary>
    public string LocImpParentPotherAttrText {
      get {
        return(_LocImpParentPotherAttrText);
      }
      set {
        _LocImpParentPotherAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: LocImpParentPtypeTkeyAttrText
    /// </summary>
    private char _LocImpParentPtypeTkeyAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: LocImpParentPtypeTkeyAttrText
    /// </summary>
    public char LocImpParentPtypeTkeyAttrText_AS {
      get {
        return(_LocImpParentPtypeTkeyAttrText_AS);
      }
      set {
        _LocImpParentPtypeTkeyAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: LocImpParentPtypeTkeyAttrText
    /// Domain: Text
    /// Length: 4
    /// Varying Length: N
    /// </summary>
    private string _LocImpParentPtypeTkeyAttrText;
    /// <summary>
    /// Attribute for: LocImpParentPtypeTkeyAttrText
    /// </summary>
    public string LocImpParentPtypeTkeyAttrText {
      get {
        return(_LocImpParentPtypeTkeyAttrText);
      }
      set {
        _LocImpParentPtypeTkeyAttrText = value;
      }
    }
    // Entity View: LOC_EXP
    //        Type: PARENT
    /// <summary>
    /// Internal storage for attribute missing flag for: LocExpParentPinstanceId
    /// </summary>
    private char _LocExpParentPinstanceId_AS;
    /// <summary>
    /// Attribute missing flag for: LocExpParentPinstanceId
    /// </summary>
    public char LocExpParentPinstanceId_AS {
      get {
        return(_LocExpParentPinstanceId_AS);
      }
      set {
        _LocExpParentPinstanceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: LocExpParentPinstanceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _LocExpParentPinstanceId;
    /// <summary>
    /// Attribute for: LocExpParentPinstanceId
    /// </summary>
    public string LocExpParentPinstanceId {
      get {
        return(_LocExpParentPinstanceId);
      }
      set {
        _LocExpParentPinstanceId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: LocExpParentPreferenceId
    /// </summary>
    private char _LocExpParentPreferenceId_AS;
    /// <summary>
    /// Attribute missing flag for: LocExpParentPreferenceId
    /// </summary>
    public char LocExpParentPreferenceId_AS {
      get {
        return(_LocExpParentPreferenceId_AS);
      }
      set {
        _LocExpParentPreferenceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: LocExpParentPreferenceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _LocExpParentPreferenceId;
    /// <summary>
    /// Attribute for: LocExpParentPreferenceId
    /// </summary>
    public string LocExpParentPreferenceId {
      get {
        return(_LocExpParentPreferenceId);
      }
      set {
        _LocExpParentPreferenceId = value;
      }
    }
    /// <summary>
    /// Default Constructor
    /// </summary>
    
    public MYY10111_LA(  )
    {
      Reset(  );
    }
    /// <summary>
    /// Copy Constructor
    /// </summary>
    
    public MYY10111_LA( MYY10111_LA orig )
    {
      LocImpParentPkeyAttrText_AS = orig.LocImpParentPkeyAttrText_AS;
      LocImpParentPkeyAttrText = orig.LocImpParentPkeyAttrText;
      LocImpParentPsearchAttrText_AS = orig.LocImpParentPsearchAttrText_AS;
      LocImpParentPsearchAttrText = orig.LocImpParentPsearchAttrText;
      LocImpParentPotherAttrText_AS = orig.LocImpParentPotherAttrText_AS;
      LocImpParentPotherAttrText = orig.LocImpParentPotherAttrText;
      LocImpParentPtypeTkeyAttrText_AS = orig.LocImpParentPtypeTkeyAttrText_AS;
      LocImpParentPtypeTkeyAttrText = orig.LocImpParentPtypeTkeyAttrText;
      LocExpParentPinstanceId_AS = orig.LocExpParentPinstanceId_AS;
      LocExpParentPinstanceId = orig.LocExpParentPinstanceId;
      LocExpParentPreferenceId_AS = orig.LocExpParentPreferenceId_AS;
      LocExpParentPreferenceId = orig.LocExpParentPreferenceId;
    }
    /// <summary>
    /// Static instance creator function
    /// </summary>
    
    public static MYY10111_LA GetInstance(  )
    {
      if ( countFree == 0 )
      {
        return(new MYY10111_LA());
      }
      else 
      {
        lock (freeArray)
        {
          if ( countFree == 0 )
          {
            return(new MYY10111_LA());
          }
          else 
          {
            MYY10111_LA result = freeArray[--countFree];
            freeArray[countFree] = null;
            result.Reset(  );
            return(result);
          }
        }
      }
    }
    /// <summary>
    /// Static free instance method
    /// </summary>
    
    public void FreeInstance(  )
    {
      lock (freeArray)
      {
        if ( countFree < freeArray.Length )
        {
          freeArray[countFree++] = this;
        }
      }
    }
    /// <summary>
    /// clone constructor
    /// </summary>
    
    public override Object Clone(  )
    {
      return(new MYY10111_LA(this));
    }
    /// <summary>
    /// Resets all properties to the defaults.
    /// </summary>
    
    public void Reset(  )
    {
      LocImpParentPkeyAttrText_AS = ' ';
      LocImpParentPkeyAttrText = "     ";
      LocImpParentPsearchAttrText_AS = ' ';
      LocImpParentPsearchAttrText = "                         ";
      LocImpParentPotherAttrText_AS = ' ';
      LocImpParentPotherAttrText = "                         ";
      LocImpParentPtypeTkeyAttrText_AS = ' ';
      LocImpParentPtypeTkeyAttrText = "    ";
      LocExpParentPinstanceId_AS = ' ';
      LocExpParentPinstanceId = "00000000000000000000";
      LocExpParentPreferenceId_AS = ' ';
      LocExpParentPreferenceId = "00000000000000000000";
    }
  }
}
