// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2024 CA Technologies. All rights reserved.
//
//    Name: MYY10121_OA                      Date: 2024/01/09
//    User: AliAl                            Time: 13:42:01
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// using Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
using System;
using com.ca.gen.vwrt;
using com.ca.gen.vwrt.types;
using com.ca.gen.vwrt.vdf;
using com.ca.gen.csu.exception;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF EXPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
namespace GEN.ORT.YYY
{
  /// <summary>
  /// Internal data view storage for: MYY10121_OA
  /// </summary>
  [Serializable]
  public class MYY10121_OA : ViewBase, IExportView
  {
    private static MYY10121_OA[] freeArray = new MYY10121_OA[30];
    private static int countFree = 0;
    
    // Entity View: EXP
    //        Type: IYY1_PARENT
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPinstanceId
    /// </summary>
    private char _ExpIyy1ParentPinstanceId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPinstanceId
    /// </summary>
    public char ExpIyy1ParentPinstanceId_AS {
      get {
        return(_ExpIyy1ParentPinstanceId_AS);
      }
      set {
        _ExpIyy1ParentPinstanceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPinstanceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ExpIyy1ParentPinstanceId;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPinstanceId
    /// </summary>
    public string ExpIyy1ParentPinstanceId {
      get {
        return(_ExpIyy1ParentPinstanceId);
      }
      set {
        _ExpIyy1ParentPinstanceId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPreferenceId
    /// </summary>
    private char _ExpIyy1ParentPreferenceId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPreferenceId
    /// </summary>
    public char ExpIyy1ParentPreferenceId_AS {
      get {
        return(_ExpIyy1ParentPreferenceId_AS);
      }
      set {
        _ExpIyy1ParentPreferenceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPreferenceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ExpIyy1ParentPreferenceId;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPreferenceId
    /// </summary>
    public string ExpIyy1ParentPreferenceId {
      get {
        return(_ExpIyy1ParentPreferenceId);
      }
      set {
        _ExpIyy1ParentPreferenceId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPcreateUserId
    /// </summary>
    private char _ExpIyy1ParentPcreateUserId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPcreateUserId
    /// </summary>
    public char ExpIyy1ParentPcreateUserId_AS {
      get {
        return(_ExpIyy1ParentPcreateUserId_AS);
      }
      set {
        _ExpIyy1ParentPcreateUserId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPcreateUserId
    /// Domain: Text
    /// Length: 8
    /// Varying Length: N
    /// </summary>
    private string _ExpIyy1ParentPcreateUserId;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPcreateUserId
    /// </summary>
    public string ExpIyy1ParentPcreateUserId {
      get {
        return(_ExpIyy1ParentPcreateUserId);
      }
      set {
        _ExpIyy1ParentPcreateUserId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPupdateUserId
    /// </summary>
    private char _ExpIyy1ParentPupdateUserId_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPupdateUserId
    /// </summary>
    public char ExpIyy1ParentPupdateUserId_AS {
      get {
        return(_ExpIyy1ParentPupdateUserId_AS);
      }
      set {
        _ExpIyy1ParentPupdateUserId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPupdateUserId
    /// Domain: Text
    /// Length: 8
    /// Varying Length: N
    /// </summary>
    private string _ExpIyy1ParentPupdateUserId;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPupdateUserId
    /// </summary>
    public string ExpIyy1ParentPupdateUserId {
      get {
        return(_ExpIyy1ParentPupdateUserId);
      }
      set {
        _ExpIyy1ParentPupdateUserId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPkeyAttrText
    /// </summary>
    private char _ExpIyy1ParentPkeyAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPkeyAttrText
    /// </summary>
    public char ExpIyy1ParentPkeyAttrText_AS {
      get {
        return(_ExpIyy1ParentPkeyAttrText_AS);
      }
      set {
        _ExpIyy1ParentPkeyAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPkeyAttrText
    /// Domain: Text
    /// Length: 5
    /// Varying Length: N
    /// </summary>
    private string _ExpIyy1ParentPkeyAttrText;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPkeyAttrText
    /// </summary>
    public string ExpIyy1ParentPkeyAttrText {
      get {
        return(_ExpIyy1ParentPkeyAttrText);
      }
      set {
        _ExpIyy1ParentPkeyAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPsearchAttrText
    /// </summary>
    private char _ExpIyy1ParentPsearchAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPsearchAttrText
    /// </summary>
    public char ExpIyy1ParentPsearchAttrText_AS {
      get {
        return(_ExpIyy1ParentPsearchAttrText_AS);
      }
      set {
        _ExpIyy1ParentPsearchAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPsearchAttrText
    /// Domain: Text
    /// Length: 25
    /// Varying Length: N
    /// </summary>
    private string _ExpIyy1ParentPsearchAttrText;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPsearchAttrText
    /// </summary>
    public string ExpIyy1ParentPsearchAttrText {
      get {
        return(_ExpIyy1ParentPsearchAttrText);
      }
      set {
        _ExpIyy1ParentPsearchAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPotherAttrText
    /// </summary>
    private char _ExpIyy1ParentPotherAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPotherAttrText
    /// </summary>
    public char ExpIyy1ParentPotherAttrText_AS {
      get {
        return(_ExpIyy1ParentPotherAttrText_AS);
      }
      set {
        _ExpIyy1ParentPotherAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPotherAttrText
    /// Domain: Text
    /// Length: 25
    /// Varying Length: N
    /// </summary>
    private string _ExpIyy1ParentPotherAttrText;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPotherAttrText
    /// </summary>
    public string ExpIyy1ParentPotherAttrText {
      get {
        return(_ExpIyy1ParentPotherAttrText);
      }
      set {
        _ExpIyy1ParentPotherAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpIyy1ParentPtypeTkeyAttrText
    /// </summary>
    private char _ExpIyy1ParentPtypeTkeyAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ExpIyy1ParentPtypeTkeyAttrText
    /// </summary>
    public char ExpIyy1ParentPtypeTkeyAttrText_AS {
      get {
        return(_ExpIyy1ParentPtypeTkeyAttrText_AS);
      }
      set {
        _ExpIyy1ParentPtypeTkeyAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpIyy1ParentPtypeTkeyAttrText
    /// Domain: Text
    /// Length: 4
    /// Varying Length: N
    /// </summary>
    private string _ExpIyy1ParentPtypeTkeyAttrText;
    /// <summary>
    /// Attribute for: ExpIyy1ParentPtypeTkeyAttrText
    /// </summary>
    public string ExpIyy1ParentPtypeTkeyAttrText {
      get {
        return(_ExpIyy1ParentPtypeTkeyAttrText);
      }
      set {
        _ExpIyy1ParentPtypeTkeyAttrText = value;
      }
    }
    // Entity View: EXP_ERROR
    //        Type: IYY1_COMPONENT
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    private char _ExpErrorIyy1ComponentSeverityCode_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    public char ExpErrorIyy1ComponentSeverityCode_AS {
      get {
        return(_ExpErrorIyy1ComponentSeverityCode_AS);
      }
      set {
        _ExpErrorIyy1ComponentSeverityCode_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentSeverityCode
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpErrorIyy1ComponentSeverityCode;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentSeverityCode
    /// </summary>
    public string ExpErrorIyy1ComponentSeverityCode {
      get {
        return(_ExpErrorIyy1ComponentSeverityCode);
      }
      set {
        _ExpErrorIyy1ComponentSeverityCode = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    private char _ExpErrorIyy1ComponentRollbackIndicator_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    public char ExpErrorIyy1ComponentRollbackIndicator_AS {
      get {
        return(_ExpErrorIyy1ComponentRollbackIndicator_AS);
      }
      set {
        _ExpErrorIyy1ComponentRollbackIndicator_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentRollbackIndicator
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _ExpErrorIyy1ComponentRollbackIndicator;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentRollbackIndicator
    /// </summary>
    public string ExpErrorIyy1ComponentRollbackIndicator {
      get {
        return(_ExpErrorIyy1ComponentRollbackIndicator);
      }
      set {
        _ExpErrorIyy1ComponentRollbackIndicator = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    private char _ExpErrorIyy1ComponentOriginServid_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    public char ExpErrorIyy1ComponentOriginServid_AS {
      get {
        return(_ExpErrorIyy1ComponentOriginServid_AS);
      }
      set {
        _ExpErrorIyy1ComponentOriginServid_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentOriginServid
    /// Domain: Number
    /// Length: 15
    /// Decimal Places: 0
    /// Decimal Precision: N
    /// </summary>
    private double _ExpErrorIyy1ComponentOriginServid;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentOriginServid
    /// </summary>
    public double ExpErrorIyy1ComponentOriginServid {
      get {
        return(_ExpErrorIyy1ComponentOriginServid);
      }
      set {
        _ExpErrorIyy1ComponentOriginServid = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentContextString
    /// </summary>
    private char _ExpErrorIyy1ComponentContextString_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentContextString
    /// </summary>
    public char ExpErrorIyy1ComponentContextString_AS {
      get {
        return(_ExpErrorIyy1ComponentContextString_AS);
      }
      set {
        _ExpErrorIyy1ComponentContextString_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentContextString
    /// Domain: Text
    /// Length: 512
    /// Varying Length: Y
    /// </summary>
    private string _ExpErrorIyy1ComponentContextString;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentContextString
    /// </summary>
    public string ExpErrorIyy1ComponentContextString {
      get {
        return(_ExpErrorIyy1ComponentContextString);
      }
      set {
        _ExpErrorIyy1ComponentContextString = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    private char _ExpErrorIyy1ComponentReturnCode_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    public char ExpErrorIyy1ComponentReturnCode_AS {
      get {
        return(_ExpErrorIyy1ComponentReturnCode_AS);
      }
      set {
        _ExpErrorIyy1ComponentReturnCode_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentReturnCode
    /// Domain: Number
    /// Length: 5
    /// Decimal Places: 0
    /// Decimal Precision: N
    /// </summary>
    private int _ExpErrorIyy1ComponentReturnCode;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentReturnCode
    /// </summary>
    public int ExpErrorIyy1ComponentReturnCode {
      get {
        return(_ExpErrorIyy1ComponentReturnCode);
      }
      set {
        _ExpErrorIyy1ComponentReturnCode = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    private char _ExpErrorIyy1ComponentReasonCode_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    public char ExpErrorIyy1ComponentReasonCode_AS {
      get {
        return(_ExpErrorIyy1ComponentReasonCode_AS);
      }
      set {
        _ExpErrorIyy1ComponentReasonCode_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentReasonCode
    /// Domain: Number
    /// Length: 5
    /// Decimal Places: 0
    /// Decimal Precision: N
    /// </summary>
    private int _ExpErrorIyy1ComponentReasonCode;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentReasonCode
    /// </summary>
    public int ExpErrorIyy1ComponentReasonCode {
      get {
        return(_ExpErrorIyy1ComponentReasonCode);
      }
      set {
        _ExpErrorIyy1ComponentReasonCode = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    private char _ExpErrorIyy1ComponentChecksum_AS;
    /// <summary>
    /// Attribute missing flag for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    public char ExpErrorIyy1ComponentChecksum_AS {
      get {
        return(_ExpErrorIyy1ComponentChecksum_AS);
      }
      set {
        _ExpErrorIyy1ComponentChecksum_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ExpErrorIyy1ComponentChecksum
    /// Domain: Text
    /// Length: 15
    /// Varying Length: N
    /// </summary>
    private string _ExpErrorIyy1ComponentChecksum;
    /// <summary>
    /// Attribute for: ExpErrorIyy1ComponentChecksum
    /// </summary>
    public string ExpErrorIyy1ComponentChecksum {
      get {
        return(_ExpErrorIyy1ComponentChecksum);
      }
      set {
        _ExpErrorIyy1ComponentChecksum = value;
      }
    }
    /// <summary>
    /// Default Constructor
    /// </summary>
    
    public MYY10121_OA(  )
    {
      Reset(  );
    }
    /// <summary>
    /// Copy Constructor
    /// </summary>
    
    public MYY10121_OA( MYY10121_OA orig )
    {
      ExpIyy1ParentPinstanceId_AS = orig.ExpIyy1ParentPinstanceId_AS;
      ExpIyy1ParentPinstanceId = orig.ExpIyy1ParentPinstanceId;
      ExpIyy1ParentPreferenceId_AS = orig.ExpIyy1ParentPreferenceId_AS;
      ExpIyy1ParentPreferenceId = orig.ExpIyy1ParentPreferenceId;
      ExpIyy1ParentPcreateUserId_AS = orig.ExpIyy1ParentPcreateUserId_AS;
      ExpIyy1ParentPcreateUserId = orig.ExpIyy1ParentPcreateUserId;
      ExpIyy1ParentPupdateUserId_AS = orig.ExpIyy1ParentPupdateUserId_AS;
      ExpIyy1ParentPupdateUserId = orig.ExpIyy1ParentPupdateUserId;
      ExpIyy1ParentPkeyAttrText_AS = orig.ExpIyy1ParentPkeyAttrText_AS;
      ExpIyy1ParentPkeyAttrText = orig.ExpIyy1ParentPkeyAttrText;
      ExpIyy1ParentPsearchAttrText_AS = orig.ExpIyy1ParentPsearchAttrText_AS;
      ExpIyy1ParentPsearchAttrText = orig.ExpIyy1ParentPsearchAttrText;
      ExpIyy1ParentPotherAttrText_AS = orig.ExpIyy1ParentPotherAttrText_AS;
      ExpIyy1ParentPotherAttrText = orig.ExpIyy1ParentPotherAttrText;
      ExpIyy1ParentPtypeTkeyAttrText_AS = orig.ExpIyy1ParentPtypeTkeyAttrText_AS;
      ExpIyy1ParentPtypeTkeyAttrText = orig.ExpIyy1ParentPtypeTkeyAttrText;
      ExpErrorIyy1ComponentSeverityCode_AS = orig.ExpErrorIyy1ComponentSeverityCode_AS;
      ExpErrorIyy1ComponentSeverityCode = orig.ExpErrorIyy1ComponentSeverityCode;
      ExpErrorIyy1ComponentRollbackIndicator_AS = orig.ExpErrorIyy1ComponentRollbackIndicator_AS;
      ExpErrorIyy1ComponentRollbackIndicator = orig.ExpErrorIyy1ComponentRollbackIndicator;
      ExpErrorIyy1ComponentOriginServid_AS = orig.ExpErrorIyy1ComponentOriginServid_AS;
      ExpErrorIyy1ComponentOriginServid = orig.ExpErrorIyy1ComponentOriginServid;
      ExpErrorIyy1ComponentContextString_AS = orig.ExpErrorIyy1ComponentContextString_AS;
      ExpErrorIyy1ComponentContextString = orig.ExpErrorIyy1ComponentContextString;
      ExpErrorIyy1ComponentReturnCode_AS = orig.ExpErrorIyy1ComponentReturnCode_AS;
      ExpErrorIyy1ComponentReturnCode = orig.ExpErrorIyy1ComponentReturnCode;
      ExpErrorIyy1ComponentReasonCode_AS = orig.ExpErrorIyy1ComponentReasonCode_AS;
      ExpErrorIyy1ComponentReasonCode = orig.ExpErrorIyy1ComponentReasonCode;
      ExpErrorIyy1ComponentChecksum_AS = orig.ExpErrorIyy1ComponentChecksum_AS;
      ExpErrorIyy1ComponentChecksum = orig.ExpErrorIyy1ComponentChecksum;
    }
    /// <summary>
    /// Static instance creator function
    /// </summary>
    
    public static MYY10121_OA GetInstance(  )
    {
      if ( countFree == 0 )
      {
        return(new MYY10121_OA());
      }
      else 
      {
        lock (freeArray)
        {
          if ( countFree == 0 )
          {
            return(new MYY10121_OA());
          }
          else 
          {
            MYY10121_OA result = freeArray[--countFree];
            freeArray[countFree] = null;
            result.Reset(  );
            return(result);
          }
        }
      }
    }
    /// <summary>
    /// Static free instance method
    /// </summary>
    
    public void FreeInstance(  )
    {
      lock (freeArray)
      {
        if ( countFree < freeArray.Length )
        {
          freeArray[countFree++] = this;
        }
      }
    }
    /// <summary>
    /// clone constructor
    /// </summary>
    
    public override Object Clone(  )
    {
      return(new MYY10121_OA(this));
    }
    /// <summary>
    /// Resets all properties to the defaults.
    /// </summary>
    
    public void Reset(  )
    {
      ExpIyy1ParentPinstanceId_AS = ' ';
      ExpIyy1ParentPinstanceId = "00000000000000000000";
      ExpIyy1ParentPreferenceId_AS = ' ';
      ExpIyy1ParentPreferenceId = "00000000000000000000";
      ExpIyy1ParentPcreateUserId_AS = ' ';
      ExpIyy1ParentPcreateUserId = "        ";
      ExpIyy1ParentPupdateUserId_AS = ' ';
      ExpIyy1ParentPupdateUserId = "        ";
      ExpIyy1ParentPkeyAttrText_AS = ' ';
      ExpIyy1ParentPkeyAttrText = "     ";
      ExpIyy1ParentPsearchAttrText_AS = ' ';
      ExpIyy1ParentPsearchAttrText = "                         ";
      ExpIyy1ParentPotherAttrText_AS = ' ';
      ExpIyy1ParentPotherAttrText = "                         ";
      ExpIyy1ParentPtypeTkeyAttrText_AS = ' ';
      ExpIyy1ParentPtypeTkeyAttrText = "    ";
      ExpErrorIyy1ComponentSeverityCode_AS = ' ';
      ExpErrorIyy1ComponentSeverityCode = " ";
      ExpErrorIyy1ComponentRollbackIndicator_AS = ' ';
      ExpErrorIyy1ComponentRollbackIndicator = " ";
      ExpErrorIyy1ComponentOriginServid_AS = ' ';
      ExpErrorIyy1ComponentOriginServid = 0.0;
      ExpErrorIyy1ComponentContextString_AS = ' ';
      ExpErrorIyy1ComponentContextString = "";
      ExpErrorIyy1ComponentReturnCode_AS = ' ';
      ExpErrorIyy1ComponentReturnCode = 0;
      ExpErrorIyy1ComponentReasonCode_AS = ' ';
      ExpErrorIyy1ComponentReasonCode = 0;
      ExpErrorIyy1ComponentChecksum_AS = ' ';
      ExpErrorIyy1ComponentChecksum = "               ";
    }
    /// <summary>
    /// Sets the current state of the instance to the VDF version.
    /// </summary>
    public void SetFromVDF( VDF vdf )
    {
      throw new Exception("can only execute SetFromVDF for a Procedure Step.");
    }
    
    /// <summary>
    /// Gets the VDF version of the current state of the instance.
    /// </summary>
    public VDF GetVDF(  )
    {
      throw new Exception("can only execute GetVDF for a Procedure Step.");
    }
    
    /// <summary>
    /// Sets the current instance based on the passed view.
    /// </summary>
    public void CopyFrom( IExportView orig )
    {
      this.CopyFrom((MYY10121_OA) orig);
    }
    
    /// <summary>
    /// Sets the current instance based on the passed view.
    /// </summary>
    public void CopyFrom( MYY10121_OA orig )
    {
      ExpIyy1ParentPinstanceId_AS = orig.ExpIyy1ParentPinstanceId_AS;
      ExpIyy1ParentPinstanceId = orig.ExpIyy1ParentPinstanceId;
      ExpIyy1ParentPreferenceId_AS = orig.ExpIyy1ParentPreferenceId_AS;
      ExpIyy1ParentPreferenceId = orig.ExpIyy1ParentPreferenceId;
      ExpIyy1ParentPcreateUserId_AS = orig.ExpIyy1ParentPcreateUserId_AS;
      ExpIyy1ParentPcreateUserId = orig.ExpIyy1ParentPcreateUserId;
      ExpIyy1ParentPupdateUserId_AS = orig.ExpIyy1ParentPupdateUserId_AS;
      ExpIyy1ParentPupdateUserId = orig.ExpIyy1ParentPupdateUserId;
      ExpIyy1ParentPkeyAttrText_AS = orig.ExpIyy1ParentPkeyAttrText_AS;
      ExpIyy1ParentPkeyAttrText = orig.ExpIyy1ParentPkeyAttrText;
      ExpIyy1ParentPsearchAttrText_AS = orig.ExpIyy1ParentPsearchAttrText_AS;
      ExpIyy1ParentPsearchAttrText = orig.ExpIyy1ParentPsearchAttrText;
      ExpIyy1ParentPotherAttrText_AS = orig.ExpIyy1ParentPotherAttrText_AS;
      ExpIyy1ParentPotherAttrText = orig.ExpIyy1ParentPotherAttrText;
      ExpIyy1ParentPtypeTkeyAttrText_AS = orig.ExpIyy1ParentPtypeTkeyAttrText_AS;
      ExpIyy1ParentPtypeTkeyAttrText = orig.ExpIyy1ParentPtypeTkeyAttrText;
      ExpErrorIyy1ComponentSeverityCode_AS = orig.ExpErrorIyy1ComponentSeverityCode_AS;
      ExpErrorIyy1ComponentSeverityCode = orig.ExpErrorIyy1ComponentSeverityCode;
      ExpErrorIyy1ComponentRollbackIndicator_AS = orig.ExpErrorIyy1ComponentRollbackIndicator_AS;
      ExpErrorIyy1ComponentRollbackIndicator = orig.ExpErrorIyy1ComponentRollbackIndicator;
      ExpErrorIyy1ComponentOriginServid_AS = orig.ExpErrorIyy1ComponentOriginServid_AS;
      ExpErrorIyy1ComponentOriginServid = orig.ExpErrorIyy1ComponentOriginServid;
      ExpErrorIyy1ComponentContextString_AS = orig.ExpErrorIyy1ComponentContextString_AS;
      ExpErrorIyy1ComponentContextString = orig.ExpErrorIyy1ComponentContextString;
      ExpErrorIyy1ComponentReturnCode_AS = orig.ExpErrorIyy1ComponentReturnCode_AS;
      ExpErrorIyy1ComponentReturnCode = orig.ExpErrorIyy1ComponentReturnCode;
      ExpErrorIyy1ComponentReasonCode_AS = orig.ExpErrorIyy1ComponentReasonCode_AS;
      ExpErrorIyy1ComponentReasonCode = orig.ExpErrorIyy1ComponentReasonCode;
      ExpErrorIyy1ComponentChecksum_AS = orig.ExpErrorIyy1ComponentChecksum_AS;
      ExpErrorIyy1ComponentChecksum = orig.ExpErrorIyy1ComponentChecksum;
    }
  }
}
