// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2024 CA Technologies. All rights reserved.
//
//    Name: MYY10221_IA                      Date: 2024/01/09
//    User: AliAl                            Time: 13:42:04
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// using Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
using System;
using com.ca.gen.vwrt;
using com.ca.gen.vwrt.types;
using com.ca.gen.vwrt.vdf;
using com.ca.gen.csu.exception;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF IMPORT VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
namespace GEN.ORT.YYY
{
  /// <summary>
  /// Internal data view storage for: MYY10221_IA
  /// </summary>
  [Serializable]
  public class MYY10221_IA : ViewBase, IImportView
  {
    private static MYY10221_IA[] freeArray = new MYY10221_IA[30];
    private static int countFree = 0;
    
    // Entity View: IMP
    //        Type: IYY1_CHILD
    /// <summary>
    /// Internal storage for attribute missing flag for: ImpIyy1ChildCinstanceId
    /// </summary>
    private char _ImpIyy1ChildCinstanceId_AS;
    /// <summary>
    /// Attribute missing flag for: ImpIyy1ChildCinstanceId
    /// </summary>
    public char ImpIyy1ChildCinstanceId_AS {
      get {
        return(_ImpIyy1ChildCinstanceId_AS);
      }
      set {
        _ImpIyy1ChildCinstanceId_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ImpIyy1ChildCinstanceId
    /// Domain: Timestamp
    /// Length: 20
    /// </summary>
    private string _ImpIyy1ChildCinstanceId;
    /// <summary>
    /// Attribute for: ImpIyy1ChildCinstanceId
    /// </summary>
    public string ImpIyy1ChildCinstanceId {
      get {
        return(_ImpIyy1ChildCinstanceId);
      }
      set {
        _ImpIyy1ChildCinstanceId = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ImpIyy1ChildCparentPkeyAttrText
    /// </summary>
    private char _ImpIyy1ChildCparentPkeyAttrText_AS;
    /// <summary>
    /// Attribute missing flag for: ImpIyy1ChildCparentPkeyAttrText
    /// </summary>
    public char ImpIyy1ChildCparentPkeyAttrText_AS {
      get {
        return(_ImpIyy1ChildCparentPkeyAttrText_AS);
      }
      set {
        _ImpIyy1ChildCparentPkeyAttrText_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ImpIyy1ChildCparentPkeyAttrText
    /// Domain: Text
    /// Length: 5
    /// Varying Length: N
    /// </summary>
    private string _ImpIyy1ChildCparentPkeyAttrText;
    /// <summary>
    /// Attribute for: ImpIyy1ChildCparentPkeyAttrText
    /// </summary>
    public string ImpIyy1ChildCparentPkeyAttrText {
      get {
        return(_ImpIyy1ChildCparentPkeyAttrText);
      }
      set {
        _ImpIyy1ChildCparentPkeyAttrText = value;
      }
    }
    /// <summary>
    /// Internal storage for attribute missing flag for: ImpIyy1ChildCkeyAttrNum
    /// </summary>
    private char _ImpIyy1ChildCkeyAttrNum_AS;
    /// <summary>
    /// Attribute missing flag for: ImpIyy1ChildCkeyAttrNum
    /// </summary>
    public char ImpIyy1ChildCkeyAttrNum_AS {
      get {
        return(_ImpIyy1ChildCkeyAttrNum_AS);
      }
      set {
        _ImpIyy1ChildCkeyAttrNum_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: ImpIyy1ChildCkeyAttrNum
    /// Domain: Number
    /// Length: 6
    /// Decimal Places: 0
    /// Decimal Precision: N
    /// </summary>
    private int _ImpIyy1ChildCkeyAttrNum;
    /// <summary>
    /// Attribute for: ImpIyy1ChildCkeyAttrNum
    /// </summary>
    public int ImpIyy1ChildCkeyAttrNum {
      get {
        return(_ImpIyy1ChildCkeyAttrNum);
      }
      set {
        _ImpIyy1ChildCkeyAttrNum = value;
      }
    }
    /// <summary>
    /// Default Constructor
    /// </summary>
    
    public MYY10221_IA(  )
    {
      Reset(  );
    }
    /// <summary>
    /// Copy Constructor
    /// </summary>
    
    public MYY10221_IA( MYY10221_IA orig )
    {
      ImpIyy1ChildCinstanceId_AS = orig.ImpIyy1ChildCinstanceId_AS;
      ImpIyy1ChildCinstanceId = orig.ImpIyy1ChildCinstanceId;
      ImpIyy1ChildCparentPkeyAttrText_AS = orig.ImpIyy1ChildCparentPkeyAttrText_AS;
      ImpIyy1ChildCparentPkeyAttrText = orig.ImpIyy1ChildCparentPkeyAttrText;
      ImpIyy1ChildCkeyAttrNum_AS = orig.ImpIyy1ChildCkeyAttrNum_AS;
      ImpIyy1ChildCkeyAttrNum = orig.ImpIyy1ChildCkeyAttrNum;
    }
    /// <summary>
    /// Static instance creator function
    /// </summary>
    
    public static MYY10221_IA GetInstance(  )
    {
      if ( countFree == 0 )
      {
        return(new MYY10221_IA());
      }
      else 
      {
        lock (freeArray)
        {
          if ( countFree == 0 )
          {
            return(new MYY10221_IA());
          }
          else 
          {
            MYY10221_IA result = freeArray[--countFree];
            freeArray[countFree] = null;
            result.Reset(  );
            return(result);
          }
        }
      }
    }
    /// <summary>
    /// Static free instance method
    /// </summary>
    
    public void FreeInstance(  )
    {
      lock (freeArray)
      {
        if ( countFree < freeArray.Length )
        {
          freeArray[countFree++] = this;
        }
      }
    }
    /// <summary>
    /// clone constructor
    /// </summary>
    
    public override Object Clone(  )
    {
      return(new MYY10221_IA(this));
    }
    /// <summary>
    /// Resets all properties to the defaults.
    /// </summary>
    
    public void Reset(  )
    {
      ImpIyy1ChildCinstanceId_AS = ' ';
      ImpIyy1ChildCinstanceId = "00000000000000000000";
      ImpIyy1ChildCparentPkeyAttrText_AS = ' ';
      ImpIyy1ChildCparentPkeyAttrText = "     ";
      ImpIyy1ChildCkeyAttrNum_AS = ' ';
      ImpIyy1ChildCkeyAttrNum = 0;
    }
    /// <summary>
    /// Gets the VDF version of the current state of the instance.
    /// </summary>
    public VDF GetVDF(  )
    {
      throw new Exception("can only execute GetVDF for a Procedure Step.");
    }
    
    /// <summary>
    /// Sets the current state of the instance to the VDF version.
    /// </summary>
    public void SetFromVDF( VDF vdf )
    {
      throw new Exception("can only execute SetFromVDF for a Procedure Step.");
    }
    
    /// <summary>
    /// Sets the current instance based on the passed view.
    /// </summary>
    public void CopyFrom( IImportView orig )
    {
      this.CopyFrom((MYY10221_IA) orig);
    }
    
    /// <summary>
    /// Sets the current instance based on the passed view.
    /// </summary>
    public void CopyFrom( MYY10221_IA orig )
    {
      ImpIyy1ChildCinstanceId_AS = orig.ImpIyy1ChildCinstanceId_AS;
      ImpIyy1ChildCinstanceId = orig.ImpIyy1ChildCinstanceId;
      ImpIyy1ChildCparentPkeyAttrText_AS = orig.ImpIyy1ChildCparentPkeyAttrText_AS;
      ImpIyy1ChildCparentPkeyAttrText = orig.ImpIyy1ChildCparentPkeyAttrText;
      ImpIyy1ChildCkeyAttrNum_AS = orig.ImpIyy1ChildCkeyAttrNum_AS;
      ImpIyy1ChildCkeyAttrNum = orig.ImpIyy1ChildCkeyAttrNum;
    }
  }
}
