// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
//
//                    Source Code Generated by
//                           CA Gen 8.6
//
//    Copyright (c) 2024 CA Technologies. All rights reserved.
//
//    Name: SYYY0351_LA                      Date: 2024/01/09
//    User: AliAl                            Time: 13:40:22
//
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// using Statements
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
using System;
using com.ca.gen.vwrt;
using com.ca.gen.vwrt.types;
using com.ca.gen.vwrt.vdf;
using com.ca.gen.csu.exception;

// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
// START OF LOCAL VIEW
// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *
namespace GEN.ORT.YYY
{
  /// <summary>
  /// Internal data view storage for: SYYY0351_LA
  /// </summary>
  [Serializable]
  public class SYYY0351_LA : ViewBase, ILocalView
  {
    private static SYYY0351_LA[] freeArray = new SYYY0351_LA[30];
    private static int countFree = 0;
    
    // Entity View: LOC_FILTER
    //        Type: IYY1_LIST
    /// <summary>
    /// Internal storage for attribute missing flag for: LocFilterIyy1ListScrollType
    /// </summary>
    private char _LocFilterIyy1ListScrollType_AS;
    /// <summary>
    /// Attribute missing flag for: LocFilterIyy1ListScrollType
    /// </summary>
    public char LocFilterIyy1ListScrollType_AS {
      get {
        return(_LocFilterIyy1ListScrollType_AS);
      }
      set {
        _LocFilterIyy1ListScrollType_AS = value;
      }
    }
    /// <summary>
    /// Internal storage, attribute for: LocFilterIyy1ListScrollType
    /// Domain: Text
    /// Length: 1
    /// Varying Length: N
    /// </summary>
    private string _LocFilterIyy1ListScrollType;
    /// <summary>
    /// Attribute for: LocFilterIyy1ListScrollType
    /// </summary>
    public string LocFilterIyy1ListScrollType {
      get {
        return(_LocFilterIyy1ListScrollType);
      }
      set {
        _LocFilterIyy1ListScrollType = value;
      }
    }
    /// <summary>
    /// Default Constructor
    /// </summary>
    
    public SYYY0351_LA(  )
    {
      Reset(  );
    }
    /// <summary>
    /// Copy Constructor
    /// </summary>
    
    public SYYY0351_LA( SYYY0351_LA orig )
    {
      LocFilterIyy1ListScrollType_AS = orig.LocFilterIyy1ListScrollType_AS;
      LocFilterIyy1ListScrollType = orig.LocFilterIyy1ListScrollType;
    }
    /// <summary>
    /// Static instance creator function
    /// </summary>
    
    public static SYYY0351_LA GetInstance(  )
    {
      if ( countFree == 0 )
      {
        return(new SYYY0351_LA());
      }
      else 
      {
        lock (freeArray)
        {
          if ( countFree == 0 )
          {
            return(new SYYY0351_LA());
          }
          else 
          {
            SYYY0351_LA result = freeArray[--countFree];
            freeArray[countFree] = null;
            result.Reset(  );
            return(result);
          }
        }
      }
    }
    /// <summary>
    /// Static free instance method
    /// </summary>
    
    public void FreeInstance(  )
    {
      lock (freeArray)
      {
        if ( countFree < freeArray.Length )
        {
          freeArray[countFree++] = this;
        }
      }
    }
    /// <summary>
    /// clone constructor
    /// </summary>
    
    public override Object Clone(  )
    {
      return(new SYYY0351_LA(this));
    }
    /// <summary>
    /// Resets all properties to the defaults.
    /// </summary>
    
    public void Reset(  )
    {
      LocFilterIyy1ListScrollType_AS = ' ';
      LocFilterIyy1ListScrollType = " ";
    }
  }
}
